#!/usr/bin/env bash
# 从 Cloudflare 官方拉取最新回源 IP 段，生成 nginx / 防火墙配置
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT_DIR="$ROOT/deploy/origin-shield"
NGINX_REALIP="$ROOT/docker/nginx/cloudflare-realip.conf"
NGINX_SHIELD="$ROOT/docker/nginx/origin-shield.prod.conf"

mkdir -p "$OUT_DIR"

curl -fsSL https://www.cloudflare.com/ips-v4 -o "$OUT_DIR/ips-v4.txt"
curl -fsSL https://www.cloudflare.com/ips-v6 -o "$OUT_DIR/ips-v6.txt"

{
  echo "# Auto-generated by fetch-cloudflare-ips.sh — DO NOT EDIT"
  echo "# Cloudflare 回源 IP 信任"
  echo ""
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
  echo ""
  echo "# IPv4"
  while read -r cidr; do
    [[ -n "$cidr" ]] && echo "set_real_ip_from $cidr;"
  done < "$OUT_DIR/ips-v4.txt"
  echo ""
  echo "# IPv6"
  while read -r cidr; do
    [[ -n "$cidr" ]] && echo "set_real_ip_from $cidr;"
  done < "$OUT_DIR/ips-v6.txt"
} > "$NGINX_REALIP"

{
  echo "# Auto-generated by fetch-cloudflare-ips.sh — DO NOT EDIT"
  echo "# 源站隐匿 — 生产模式"
  echo ""
  echo "geo \$realip_remote_addr \$origin_shield_allowed {"
  echo "    default 0;"
  echo ""
  echo "    # 本机 / 内网健康检查"
  echo "    127.0.0.1 1;"
  echo "    ::1       1;"
  echo "    10.0.0.0/8 1;"
  echo "    172.16.0.0/12 1;"
  echo "    192.168.0.0/16 1;"
  echo ""
  echo "    # Cloudflare IPv4"
  while read -r cidr; do
    [[ -n "$cidr" ]] && echo "    $cidr 1;"
  done < "$OUT_DIR/ips-v4.txt"
  echo ""
  echo "    # Cloudflare IPv6"
  while read -r cidr; do
    [[ -n "$cidr" ]] && echo "    $cidr 1;"
  done < "$OUT_DIR/ips-v6.txt"
  echo "}"
} > "$NGINX_SHIELD"

echo "Updated:"
echo "  $NGINX_REALIP"
echo "  $NGINX_SHIELD"
echo "  $OUT_DIR/ips-v4.txt"
echo "  $OUT_DIR/ips-v6.txt"
