// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminUsersFieldNames          = builder.RawFieldNames(&AdminUsers{})
	adminUsersRows                = strings.Join(adminUsersFieldNames, ",")
	adminUsersRowsExpectAutoSet   = strings.Join(stringx.Remove(adminUsersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminUsersRowsWithPlaceHolder = strings.Join(stringx.Remove(adminUsersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	adminUsersModel interface {
		Insert(ctx context.Context, data *AdminUsers) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AdminUsers, error)
		FindOneByUsername(ctx context.Context, username string) (*AdminUsers, error)
		Update(ctx context.Context, data *AdminUsers) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAdminUsersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	// AdminUsers 对应表 admin_users：管理后台用户
	AdminUsers struct {
		Id                 uint64         `db:"id"`                   // 主键
		Username           string         `db:"username"`             // 用户名
		PasswordHash       string         `db:"password_hash"`        // 密码哈希（bcrypt）
		RoleId             uint64         `db:"role_id"`              // 角色 ID（roles.id）
		Status             int64          `db:"status"`               // 状态：1=启用 0=停用
		TotpSecret         sql.NullString `db:"totp_secret"`          // TOTP 密钥（加密存储）
		TotpEnabled        int64          `db:"totp_enabled"`         // 1=已启用二次验证 0=未启用
		TotpRecoveryHashes sql.NullString `db:"totp_recovery_hashes"` // 一次性恢复码的 bcrypt 哈希
		CreatedAt          time.Time      `db:"created_at"`           // 创建时间（UTC）
		UpdatedAt          time.Time      `db:"updated_at"`           // 更新时间（UTC）
	}
)

func newAdminUsersModel(conn sqlx.SqlConn) *defaultAdminUsersModel {
	return &defaultAdminUsersModel{
		conn:  conn,
		table: "`admin_users`",
	}
}

func (m *defaultAdminUsersModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAdminUsersModel) FindOne(ctx context.Context, id uint64) (*AdminUsers, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminUsersRows, m.table)
	var resp AdminUsers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminUsersModel) FindOneByUsername(ctx context.Context, username string) (*AdminUsers, error) {
	var resp AdminUsers
	query := fmt.Sprintf("select %s from %s where `username` = ? limit 1", adminUsersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, username)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminUsersModel) Insert(ctx context.Context, data *AdminUsers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, adminUsersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Username, data.PasswordHash, data.RoleId, data.Status, data.TotpSecret, data.TotpEnabled, data.TotpRecoveryHashes)
	return ret, err
}

func (m *defaultAdminUsersModel) Update(ctx context.Context, newData *AdminUsers) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminUsersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Username, newData.PasswordHash, newData.RoleId, newData.Status, newData.TotpSecret, newData.TotpEnabled, newData.TotpRecoveryHashes, newData.Id)
	return err
}

func (m *defaultAdminUsersModel) tableName() string {
	return m.table
}
