// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameConfigsFieldNames          = builder.RawFieldNames(&GameConfigs{})
	gameConfigsRows                = strings.Join(gameConfigsFieldNames, ",")
	gameConfigsRowsExpectAutoSet   = strings.Join(stringx.Remove(gameConfigsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameConfigsRowsWithPlaceHolder = strings.Join(stringx.Remove(gameConfigsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gameConfigsModel interface {
		Insert(ctx context.Context, data *GameConfigs) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*GameConfigs, error)
		FindOneByMerchantIdGameCodeConfigKey(ctx context.Context, merchantId uint64, gameCode string, configKey string) (*GameConfigs, error)
		Update(ctx context.Context, data *GameConfigs) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultGameConfigsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GameConfigs struct {
		Id          uint64         `db:"id"`
		MerchantId  uint64         `db:"merchant_id"`
		GameCode    string         `db:"game_code"`
		ConfigKey   string         `db:"config_key"`
		ConfigValue string         `db:"config_value"`
		RtpTier     sql.NullString `db:"rtp_tier"`
		Status      int64          `db:"status"`
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newGameConfigsModel(conn sqlx.SqlConn) *defaultGameConfigsModel {
	return &defaultGameConfigsModel{
		conn:  conn,
		table: "`game_configs`",
	}
}

func (m *defaultGameConfigsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGameConfigsModel) FindOne(ctx context.Context, id uint64) (*GameConfigs, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameConfigsRows, m.table)
	var resp GameConfigs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameConfigsModel) FindOneByMerchantIdGameCodeConfigKey(ctx context.Context, merchantId uint64, gameCode string, configKey string) (*GameConfigs, error) {
	var resp GameConfigs
	query := fmt.Sprintf("select %s from %s where `merchant_id` = ? and `game_code` = ? and `config_key` = ? limit 1", gameConfigsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, merchantId, gameCode, configKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameConfigsModel) Insert(ctx context.Context, data *GameConfigs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, gameConfigsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MerchantId, data.GameCode, data.ConfigKey, data.ConfigValue, data.RtpTier, data.Status)
	return ret, err
}

func (m *defaultGameConfigsModel) Update(ctx context.Context, newData *GameConfigs) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameConfigsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.MerchantId, newData.GameCode, newData.ConfigKey, newData.ConfigValue, newData.RtpTier, newData.Status, newData.Id)
	return err
}

func (m *defaultGameConfigsModel) tableName() string {
	return m.table
}
