// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantsFieldNames          = builder.RawFieldNames(&Merchants{})
	merchantsRows                = strings.Join(merchantsFieldNames, ",")
	merchantsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantsRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	merchantsModel interface {
		Insert(ctx context.Context, data *Merchants) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Merchants, error)
		FindOneByMerchantCode(ctx context.Context, merchantCode string) (*Merchants, error)
		Update(ctx context.Context, data *Merchants) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMerchantsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	// Merchants 对应表 merchants：商户主体
	Merchants struct {
		Id                      uint64         `db:"id"`                          // 主键
		MerchantCode            string         `db:"merchant_code"`               // 商户唯一编码
		Name                    string         `db:"name"`                        // 商户名称
		PublicKey               sql.NullString `db:"public_key"`                  // API 公钥
		PrivateKey              sql.NullString `db:"private_key"`                 // API 私钥 (加密存储)
		PrivateKeyPrev          sql.NullString `db:"private_key_prev"`            // 轮换过渡期旧私钥
		PrivateKeyPrevExpiresAt sql.NullTime   `db:"private_key_prev_expires_at"` // 旧私钥失效时间
		AllowedIPs              sql.NullString `db:"allowed_ips"`                 // 聚合器报备公网 IP 白名单
		Status                  int64          `db:"status"`                      // 1=启用 0=禁用
		CreatedAt               time.Time      `db:"created_at"`                  // 创建时间（UTC）
		UpdatedAt               time.Time      `db:"updated_at"`                  // 更新时间（UTC）
	}
)

func newMerchantsModel(conn sqlx.SqlConn) *defaultMerchantsModel {
	return &defaultMerchantsModel{
		conn:  conn,
		table: "`merchants`",
	}
}

func (m *defaultMerchantsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMerchantsModel) FindOne(ctx context.Context, id uint64) (*Merchants, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantsRows, m.table)
	var resp Merchants
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantsModel) FindOneByMerchantCode(ctx context.Context, merchantCode string) (*Merchants, error) {
	var resp Merchants
	query := fmt.Sprintf("select %s from %s where `merchant_code` = ? limit 1", merchantsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, merchantCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantsModel) Insert(ctx context.Context, data *Merchants) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MerchantCode, data.Name, data.PublicKey, data.PrivateKey, data.PrivateKeyPrev, data.PrivateKeyPrevExpiresAt, data.AllowedIPs, data.Status)
	return ret, err
}

func (m *defaultMerchantsModel) Update(ctx context.Context, newData *Merchants) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.MerchantCode, newData.Name, newData.PublicKey, newData.PrivateKey, newData.PrivateKeyPrev, newData.PrivateKeyPrevExpiresAt, newData.AllowedIPs, newData.Status, newData.Id)
	return err
}

func (m *defaultMerchantsModel) tableName() string {
	return m.table
}
