// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"fastgame/services/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/game-configs",
					Handler: GameConfigListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/game-configs",
					Handler: UpsertGameConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/merchants",
					Handler: MerchantListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/merchants",
					Handler: CreateMerchantHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/merchants/:id",
					Handler: UpdateMerchantHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/merchants/:id/rotate-key",
					Handler: RotateMerchantKeyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/merchants/:id/allowed-ips",
					Handler: GetMerchantAllowedIPsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/merchants/:id/allowed-ips",
					Handler: UpdateMerchantAllowedIPsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/risk-blacklist",
					Handler: BlacklistListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/risk-blacklist",
					Handler: CreateBlacklistHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/risk-blacklist/:id",
					Handler: DeleteBlacklistHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/reports/rtp",
					Handler: RtpReportHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/traces/:traceId",
					Handler: GetTraceHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/risk-alerts",
					Handler: RiskAlertsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)
}
