// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameMathModelsFieldNames          = builder.RawFieldNames(&GameMathModels{})
	gameMathModelsRows                = strings.Join(gameMathModelsFieldNames, ",")
	gameMathModelsRowsExpectAutoSet   = strings.Join(stringx.Remove(gameMathModelsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameMathModelsRowsWithPlaceHolder = strings.Join(stringx.Remove(gameMathModelsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameGameMathModelsIdPrefix                = "biz:fastgame:gameMathModels:id:"
	bizFastgameGameMathModelsGameIdMathVersionPrefix = "biz:fastgame:gameMathModels:gameId:mathVersion:"
)

type (
	gameMathModelsModel interface {
		Insert(ctx context.Context, data *GameMathModels) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*GameMathModels, error)
		FindOneByGameIdMathVersion(ctx context.Context, gameId uint64, mathVersion string) (*GameMathModels, error)
		Update(ctx context.Context, data *GameMathModels) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultGameMathModelsModel struct {
		sqlc.CachedConn
		table string
	}

	GameMathModels struct {
		Id                  uint64    `db:"id"`                    // è‡ªå¢žä¸»é”®ID
		GameId              uint64    `db:"game_id"`               // å…³è”æ¸¸æˆID (games.id)
		GameCode            string    `db:"game_code"`             // æ¸¸æˆä»£å·
		MathVersion         string    `db:"math_version"`          // æ•°å­¦æ¨¡åž‹ç‰ˆæœ¬å· (å¦‚: v1.0.0_tier96)
		RtpTier             float64   `db:"rtp_tier"`              // å¯¹åº”çš„æ ‡ç§°ç†è®º RTP (å¦‚ 96.00)
		ParTableChecksum    string    `db:"par_table_checksum"`    // æƒé‡è¡¨é™æ€æ•°ç»„çš„ SHA256 æŒ‡çº¹ (è¯æ˜Žæœªè¢«ç¯¡æ”¹)
		ParTableContent     string    `db:"par_table_content"`     // å®Œæ•´çš„ç¦»æ•£æ¦‚çŽ‡ä¸Žå‡ºå¥–å€çŽ‡æ˜ å°„æ•°ç»„é…ç½®
		SimulationSpins     uint64    `db:"simulation_spins"`      // ä¸Šçº¿å‰è®¡ç®—æœºæ¨¡æ‹ŸåŽ‹æµ‹å±€æ•° (å¦‚1äº¿å±€)
		SimulationActualRtp float64   `db:"simulation_actual_rtp"` // æ¨¡æ‹Ÿæµ‹è¯•å®žé™…è·‘å‡ºçš„æ”¶æ•› RTP (å¦‚ 0.9599)
		CertifiedBy         string    `db:"certified_by"`          // ç®—æ³•è®¤è¯æœºæž„æˆ–å†…éƒ¨ç­¾å (å¦‚: GLI, BMM, INTERNAL)
		IsActive            uint64    `db:"is_active"`             // æ˜¯å¦å¯ç”¨: 0-åœç”¨, 1-çŽ°è¡Œç”Ÿæ•ˆ
		CreatedAt           time.Time `db:"created_at"`            // åˆ›å»ºæ—¶é—´
	}
)

func newGameMathModelsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGameMathModelsModel {
	return &defaultGameMathModelsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`game_math_models`",
	}
}

func (m *defaultGameMathModelsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameGameMathModelsGameIdMathVersionKey := fmt.Sprintf("%s%v:%v", bizFastgameGameMathModelsGameIdMathVersionPrefix, data.GameId, data.MathVersion)
	fastgameGameMathModelsIdKey := fmt.Sprintf("%s%v", bizFastgameGameMathModelsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameGameMathModelsGameIdMathVersionKey, fastgameGameMathModelsIdKey)
	return err
}

func (m *defaultGameMathModelsModel) FindOne(ctx context.Context, id uint64) (*GameMathModels, error) {
	fastgameGameMathModelsIdKey := fmt.Sprintf("%s%v", bizFastgameGameMathModelsIdPrefix, id)
	var resp GameMathModels
	err := m.QueryRowCtx(ctx, &resp, fastgameGameMathModelsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameMathModelsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameMathModelsModel) FindOneByGameIdMathVersion(ctx context.Context, gameId uint64, mathVersion string) (*GameMathModels, error) {
	fastgameGameMathModelsGameIdMathVersionKey := fmt.Sprintf("%s%v:%v", bizFastgameGameMathModelsGameIdMathVersionPrefix, gameId, mathVersion)
	var resp GameMathModels
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameGameMathModelsGameIdMathVersionKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `game_id` = ? and `math_version` = ? limit 1", gameMathModelsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, gameId, mathVersion); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameMathModelsModel) Insert(ctx context.Context, data *GameMathModels) (sql.Result, error) {
	fastgameGameMathModelsGameIdMathVersionKey := fmt.Sprintf("%s%v:%v", bizFastgameGameMathModelsGameIdMathVersionPrefix, data.GameId, data.MathVersion)
	fastgameGameMathModelsIdKey := fmt.Sprintf("%s%v", bizFastgameGameMathModelsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, gameMathModelsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GameId, data.GameCode, data.MathVersion, data.RtpTier, data.ParTableChecksum, data.ParTableContent, data.SimulationSpins, data.SimulationActualRtp, data.CertifiedBy, data.IsActive)
	}, fastgameGameMathModelsGameIdMathVersionKey, fastgameGameMathModelsIdKey)
	return ret, err
}

func (m *defaultGameMathModelsModel) Update(ctx context.Context, newData *GameMathModels) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameGameMathModelsGameIdMathVersionKey := fmt.Sprintf("%s%v:%v", bizFastgameGameMathModelsGameIdMathVersionPrefix, data.GameId, data.MathVersion)
	fastgameGameMathModelsIdKey := fmt.Sprintf("%s%v", bizFastgameGameMathModelsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameMathModelsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.GameId, newData.GameCode, newData.MathVersion, newData.RtpTier, newData.ParTableChecksum, newData.ParTableContent, newData.SimulationSpins, newData.SimulationActualRtp, newData.CertifiedBy, newData.IsActive, newData.Id)
	}, fastgameGameMathModelsGameIdMathVersionKey, fastgameGameMathModelsIdKey)
	return err
}

func (m *defaultGameMathModelsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameGameMathModelsIdPrefix, primary)
}

func (m *defaultGameMathModelsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameMathModelsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGameMathModelsModel) tableName() string {
	return m.table
}
