// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameTransactionsFieldNames          = builder.RawFieldNames(&GameTransactions{})
	gameTransactionsRows                = strings.Join(gameTransactionsFieldNames, ",")
	gameTransactionsRowsExpectAutoSet   = strings.Join(stringx.Remove(gameTransactionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameTransactionsRowsWithPlaceHolder = strings.Join(stringx.Remove(gameTransactionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameGameTransactionsIdPrefix            = "biz:fastgame:gameTransactions:id:"
	bizFastgameGameTransactionsTransactionIdPrefix = "biz:fastgame:gameTransactions:transactionId:"
)

type (
	gameTransactionsModel interface {
		Insert(ctx context.Context, data *GameTransactions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*GameTransactions, error)
		FindOneByTransactionId(ctx context.Context, transactionId string) (*GameTransactions, error)
		Update(ctx context.Context, data *GameTransactions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultGameTransactionsModel struct {
		sqlc.CachedConn
		table string
	}

	GameTransactions struct {
		Id            uint64    `db:"id"`             // 账变自增主键ID
		TransactionId string    `db:"transaction_id"` // 我方系统全局唯一账变流水号 (雪花算法生成，TxID)
		ExternalTxId  string    `db:"external_tx_id"` // 下游无缝钱包返回的三方对账凭据号 (External TxID)
		RoundId       string    `db:"round_id"`       // 归属单局业务唯一流水号 (Round ID)
		MerchantId    uint64    `db:"merchant_id"`    // 关联商户ID
		MerchantCode  string    `db:"merchant_code"`  // 商户代号冗余
		GameId        uint64    `db:"game_id"`        // 关联游戏ID
		GameCode      string    `db:"game_code"`      // 游戏代号冗余
		UserId        string    `db:"user_id"`        // 玩家在下游系统的唯一ID
		Currency      string    `db:"currency"`       // 交易结算币种
		Direction     string    `db:"direction"`      // 资金流向: IN (玩家进账/派彩), OUT (玩家出资/扣款)
		TxType        string    `db:"tx_type"`        // 账变类型: BET (有效下注扣款), WIN (派彩中奖), REFUND (异常退款), ROLLBACK (撤单回滚), PROMO_CREDIT (活动空投)
		Amount        int64     `db:"amount"`         // 发生变动的绝对金额 (分，必须 > 0)
		BalanceBefore int64     `db:"balance_before"` // 账变前玩家余额快照 (若下游钱包返回则记录，分)
		BalanceAfter  int64     `db:"balance_after"`  // 账变后玩家余额快照 (若下游钱包返回则记录，分)
		IsDemo        uint64    `db:"is_demo"`        // 模式标识: 0-真实货币账变, 1-虚拟试玩账变
		Status        string    `db:"status"`         // 账变终态: SUCCESS (成功落账), FAILED (下游扣款失败), PENDING_RETRY (挂起进死信补偿)
		Remark        string    `db:"remark"`         // 账变原因/上下文备注
		CreatedAt     time.Time `db:"created_at"`     // 账变产生时间
	}
)

func newGameTransactionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGameTransactionsModel {
	return &defaultGameTransactionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`game_transactions`",
	}
}

func (m *defaultGameTransactionsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameGameTransactionsIdKey := fmt.Sprintf("%s%v", bizFastgameGameTransactionsIdPrefix, id)
	fastgameGameTransactionsTransactionIdKey := fmt.Sprintf("%s%v", bizFastgameGameTransactionsTransactionIdPrefix, data.TransactionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameGameTransactionsIdKey, fastgameGameTransactionsTransactionIdKey)
	return err
}

func (m *defaultGameTransactionsModel) FindOne(ctx context.Context, id uint64) (*GameTransactions, error) {
	fastgameGameTransactionsIdKey := fmt.Sprintf("%s%v", bizFastgameGameTransactionsIdPrefix, id)
	var resp GameTransactions
	err := m.QueryRowCtx(ctx, &resp, fastgameGameTransactionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameTransactionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameTransactionsModel) FindOneByTransactionId(ctx context.Context, transactionId string) (*GameTransactions, error) {
	fastgameGameTransactionsTransactionIdKey := fmt.Sprintf("%s%v", bizFastgameGameTransactionsTransactionIdPrefix, transactionId)
	var resp GameTransactions
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameGameTransactionsTransactionIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `transaction_id` = ? limit 1", gameTransactionsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, transactionId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameTransactionsModel) Insert(ctx context.Context, data *GameTransactions) (sql.Result, error) {
	fastgameGameTransactionsIdKey := fmt.Sprintf("%s%v", bizFastgameGameTransactionsIdPrefix, data.Id)
	fastgameGameTransactionsTransactionIdKey := fmt.Sprintf("%s%v", bizFastgameGameTransactionsTransactionIdPrefix, data.TransactionId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, gameTransactionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TransactionId, data.ExternalTxId, data.RoundId, data.MerchantId, data.MerchantCode, data.GameId, data.GameCode, data.UserId, data.Currency, data.Direction, data.TxType, data.Amount, data.BalanceBefore, data.BalanceAfter, data.IsDemo, data.Status, data.Remark)
	}, fastgameGameTransactionsIdKey, fastgameGameTransactionsTransactionIdKey)
	return ret, err
}

func (m *defaultGameTransactionsModel) Update(ctx context.Context, newData *GameTransactions) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameGameTransactionsIdKey := fmt.Sprintf("%s%v", bizFastgameGameTransactionsIdPrefix, data.Id)
	fastgameGameTransactionsTransactionIdKey := fmt.Sprintf("%s%v", bizFastgameGameTransactionsTransactionIdPrefix, data.TransactionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameTransactionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TransactionId, newData.ExternalTxId, newData.RoundId, newData.MerchantId, newData.MerchantCode, newData.GameId, newData.GameCode, newData.UserId, newData.Currency, newData.Direction, newData.TxType, newData.Amount, newData.BalanceBefore, newData.BalanceAfter, newData.IsDemo, newData.Status, newData.Remark, newData.Id)
	}, fastgameGameTransactionsIdKey, fastgameGameTransactionsTransactionIdKey)
	return err
}

func (m *defaultGameTransactionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameGameTransactionsIdPrefix, primary)
}

func (m *defaultGameTransactionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameTransactionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGameTransactionsModel) tableName() string {
	return m.table
}
