// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameRoundsFieldNames          = builder.RawFieldNames(&GameRounds{})
	gameRoundsRows                = strings.Join(gameRoundsFieldNames, ",")
	gameRoundsRowsExpectAutoSet   = strings.Join(stringx.Remove(gameRoundsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameRoundsRowsWithPlaceHolder = strings.Join(stringx.Remove(gameRoundsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameGameRoundsIdPrefix      = "biz:fastgame:gameRounds:id:"
	bizFastgameGameRoundsRoundIdPrefix = "biz:fastgame:gameRounds:roundId:"
)

type (
	gameRoundsModel interface {
		Insert(ctx context.Context, data *GameRounds) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*GameRounds, error)
		FindOneByRoundId(ctx context.Context, roundId string) (*GameRounds, error)
		Update(ctx context.Context, data *GameRounds) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultGameRoundsModel struct {
		sqlc.CachedConn
		table string
	}

	GameRounds struct {
		Id               uint64    `db:"id"`                // 自增主键ID
		RoundId          string    `db:"round_id"`          // 单局业务全局唯一号 (全链路业务主键)
		MerchantId       uint64    `db:"merchant_id"`       // 关联商户ID
		MerchantCode     string    `db:"merchant_code"`     // 商户唯一代号
		GameId           uint64    `db:"game_id"`           // 关联游戏ID
		GameCode         string    `db:"game_code"`         // 游戏全局唯一代号
		MathVersion      string    `db:"math_version"`      // 运算使用的数学模型版本号 (对齐 game_math_models)
		UserId           string    `db:"user_id"`           // 玩家在下游系统的唯一ID
		Currency         string    `db:"currency"`          // 原始结算货币代号
		BetAmount        int64     `db:"bet_amount"`        // 原币种总下注金额 (分)
		WinAmount        int64     `db:"win_amount"`        // 原币种总派彩金额 (分，0为未中奖)
		NetAmount        int64     `db:"net_amount"`        // 平台单局净盈亏 (分): bet_amount - win_amount
		PayoutMultiplier float64   `db:"payout_multiplier"` // 计算出的实际返还倍率 (win_amount / bet_amount)
		ExchangeRateUsd  float64   `db:"exchange_rate_usd"` // 对账发生时相对 USD 的快照汇率
		BetAmountUsd     int64     `db:"bet_amount_usd"`    // 折算为 USD 的投注额 (USD 分)
		WinAmountUsd     int64     `db:"win_amount_usd"`    // 折算为 USD 的派彩额 (USD 分)
		NetAmountUsd     int64     `db:"net_amount_usd"`    // 折算为 USD 的净收益 (USD 分)
		IsDemo           uint64    `db:"is_demo"`           // 0: 真金局, 1: 试玩局
		IsPromo          uint64    `db:"is_promo"`          // 是否为营销局 (如免费转/活动送局): 0-否, 1-是
		SettleStatus     string    `db:"settle_status"`     // 单局生命周期终态: SETTLED (正常结清), CANCELLED (全额撤单退回), HELD_AUDIT (触发看门狗风控挂起)
		StartedAt        time.Time `db:"started_at"`        // 单局抛竿/起步时间
		EndedAt          time.Time `db:"ended_at"`          // 单局派彩结算完毕时间
		DurationMs       uint64    `db:"duration_ms"`       // 从开始到结算内部处理总耗时 (毫秒)
		CreatedAt        time.Time `db:"created_at"`        // 记录入库时间
	}
)

func newGameRoundsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGameRoundsModel {
	return &defaultGameRoundsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`game_rounds`",
	}
}

func (m *defaultGameRoundsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameGameRoundsIdKey := fmt.Sprintf("%s%v", bizFastgameGameRoundsIdPrefix, id)
	fastgameGameRoundsRoundIdKey := fmt.Sprintf("%s%v", bizFastgameGameRoundsRoundIdPrefix, data.RoundId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameGameRoundsIdKey, fastgameGameRoundsRoundIdKey)
	return err
}

func (m *defaultGameRoundsModel) FindOne(ctx context.Context, id uint64) (*GameRounds, error) {
	fastgameGameRoundsIdKey := fmt.Sprintf("%s%v", bizFastgameGameRoundsIdPrefix, id)
	var resp GameRounds
	err := m.QueryRowCtx(ctx, &resp, fastgameGameRoundsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameRoundsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameRoundsModel) FindOneByRoundId(ctx context.Context, roundId string) (*GameRounds, error) {
	fastgameGameRoundsRoundIdKey := fmt.Sprintf("%s%v", bizFastgameGameRoundsRoundIdPrefix, roundId)
	var resp GameRounds
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameGameRoundsRoundIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `round_id` = ? limit 1", gameRoundsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, roundId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameRoundsModel) Insert(ctx context.Context, data *GameRounds) (sql.Result, error) {
	fastgameGameRoundsIdKey := fmt.Sprintf("%s%v", bizFastgameGameRoundsIdPrefix, data.Id)
	fastgameGameRoundsRoundIdKey := fmt.Sprintf("%s%v", bizFastgameGameRoundsRoundIdPrefix, data.RoundId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, gameRoundsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RoundId, data.MerchantId, data.MerchantCode, data.GameId, data.GameCode, data.MathVersion, data.UserId, data.Currency, data.BetAmount, data.WinAmount, data.NetAmount, data.PayoutMultiplier, data.ExchangeRateUsd, data.BetAmountUsd, data.WinAmountUsd, data.NetAmountUsd, data.IsDemo, data.IsPromo, data.SettleStatus, data.StartedAt, data.EndedAt, data.DurationMs)
	}, fastgameGameRoundsIdKey, fastgameGameRoundsRoundIdKey)
	return ret, err
}

func (m *defaultGameRoundsModel) Update(ctx context.Context, newData *GameRounds) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameGameRoundsIdKey := fmt.Sprintf("%s%v", bizFastgameGameRoundsIdPrefix, data.Id)
	fastgameGameRoundsRoundIdKey := fmt.Sprintf("%s%v", bizFastgameGameRoundsRoundIdPrefix, data.RoundId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameRoundsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.RoundId, newData.MerchantId, newData.MerchantCode, newData.GameId, newData.GameCode, newData.MathVersion, newData.UserId, newData.Currency, newData.BetAmount, newData.WinAmount, newData.NetAmount, newData.PayoutMultiplier, newData.ExchangeRateUsd, newData.BetAmountUsd, newData.WinAmountUsd, newData.NetAmountUsd, newData.IsDemo, newData.IsPromo, newData.SettleStatus, newData.StartedAt, newData.EndedAt, newData.DurationMs, newData.Id)
	}, fastgameGameRoundsIdKey, fastgameGameRoundsRoundIdKey)
	return err
}

func (m *defaultGameRoundsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameGameRoundsIdPrefix, primary)
}

func (m *defaultGameRoundsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameRoundsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGameRoundsModel) tableName() string {
	return m.table
}
