// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameSessionsFieldNames          = builder.RawFieldNames(&GameSessions{})
	gameSessionsRows                = strings.Join(gameSessionsFieldNames, ",")
	gameSessionsRowsExpectAutoSet   = strings.Join(stringx.Remove(gameSessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameSessionsRowsWithPlaceHolder = strings.Join(stringx.Remove(gameSessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameGameSessionsIdPrefix        = "biz:fastgame:gameSessions:id:"
	bizFastgameGameSessionsRoundIdPrefix   = "biz:fastgame:gameSessions:roundId:"
	bizFastgameGameSessionsSessionIdPrefix = "biz:fastgame:gameSessions:sessionId:"
)

type (
	gameSessionsModel interface {
		Insert(ctx context.Context, data *GameSessions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*GameSessions, error)
		FindOneByRoundId(ctx context.Context, roundId string) (*GameSessions, error)
		FindOneBySessionId(ctx context.Context, sessionId string) (*GameSessions, error)
		Update(ctx context.Context, data *GameSessions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultGameSessionsModel struct {
		sqlc.CachedConn
		table string
	}

	GameSessions struct {
		Id                   uint64         `db:"id"`                     // 会话主键ID
		SessionId            string         `db:"session_id"`             // 会话全局唯一ID (对应前台一次长局)
		RoundId              string         `db:"round_id"`               // 绑定的全局注单唯一号
		MerchantId           uint64         `db:"merchant_id"`            // 商户ID
		MerchantCode         string         `db:"merchant_code"`          // 商户代号
		GameId               uint64         `db:"game_id"`                // 游戏ID
		GameCode             string         `db:"game_code"`              // 游戏代号
		UserId               string         `db:"user_id"`                // 下游系统玩家唯一代号
		Currency             string         `db:"currency"`               // 货币代号
		BetAmount            int64          `db:"bet_amount"`             // 开局下注扣款本金 (分)
		CurrentStep          uint64         `db:"current_step"`           // 当前已成功完成的步数 (步进深度)
		CurrentMultiplier    float64        `db:"current_multiplier"`     // 当前累积达到的倍率
		AccumulatedPayout    int64          `db:"accumulated_payout"`     // 当前若选择结算可拿走的派彩金额 (分)
		StepHistory          sql.NullString `db:"step_history"`           // 步进历史与状态快照: [{"step":1,"action":"tile_3","outcome":"safe","mult":1.2}]
		EncryptedSecretState string         `db:"encrypted_secret_state"` // 加密存储的底牌/炸弹位置 (防内存透视或提前解密)
		StepVersion          uint64         `db:"step_version"`           // 步进操作版本号 (乐观锁)
		SessionStatus        string         `db:"session_status"`         // 会话状态: IN_PROGRESS (进行中), CASHED_OUT (主动提现), CRASHED (触雷失败), EXPIRED_AUTO_SETTLE (超时系统自动平账)
		ExpireAt             time.Time      `db:"expire_at"`              // 会话最迟过期时间 (到期由 Cron 自动执行保底结算并销毁)
		CreatedAt            time.Time      `db:"created_at"`             // 开局时间
		UpdatedAt            time.Time      `db:"updated_at"`             // 最后操作更新时间
	}
)

func newGameSessionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGameSessionsModel {
	return &defaultGameSessionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`game_sessions`",
	}
}

func (m *defaultGameSessionsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameGameSessionsIdKey := fmt.Sprintf("%s%v", bizFastgameGameSessionsIdPrefix, id)
	fastgameGameSessionsRoundIdKey := fmt.Sprintf("%s%v", bizFastgameGameSessionsRoundIdPrefix, data.RoundId)
	fastgameGameSessionsSessionIdKey := fmt.Sprintf("%s%v", bizFastgameGameSessionsSessionIdPrefix, data.SessionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameGameSessionsIdKey, fastgameGameSessionsRoundIdKey, fastgameGameSessionsSessionIdKey)
	return err
}

func (m *defaultGameSessionsModel) FindOne(ctx context.Context, id uint64) (*GameSessions, error) {
	fastgameGameSessionsIdKey := fmt.Sprintf("%s%v", bizFastgameGameSessionsIdPrefix, id)
	var resp GameSessions
	err := m.QueryRowCtx(ctx, &resp, fastgameGameSessionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameSessionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameSessionsModel) FindOneByRoundId(ctx context.Context, roundId string) (*GameSessions, error) {
	fastgameGameSessionsRoundIdKey := fmt.Sprintf("%s%v", bizFastgameGameSessionsRoundIdPrefix, roundId)
	var resp GameSessions
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameGameSessionsRoundIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `round_id` = ? limit 1", gameSessionsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, roundId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameSessionsModel) FindOneBySessionId(ctx context.Context, sessionId string) (*GameSessions, error) {
	fastgameGameSessionsSessionIdKey := fmt.Sprintf("%s%v", bizFastgameGameSessionsSessionIdPrefix, sessionId)
	var resp GameSessions
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameGameSessionsSessionIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `session_id` = ? limit 1", gameSessionsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, sessionId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameSessionsModel) Insert(ctx context.Context, data *GameSessions) (sql.Result, error) {
	fastgameGameSessionsIdKey := fmt.Sprintf("%s%v", bizFastgameGameSessionsIdPrefix, data.Id)
	fastgameGameSessionsRoundIdKey := fmt.Sprintf("%s%v", bizFastgameGameSessionsRoundIdPrefix, data.RoundId)
	fastgameGameSessionsSessionIdKey := fmt.Sprintf("%s%v", bizFastgameGameSessionsSessionIdPrefix, data.SessionId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, gameSessionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SessionId, data.RoundId, data.MerchantId, data.MerchantCode, data.GameId, data.GameCode, data.UserId, data.Currency, data.BetAmount, data.CurrentStep, data.CurrentMultiplier, data.AccumulatedPayout, data.StepHistory, data.EncryptedSecretState, data.StepVersion, data.SessionStatus, data.ExpireAt)
	}, fastgameGameSessionsIdKey, fastgameGameSessionsRoundIdKey, fastgameGameSessionsSessionIdKey)
	return ret, err
}

func (m *defaultGameSessionsModel) Update(ctx context.Context, newData *GameSessions) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameGameSessionsIdKey := fmt.Sprintf("%s%v", bizFastgameGameSessionsIdPrefix, data.Id)
	fastgameGameSessionsRoundIdKey := fmt.Sprintf("%s%v", bizFastgameGameSessionsRoundIdPrefix, data.RoundId)
	fastgameGameSessionsSessionIdKey := fmt.Sprintf("%s%v", bizFastgameGameSessionsSessionIdPrefix, data.SessionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameSessionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.SessionId, newData.RoundId, newData.MerchantId, newData.MerchantCode, newData.GameId, newData.GameCode, newData.UserId, newData.Currency, newData.BetAmount, newData.CurrentStep, newData.CurrentMultiplier, newData.AccumulatedPayout, newData.StepHistory, newData.EncryptedSecretState, newData.StepVersion, newData.SessionStatus, newData.ExpireAt, newData.Id)
	}, fastgameGameSessionsIdKey, fastgameGameSessionsRoundIdKey, fastgameGameSessionsSessionIdKey)
	return err
}

func (m *defaultGameSessionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameGameSessionsIdPrefix, primary)
}

func (m *defaultGameSessionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameSessionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGameSessionsModel) tableName() string {
	return m.table
}
