// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gamesFieldNames          = builder.RawFieldNames(&Games{})
	gamesRows                = strings.Join(gamesFieldNames, ",")
	gamesRowsExpectAutoSet   = strings.Join(stringx.Remove(gamesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gamesRowsWithPlaceHolder = strings.Join(stringx.Remove(gamesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameGamesIdPrefix       = "biz:fastgame:games:id:"
	bizFastgameGamesGameCodePrefix = "biz:fastgame:games:gameCode:"
)

type (
	gamesModel interface {
		Insert(ctx context.Context, data *Games) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Games, error)
		FindOneByGameCode(ctx context.Context, gameCode string) (*Games, error)
		Update(ctx context.Context, data *Games) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultGamesModel struct {
		sqlc.CachedConn
		table string
	}

	Games struct {
		Id                uint64    `db:"id"`                  // 游戏自增ID
		GameCode          string    `db:"game_code"`           // 游戏全局唯一代号 (如: fishing_deep_sea, gold_miner, slot_zodiac)
		Category          string    `db:"category"`            // 玩法品类: ARCADE (钓鱼/矿工), SLOT (多轴轮盘), MINES (步进扫雷), CASCADE (消除下落)
		Title             string    `db:"title"`               // 多语言游戏显示名称: {"en": "Fishing Tycoon", "zh": "钓鱼大亨"}
		IconUrl           string    `db:"icon_url"`            // 游戏主视觉 Icon 资源路径
		BannerUrl         string    `db:"banner_url"`          // 游戏大厅横幅/海报图路径
		BundlePath        string    `db:"bundle_path"`         // Cocos 资源分包加载相对路径 (Subpackage URL)
		EnginePluginName  string    `db:"engine_plugin_name"`  // Go 核心数学插件注册名 (与代码中的 GamePlugin 映射)
		SupportedRtpTiers string    `db:"supported_rtp_tiers"` // 该机台支持的预设 RTP 挡位数组: [94.00, 96.00, 98.00]
		DefaultRtp        float64   `db:"default_rtp"`         // 系统默认激活的基准 RTP 挡位
		MaxMultiplier     uint64    `db:"max_multiplier"`      // 系统设定的单局硬顶最大倍数 (风控安全防线)
		HasMultiStep      uint64    `db:"has_multi_step"`      // 是否为多阶段步进状态机游戏 (如扫雷): 0-否 (瞬时结算), 1-是 (需要会话暂存)
		DisplayOrder      int64     `db:"display_order"`       // 在大厅中的推荐排序权重 (越大越靠前)
		Status            string    `db:"status"`              // 状态: ONLINE (正常上线), COMING_SOON (敬请期待占位), MAINTENANCE (单游戏维护)
		CreatedAt         time.Time `db:"created_at"`          // 创建时间
		UpdatedAt         time.Time `db:"updated_at"`          // 最后更新时间
	}
)

func newGamesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGamesModel {
	return &defaultGamesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`games`",
	}
}

func (m *defaultGamesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameGamesGameCodeKey := fmt.Sprintf("%s%v", bizFastgameGamesGameCodePrefix, data.GameCode)
	fastgameGamesIdKey := fmt.Sprintf("%s%v", bizFastgameGamesIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameGamesGameCodeKey, fastgameGamesIdKey)
	return err
}

func (m *defaultGamesModel) FindOne(ctx context.Context, id uint64) (*Games, error) {
	fastgameGamesIdKey := fmt.Sprintf("%s%v", bizFastgameGamesIdPrefix, id)
	var resp Games
	err := m.QueryRowCtx(ctx, &resp, fastgameGamesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gamesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGamesModel) FindOneByGameCode(ctx context.Context, gameCode string) (*Games, error) {
	fastgameGamesGameCodeKey := fmt.Sprintf("%s%v", bizFastgameGamesGameCodePrefix, gameCode)
	var resp Games
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameGamesGameCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `game_code` = ? limit 1", gamesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, gameCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGamesModel) Insert(ctx context.Context, data *Games) (sql.Result, error) {
	fastgameGamesGameCodeKey := fmt.Sprintf("%s%v", bizFastgameGamesGameCodePrefix, data.GameCode)
	fastgameGamesIdKey := fmt.Sprintf("%s%v", bizFastgameGamesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, gamesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GameCode, data.Category, data.Title, data.IconUrl, data.BannerUrl, data.BundlePath, data.EnginePluginName, data.SupportedRtpTiers, data.DefaultRtp, data.MaxMultiplier, data.HasMultiStep, data.DisplayOrder, data.Status)
	}, fastgameGamesGameCodeKey, fastgameGamesIdKey)
	return ret, err
}

func (m *defaultGamesModel) Update(ctx context.Context, newData *Games) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameGamesGameCodeKey := fmt.Sprintf("%s%v", bizFastgameGamesGameCodePrefix, data.GameCode)
	fastgameGamesIdKey := fmt.Sprintf("%s%v", bizFastgameGamesIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gamesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.GameCode, newData.Category, newData.Title, newData.IconUrl, newData.BannerUrl, newData.BundlePath, newData.EnginePluginName, newData.SupportedRtpTiers, newData.DefaultRtp, newData.MaxMultiplier, newData.HasMultiStep, newData.DisplayOrder, newData.Status, newData.Id)
	}, fastgameGamesGameCodeKey, fastgameGamesIdKey)
	return err
}

func (m *defaultGamesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameGamesIdPrefix, primary)
}

func (m *defaultGamesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gamesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGamesModel) tableName() string {
	return m.table
}
