// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	i18nReleaseVersionsFieldNames          = builder.RawFieldNames(&I18nReleaseVersions{})
	i18nReleaseVersionsRows                = strings.Join(i18nReleaseVersionsFieldNames, ",")
	i18nReleaseVersionsRowsExpectAutoSet   = strings.Join(stringx.Remove(i18nReleaseVersionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	i18nReleaseVersionsRowsWithPlaceHolder = strings.Join(stringx.Remove(i18nReleaseVersionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameI18nReleaseVersionsIdPrefix = "biz:fastgame:i18nReleaseVersions:id:"
)

type (
	i18nReleaseVersionsModel interface {
		Insert(ctx context.Context, data *I18nReleaseVersions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*I18nReleaseVersions, error)
		Update(ctx context.Context, data *I18nReleaseVersions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultI18nReleaseVersionsModel struct {
		sqlc.CachedConn
		table string
	}

	I18nReleaseVersions struct {
		Id             uint64    `db:"id"`              // 发布流水主键ID
		ReleaseVersion string    `db:"release_version"` // 版本标识代号 (如: v1.0.26_build14 或 MD5前8位)
		MerchantId     uint64    `db:"merchant_id"`     // 所属商户ID (0 表示平台通用基线包，>0 表示商户定制差分包)
		ModuleCode     string    `db:"module_code"`     // 模块代号 (或 ALL 表示全局大包)
		LangCode       string    `db:"lang_code"`       // 语种代码
		ChecksumHash   string    `db:"checksum_hash"`   // 编译生成产物的 SHA256 / MD5 指纹 (供客户端比对校验)
		CdnJsonUrl     string    `db:"cdn_json_url"`    // 编译上传至 CDN/OSS 后的直接静态 JSON 文件下载地址
		EntryCount     uint64    `db:"entry_count"`     // 该包包含的有效词条总数量
		FileSizeBytes  uint64    `db:"file_size_bytes"` // JSON 产物文件大小 (字节)
		IsActive       uint64    `db:"is_active"`       // 是否为当前最新推荐版本: 0-历史旧版本, 1-当前最新生效版
		PublishedBy    string    `db:"published_by"`    // 发布操作人员或系统构建流水线代号
		CreatedAt      time.Time `db:"created_at"`      // 发布上线时间
	}
)

func newI18nReleaseVersionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultI18nReleaseVersionsModel {
	return &defaultI18nReleaseVersionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`i18n_release_versions`",
	}
}

func (m *defaultI18nReleaseVersionsModel) Delete(ctx context.Context, id uint64) error {
	fastgameI18nReleaseVersionsIdKey := fmt.Sprintf("%s%v", bizFastgameI18nReleaseVersionsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameI18nReleaseVersionsIdKey)
	return err
}

func (m *defaultI18nReleaseVersionsModel) FindOne(ctx context.Context, id uint64) (*I18nReleaseVersions, error) {
	fastgameI18nReleaseVersionsIdKey := fmt.Sprintf("%s%v", bizFastgameI18nReleaseVersionsIdPrefix, id)
	var resp I18nReleaseVersions
	err := m.QueryRowCtx(ctx, &resp, fastgameI18nReleaseVersionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", i18nReleaseVersionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultI18nReleaseVersionsModel) Insert(ctx context.Context, data *I18nReleaseVersions) (sql.Result, error) {
	fastgameI18nReleaseVersionsIdKey := fmt.Sprintf("%s%v", bizFastgameI18nReleaseVersionsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, i18nReleaseVersionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ReleaseVersion, data.MerchantId, data.ModuleCode, data.LangCode, data.ChecksumHash, data.CdnJsonUrl, data.EntryCount, data.FileSizeBytes, data.IsActive, data.PublishedBy)
	}, fastgameI18nReleaseVersionsIdKey)
	return ret, err
}

func (m *defaultI18nReleaseVersionsModel) Update(ctx context.Context, data *I18nReleaseVersions) error {
	fastgameI18nReleaseVersionsIdKey := fmt.Sprintf("%s%v", bizFastgameI18nReleaseVersionsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, i18nReleaseVersionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ReleaseVersion, data.MerchantId, data.ModuleCode, data.LangCode, data.ChecksumHash, data.CdnJsonUrl, data.EntryCount, data.FileSizeBytes, data.IsActive, data.PublishedBy, data.Id)
	}, fastgameI18nReleaseVersionsIdKey)
	return err
}

func (m *defaultI18nReleaseVersionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameI18nReleaseVersionsIdPrefix, primary)
}

func (m *defaultI18nReleaseVersionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", i18nReleaseVersionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultI18nReleaseVersionsModel) tableName() string {
	return m.table
}
