// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	i18nMerchantOverridesFieldNames          = builder.RawFieldNames(&I18nMerchantOverrides{})
	i18nMerchantOverridesRows                = strings.Join(i18nMerchantOverridesFieldNames, ",")
	i18nMerchantOverridesRowsExpectAutoSet   = strings.Join(stringx.Remove(i18nMerchantOverridesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	i18nMerchantOverridesRowsWithPlaceHolder = strings.Join(stringx.Remove(i18nMerchantOverridesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameI18nMerchantOverridesIdPrefix                                     = "biz:fastgame:i18nMerchantOverrides:id:"
	bizFastgameI18nMerchantOverridesMerchantIdModuleCodeMessageKeyLangCodePrefix = "biz:fastgame:i18nMerchantOverrides:merchantId:moduleCode:messageKey:langCode:"
)

type (
	i18nMerchantOverridesModel interface {
		Insert(ctx context.Context, data *I18nMerchantOverrides) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*I18nMerchantOverrides, error)
		FindOneByMerchantIdModuleCodeMessageKeyLangCode(ctx context.Context, merchantId uint64, moduleCode string, messageKey string, langCode string) (*I18nMerchantOverrides, error)
		Update(ctx context.Context, data *I18nMerchantOverrides) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultI18nMerchantOverridesModel struct {
		sqlc.CachedConn
		table string
	}

	I18nMerchantOverrides struct {
		Id           uint64    `db:"id"`            // 覆盖规则主键ID
		MerchantId   uint64    `db:"merchant_id"`   // 关联商户ID (merchant_accounts.id)
		MerchantCode string    `db:"merchant_code"` // 商户唯一代号
		ModuleCode   string    `db:"module_code"`   // 模块代号
		MessageKey   string    `db:"message_key"`   // 被重写的目标 Key (必须存在于 i18n_messages)
		LangCode     string    `db:"lang_code"`     // 重写的语种代码
		CustomText   string    `db:"custom_text"`   // 该商户定制展示的特殊文本
		Status       uint64    `db:"status"`        // 是否启用该重写: 0-停用(恢复默认), 1-启用覆盖
		CreatedAt    time.Time `db:"created_at"`    // 配置时间
		UpdatedAt    time.Time `db:"updated_at"`    // 更新时间
	}
)

func newI18nMerchantOverridesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultI18nMerchantOverridesModel {
	return &defaultI18nMerchantOverridesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`i18n_merchant_overrides`",
	}
}

func (m *defaultI18nMerchantOverridesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameI18nMerchantOverridesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nMerchantOverridesIdPrefix, id)
	fastgameI18nMerchantOverridesMerchantIdModuleCodeMessageKeyLangCodeKey := fmt.Sprintf("%s%v:%v:%v:%v", bizFastgameI18nMerchantOverridesMerchantIdModuleCodeMessageKeyLangCodePrefix, data.MerchantId, data.ModuleCode, data.MessageKey, data.LangCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameI18nMerchantOverridesIdKey, fastgameI18nMerchantOverridesMerchantIdModuleCodeMessageKeyLangCodeKey)
	return err
}

func (m *defaultI18nMerchantOverridesModel) FindOne(ctx context.Context, id uint64) (*I18nMerchantOverrides, error) {
	fastgameI18nMerchantOverridesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nMerchantOverridesIdPrefix, id)
	var resp I18nMerchantOverrides
	err := m.QueryRowCtx(ctx, &resp, fastgameI18nMerchantOverridesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", i18nMerchantOverridesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultI18nMerchantOverridesModel) FindOneByMerchantIdModuleCodeMessageKeyLangCode(ctx context.Context, merchantId uint64, moduleCode string, messageKey string, langCode string) (*I18nMerchantOverrides, error) {
	fastgameI18nMerchantOverridesMerchantIdModuleCodeMessageKeyLangCodeKey := fmt.Sprintf("%s%v:%v:%v:%v", bizFastgameI18nMerchantOverridesMerchantIdModuleCodeMessageKeyLangCodePrefix, merchantId, moduleCode, messageKey, langCode)
	var resp I18nMerchantOverrides
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameI18nMerchantOverridesMerchantIdModuleCodeMessageKeyLangCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `merchant_id` = ? and `module_code` = ? and `message_key` = ? and `lang_code` = ? limit 1", i18nMerchantOverridesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, merchantId, moduleCode, messageKey, langCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultI18nMerchantOverridesModel) Insert(ctx context.Context, data *I18nMerchantOverrides) (sql.Result, error) {
	fastgameI18nMerchantOverridesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nMerchantOverridesIdPrefix, data.Id)
	fastgameI18nMerchantOverridesMerchantIdModuleCodeMessageKeyLangCodeKey := fmt.Sprintf("%s%v:%v:%v:%v", bizFastgameI18nMerchantOverridesMerchantIdModuleCodeMessageKeyLangCodePrefix, data.MerchantId, data.ModuleCode, data.MessageKey, data.LangCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, i18nMerchantOverridesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MerchantId, data.MerchantCode, data.ModuleCode, data.MessageKey, data.LangCode, data.CustomText, data.Status)
	}, fastgameI18nMerchantOverridesIdKey, fastgameI18nMerchantOverridesMerchantIdModuleCodeMessageKeyLangCodeKey)
	return ret, err
}

func (m *defaultI18nMerchantOverridesModel) Update(ctx context.Context, newData *I18nMerchantOverrides) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameI18nMerchantOverridesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nMerchantOverridesIdPrefix, data.Id)
	fastgameI18nMerchantOverridesMerchantIdModuleCodeMessageKeyLangCodeKey := fmt.Sprintf("%s%v:%v:%v:%v", bizFastgameI18nMerchantOverridesMerchantIdModuleCodeMessageKeyLangCodePrefix, data.MerchantId, data.ModuleCode, data.MessageKey, data.LangCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, i18nMerchantOverridesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MerchantId, newData.MerchantCode, newData.ModuleCode, newData.MessageKey, newData.LangCode, newData.CustomText, newData.Status, newData.Id)
	}, fastgameI18nMerchantOverridesIdKey, fastgameI18nMerchantOverridesMerchantIdModuleCodeMessageKeyLangCodeKey)
	return err
}

func (m *defaultI18nMerchantOverridesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameI18nMerchantOverridesIdPrefix, primary)
}

func (m *defaultI18nMerchantOverridesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", i18nMerchantOverridesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultI18nMerchantOverridesModel) tableName() string {
	return m.table
}
