// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	i18nLanguagesFieldNames          = builder.RawFieldNames(&I18nLanguages{})
	i18nLanguagesRows                = strings.Join(i18nLanguagesFieldNames, ",")
	i18nLanguagesRowsExpectAutoSet   = strings.Join(stringx.Remove(i18nLanguagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	i18nLanguagesRowsWithPlaceHolder = strings.Join(stringx.Remove(i18nLanguagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameI18nLanguagesIdPrefix       = "biz:fastgame:i18nLanguages:id:"
	bizFastgameI18nLanguagesLangCodePrefix = "biz:fastgame:i18nLanguages:langCode:"
)

type (
	i18nLanguagesModel interface {
		Insert(ctx context.Context, data *I18nLanguages) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*I18nLanguages, error)
		FindOneByLangCode(ctx context.Context, langCode string) (*I18nLanguages, error)
		Update(ctx context.Context, data *I18nLanguages) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultI18nLanguagesModel struct {
		sqlc.CachedConn
		table string
	}

	I18nLanguages struct {
		Id            uint64    `db:"id"`             // 自增主键ID
		LangCode      string    `db:"lang_code"`      // 标准语言标签 (BCP 47 规范，如: en-US, zh-CN, pt-BR, es-419, vi-VN, tl-PH)
		NameLocal     string    `db:"name_local"`     // 该语言的本族语名称 (如: English, 简体中文, Português, Español)
		NameEn        string    `db:"name_en"`        // 该语言的标准英文全称 (如: Brazilian Portuguese)
		TextDirection string    `db:"text_direction"` // 文字书写排版方向: LTR (从左到右), RTL (从右到左，如阿语/希伯来语)
		FallbackLang  string    `db:"fallback_lang"`  // 当某个词条缺失翻译时的自动降级回退语种
		SortOrder     int64     `db:"sort_order"`     // 前端语言切换下拉菜单的展示排序 (越大越靠前)
		Status        uint64    `db:"status"`         // 启用状态: 0-禁用隐藏, 1-正式启用, 2-开发测试中
		CreatedAt     time.Time `db:"created_at"`     // 创建时间
		UpdatedAt     time.Time `db:"updated_at"`     // 更新时间
	}
)

func newI18nLanguagesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultI18nLanguagesModel {
	return &defaultI18nLanguagesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`i18n_languages`",
	}
}

func (m *defaultI18nLanguagesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameI18nLanguagesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nLanguagesIdPrefix, id)
	fastgameI18nLanguagesLangCodeKey := fmt.Sprintf("%s%v", bizFastgameI18nLanguagesLangCodePrefix, data.LangCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameI18nLanguagesIdKey, fastgameI18nLanguagesLangCodeKey)
	return err
}

func (m *defaultI18nLanguagesModel) FindOne(ctx context.Context, id uint64) (*I18nLanguages, error) {
	fastgameI18nLanguagesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nLanguagesIdPrefix, id)
	var resp I18nLanguages
	err := m.QueryRowCtx(ctx, &resp, fastgameI18nLanguagesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", i18nLanguagesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultI18nLanguagesModel) FindOneByLangCode(ctx context.Context, langCode string) (*I18nLanguages, error) {
	fastgameI18nLanguagesLangCodeKey := fmt.Sprintf("%s%v", bizFastgameI18nLanguagesLangCodePrefix, langCode)
	var resp I18nLanguages
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameI18nLanguagesLangCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `lang_code` = ? limit 1", i18nLanguagesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, langCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultI18nLanguagesModel) Insert(ctx context.Context, data *I18nLanguages) (sql.Result, error) {
	fastgameI18nLanguagesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nLanguagesIdPrefix, data.Id)
	fastgameI18nLanguagesLangCodeKey := fmt.Sprintf("%s%v", bizFastgameI18nLanguagesLangCodePrefix, data.LangCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, i18nLanguagesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.LangCode, data.NameLocal, data.NameEn, data.TextDirection, data.FallbackLang, data.SortOrder, data.Status)
	}, fastgameI18nLanguagesIdKey, fastgameI18nLanguagesLangCodeKey)
	return ret, err
}

func (m *defaultI18nLanguagesModel) Update(ctx context.Context, newData *I18nLanguages) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameI18nLanguagesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nLanguagesIdPrefix, data.Id)
	fastgameI18nLanguagesLangCodeKey := fmt.Sprintf("%s%v", bizFastgameI18nLanguagesLangCodePrefix, data.LangCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, i18nLanguagesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.LangCode, newData.NameLocal, newData.NameEn, newData.TextDirection, newData.FallbackLang, newData.SortOrder, newData.Status, newData.Id)
	}, fastgameI18nLanguagesIdKey, fastgameI18nLanguagesLangCodeKey)
	return err
}

func (m *defaultI18nLanguagesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameI18nLanguagesIdPrefix, primary)
}

func (m *defaultI18nLanguagesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", i18nLanguagesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultI18nLanguagesModel) tableName() string {
	return m.table
}
