// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	i18nModulesFieldNames          = builder.RawFieldNames(&I18nModules{})
	i18nModulesRows                = strings.Join(i18nModulesFieldNames, ",")
	i18nModulesRowsExpectAutoSet   = strings.Join(stringx.Remove(i18nModulesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	i18nModulesRowsWithPlaceHolder = strings.Join(stringx.Remove(i18nModulesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameI18nModulesIdPrefix         = "biz:fastgame:i18nModules:id:"
	bizFastgameI18nModulesModuleCodePrefix = "biz:fastgame:i18nModules:moduleCode:"
)

type (
	i18nModulesModel interface {
		Insert(ctx context.Context, data *I18nModules) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*I18nModules, error)
		FindOneByModuleCode(ctx context.Context, moduleCode string) (*I18nModules, error)
		Update(ctx context.Context, data *I18nModules) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultI18nModulesModel struct {
		sqlc.CachedConn
		table string
	}

	I18nModules struct {
		Id           uint64    `db:"id"`            // 模块主键ID
		ModuleCode   string    `db:"module_code"`   // 模块代号: LOBBY_SHELL (大厅外壳), ERRORS (错误码), FISHING (钓鱼机台), MINER (黄金矿工), PROMO (活动系统)
		ModuleName   string    `db:"module_name"`   // 模块业务中文描述
		LoadStrategy string    `db:"load_strategy"` // 加载策略: EAGER (大厅启动必须预载), LAZY (进入该游戏时动态按需加载)
		CreatedAt    time.Time `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time `db:"updated_at"`    // 更新时间
	}
)

func newI18nModulesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultI18nModulesModel {
	return &defaultI18nModulesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`i18n_modules`",
	}
}

func (m *defaultI18nModulesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameI18nModulesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nModulesIdPrefix, id)
	fastgameI18nModulesModuleCodeKey := fmt.Sprintf("%s%v", bizFastgameI18nModulesModuleCodePrefix, data.ModuleCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameI18nModulesIdKey, fastgameI18nModulesModuleCodeKey)
	return err
}

func (m *defaultI18nModulesModel) FindOne(ctx context.Context, id uint64) (*I18nModules, error) {
	fastgameI18nModulesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nModulesIdPrefix, id)
	var resp I18nModules
	err := m.QueryRowCtx(ctx, &resp, fastgameI18nModulesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", i18nModulesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultI18nModulesModel) FindOneByModuleCode(ctx context.Context, moduleCode string) (*I18nModules, error) {
	fastgameI18nModulesModuleCodeKey := fmt.Sprintf("%s%v", bizFastgameI18nModulesModuleCodePrefix, moduleCode)
	var resp I18nModules
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameI18nModulesModuleCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `module_code` = ? limit 1", i18nModulesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, moduleCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultI18nModulesModel) Insert(ctx context.Context, data *I18nModules) (sql.Result, error) {
	fastgameI18nModulesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nModulesIdPrefix, data.Id)
	fastgameI18nModulesModuleCodeKey := fmt.Sprintf("%s%v", bizFastgameI18nModulesModuleCodePrefix, data.ModuleCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, i18nModulesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ModuleCode, data.ModuleName, data.LoadStrategy)
	}, fastgameI18nModulesIdKey, fastgameI18nModulesModuleCodeKey)
	return ret, err
}

func (m *defaultI18nModulesModel) Update(ctx context.Context, newData *I18nModules) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameI18nModulesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nModulesIdPrefix, data.Id)
	fastgameI18nModulesModuleCodeKey := fmt.Sprintf("%s%v", bizFastgameI18nModulesModuleCodePrefix, data.ModuleCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, i18nModulesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ModuleCode, newData.ModuleName, newData.LoadStrategy, newData.Id)
	}, fastgameI18nModulesIdKey, fastgameI18nModulesModuleCodeKey)
	return err
}

func (m *defaultI18nModulesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameI18nModulesIdPrefix, primary)
}

func (m *defaultI18nModulesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", i18nModulesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultI18nModulesModel) tableName() string {
	return m.table
}
