// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	i18nMessagesFieldNames          = builder.RawFieldNames(&I18nMessages{})
	i18nMessagesRows                = strings.Join(i18nMessagesFieldNames, ",")
	i18nMessagesRowsExpectAutoSet   = strings.Join(stringx.Remove(i18nMessagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	i18nMessagesRowsWithPlaceHolder = strings.Join(stringx.Remove(i18nMessagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameI18nMessagesIdPrefix                           = "biz:fastgame:i18nMessages:id:"
	bizFastgameI18nMessagesModuleCodeMessageKeyLangCodePrefix = "biz:fastgame:i18nMessages:moduleCode:messageKey:langCode:"
)

type (
	i18nMessagesModel interface {
		Insert(ctx context.Context, data *I18nMessages) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*I18nMessages, error)
		FindOneByModuleCodeMessageKeyLangCode(ctx context.Context, moduleCode string, messageKey string, langCode string) (*I18nMessages, error)
		Update(ctx context.Context, data *I18nMessages) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultI18nMessagesModel struct {
		sqlc.CachedConn
		table string
	}

	I18nMessages struct {
		Id            uint64    `db:"id"`             // 词条自增主键ID
		ModuleCode    string    `db:"module_code"`    // 所属模块 (关联 i18n_modules.module_code)
		MessageKey    string    `db:"message_key"`    // 程序引用的唯一键名 (如: btn_spin, err_insufficient_balance, fish_tuna_title)
		LangCode      string    `db:"lang_code"`      // 语种代码 (关联 i18n_languages.lang_code)
		MessageText   string    `db:"message_text"`   // 翻译译文内容 (支持动态插值占位符，如: "余额不足，需至少 {min_bet} {currency}")
		ContextRemark string    `db:"context_remark"` // 语境上下文说明 (用于辅助翻译及大模型校对)
		Status        uint64    `db:"status"`         // 状态: 0-待翻译/草稿, 1-已校对生效, 2-已废弃
		CreatedAt     time.Time `db:"created_at"`     // 录入时间
		UpdatedAt     time.Time `db:"updated_at"`     // 更新时间
	}
)

func newI18nMessagesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultI18nMessagesModel {
	return &defaultI18nMessagesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`i18n_messages`",
	}
}

func (m *defaultI18nMessagesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameI18nMessagesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nMessagesIdPrefix, id)
	fastgameI18nMessagesModuleCodeMessageKeyLangCodeKey := fmt.Sprintf("%s%v:%v:%v", bizFastgameI18nMessagesModuleCodeMessageKeyLangCodePrefix, data.ModuleCode, data.MessageKey, data.LangCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameI18nMessagesIdKey, fastgameI18nMessagesModuleCodeMessageKeyLangCodeKey)
	return err
}

func (m *defaultI18nMessagesModel) FindOne(ctx context.Context, id uint64) (*I18nMessages, error) {
	fastgameI18nMessagesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nMessagesIdPrefix, id)
	var resp I18nMessages
	err := m.QueryRowCtx(ctx, &resp, fastgameI18nMessagesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", i18nMessagesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultI18nMessagesModel) FindOneByModuleCodeMessageKeyLangCode(ctx context.Context, moduleCode string, messageKey string, langCode string) (*I18nMessages, error) {
	fastgameI18nMessagesModuleCodeMessageKeyLangCodeKey := fmt.Sprintf("%s%v:%v:%v", bizFastgameI18nMessagesModuleCodeMessageKeyLangCodePrefix, moduleCode, messageKey, langCode)
	var resp I18nMessages
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameI18nMessagesModuleCodeMessageKeyLangCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `module_code` = ? and `message_key` = ? and `lang_code` = ? limit 1", i18nMessagesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, moduleCode, messageKey, langCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultI18nMessagesModel) Insert(ctx context.Context, data *I18nMessages) (sql.Result, error) {
	fastgameI18nMessagesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nMessagesIdPrefix, data.Id)
	fastgameI18nMessagesModuleCodeMessageKeyLangCodeKey := fmt.Sprintf("%s%v:%v:%v", bizFastgameI18nMessagesModuleCodeMessageKeyLangCodePrefix, data.ModuleCode, data.MessageKey, data.LangCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, i18nMessagesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ModuleCode, data.MessageKey, data.LangCode, data.MessageText, data.ContextRemark, data.Status)
	}, fastgameI18nMessagesIdKey, fastgameI18nMessagesModuleCodeMessageKeyLangCodeKey)
	return ret, err
}

func (m *defaultI18nMessagesModel) Update(ctx context.Context, newData *I18nMessages) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameI18nMessagesIdKey := fmt.Sprintf("%s%v", bizFastgameI18nMessagesIdPrefix, data.Id)
	fastgameI18nMessagesModuleCodeMessageKeyLangCodeKey := fmt.Sprintf("%s%v:%v:%v", bizFastgameI18nMessagesModuleCodeMessageKeyLangCodePrefix, data.ModuleCode, data.MessageKey, data.LangCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, i18nMessagesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ModuleCode, newData.MessageKey, newData.LangCode, newData.MessageText, newData.ContextRemark, newData.Status, newData.Id)
	}, fastgameI18nMessagesIdKey, fastgameI18nMessagesModuleCodeMessageKeyLangCodeKey)
	return err
}

func (m *defaultI18nMessagesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameI18nMessagesIdPrefix, primary)
}

func (m *defaultI18nMessagesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", i18nMessagesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultI18nMessagesModel) tableName() string {
	return m.table
}
