// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantCredentialsFieldNames          = builder.RawFieldNames(&MerchantCredentials{})
	merchantCredentialsRows                = strings.Join(merchantCredentialsFieldNames, ",")
	merchantCredentialsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantCredentialsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantCredentialsRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantCredentialsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameMerchantCredentialsIdPrefix     = "biz:fastgame:merchantCredentials:id:"
	bizFastgameMerchantCredentialsApiKeyPrefix = "biz:fastgame:merchantCredentials:apiKey:"
)

type (
	merchantCredentialsModel interface {
		Insert(ctx context.Context, data *MerchantCredentials) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MerchantCredentials, error)
		FindOneByApiKey(ctx context.Context, apiKey string) (*MerchantCredentials, error)
		Update(ctx context.Context, data *MerchantCredentials) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMerchantCredentialsModel struct {
		sqlc.CachedConn
		table string
	}

	MerchantCredentials struct {
		Id           uint64         `db:"id"`            // 主键ID
		MerchantId   uint64         `db:"merchant_id"`   // 关联商户ID (merchant_accounts.id)
		MerchantCode string         `db:"merchant_code"` // 商户代号冗余
		Environment  string         `db:"environment"`   // 环境分类: PRODUCTION (生产), STAGING (预发布), SANDBOX (沙盒测试)
		KeyType      string         `db:"key_type"`      // 鉴权算法: HMAC_SHA256, RSA2048, ED25519
		ApiKey       string         `db:"api_key"`       // 对外公开的 Access Key ID / Client ID
		SecretKey    string         `db:"secret_key"`    // 对称加密密钥 / 签名用 Secret Key
		PublicKey    sql.NullString `db:"public_key"`    // 非对称加密之商户公钥 (RSA验签使用)
		PrivateKey   sql.NullString `db:"private_key"`   // 非对称加密之我方私钥 (密文存储或KMS引用)
		Version      uint64         `db:"version"`       // 密钥版本号 (用于不停机热轮换换密)
		Status       uint64         `db:"status"`        // 凭证状态: 0-已失效, 1-生效中, 2-即将废除(过渡期双活)
		ExpiredAt    sql.NullTime   `db:"expired_at"`    // 凭证强制失效时间 (NULL为永久有效)
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time      `db:"updated_at"`    // 最后更新时间
	}
)

func newMerchantCredentialsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantCredentialsModel {
	return &defaultMerchantCredentialsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchant_credentials`",
	}
}

func (m *defaultMerchantCredentialsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameMerchantCredentialsApiKeyKey := fmt.Sprintf("%s%v", bizFastgameMerchantCredentialsApiKeyPrefix, data.ApiKey)
	fastgameMerchantCredentialsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantCredentialsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameMerchantCredentialsApiKeyKey, fastgameMerchantCredentialsIdKey)
	return err
}

func (m *defaultMerchantCredentialsModel) FindOne(ctx context.Context, id uint64) (*MerchantCredentials, error) {
	fastgameMerchantCredentialsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantCredentialsIdPrefix, id)
	var resp MerchantCredentials
	err := m.QueryRowCtx(ctx, &resp, fastgameMerchantCredentialsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantCredentialsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantCredentialsModel) FindOneByApiKey(ctx context.Context, apiKey string) (*MerchantCredentials, error) {
	fastgameMerchantCredentialsApiKeyKey := fmt.Sprintf("%s%v", bizFastgameMerchantCredentialsApiKeyPrefix, apiKey)
	var resp MerchantCredentials
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameMerchantCredentialsApiKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `api_key` = ? limit 1", merchantCredentialsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, apiKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantCredentialsModel) Insert(ctx context.Context, data *MerchantCredentials) (sql.Result, error) {
	fastgameMerchantCredentialsApiKeyKey := fmt.Sprintf("%s%v", bizFastgameMerchantCredentialsApiKeyPrefix, data.ApiKey)
	fastgameMerchantCredentialsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantCredentialsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantCredentialsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MerchantId, data.MerchantCode, data.Environment, data.KeyType, data.ApiKey, data.SecretKey, data.PublicKey, data.PrivateKey, data.Version, data.Status, data.ExpiredAt)
	}, fastgameMerchantCredentialsApiKeyKey, fastgameMerchantCredentialsIdKey)
	return ret, err
}

func (m *defaultMerchantCredentialsModel) Update(ctx context.Context, newData *MerchantCredentials) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameMerchantCredentialsApiKeyKey := fmt.Sprintf("%s%v", bizFastgameMerchantCredentialsApiKeyPrefix, data.ApiKey)
	fastgameMerchantCredentialsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantCredentialsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantCredentialsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MerchantId, newData.MerchantCode, newData.Environment, newData.KeyType, newData.ApiKey, newData.SecretKey, newData.PublicKey, newData.PrivateKey, newData.Version, newData.Status, newData.ExpiredAt, newData.Id)
	}, fastgameMerchantCredentialsApiKeyKey, fastgameMerchantCredentialsIdKey)
	return err
}

func (m *defaultMerchantCredentialsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameMerchantCredentialsIdPrefix, primary)
}

func (m *defaultMerchantCredentialsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantCredentialsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantCredentialsModel) tableName() string {
	return m.table
}
