// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantUsersFieldNames          = builder.RawFieldNames(&MerchantUsers{})
	merchantUsersRows                = strings.Join(merchantUsersFieldNames, ",")
	merchantUsersRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantUsersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantUsersRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantUsersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameMerchantUsersIdPrefix                 = "biz:fastgame:merchantUsers:id:"
	bizFastgameMerchantUsersMerchantIdUsernamePrefix = "biz:fastgame:merchantUsers:merchantId:username:"
)

type (
	merchantUsersModel interface {
		Insert(ctx context.Context, data *MerchantUsers) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MerchantUsers, error)
		FindOneByMerchantIdUsername(ctx context.Context, merchantId uint64, username string) (*MerchantUsers, error)
		Update(ctx context.Context, data *MerchantUsers) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMerchantUsersModel struct {
		sqlc.CachedConn
		table string
	}

	MerchantUsers struct {
		Id            uint64         `db:"id"`              // 后台用户ID
		MerchantId    uint64         `db:"merchant_id"`     // 归属商户ID (merchant_accounts.id)
		Username      string         `db:"username"`        // 登录账号用户名
		PasswordHash  string         `db:"password_hash"`   // 密码哈希值 (Argon2id 或 Bcrypt 加密)
		Salt          string         `db:"salt"`            // 密码混淆盐值
		RealName      string         `db:"real_name"`       // 使用者真实姓名/代号
		Role          string         `db:"role"`            // 权限角色: ADMIN (商户超管), DEVELOPER (技术对接), FINANCE (财务核账), VIEWER (只读观察员)
		TotpSecret    sql.NullString `db:"totp_secret"`     // 谷歌双因子认证 (2FA / TOTP) 密钥密文
		Is2FaEnabled  uint64         `db:"is_2fa_enabled"`  // 是否强制开启 2FA: 0-未开启, 1-已开启
		LastLoginIp   string         `db:"last_login_ip"`   // 最后一次成功登录的 IP 地址
		LastLoginTime sql.NullTime   `db:"last_login_time"` // 最后一次成功登录时间
		Status        uint64         `db:"status"`          // 用户状态: 0-冻结停用, 1-正常有效
		CreatedAt     time.Time      `db:"created_at"`      // 创建时间
		UpdatedAt     time.Time      `db:"updated_at"`      // 最后更新时间
	}
)

func newMerchantUsersModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantUsersModel {
	return &defaultMerchantUsersModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchant_users`",
	}
}

func (m *defaultMerchantUsersModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameMerchantUsersIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantUsersIdPrefix, id)
	fastgameMerchantUsersMerchantIdUsernameKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantUsersMerchantIdUsernamePrefix, data.MerchantId, data.Username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameMerchantUsersIdKey, fastgameMerchantUsersMerchantIdUsernameKey)
	return err
}

func (m *defaultMerchantUsersModel) FindOne(ctx context.Context, id uint64) (*MerchantUsers, error) {
	fastgameMerchantUsersIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantUsersIdPrefix, id)
	var resp MerchantUsers
	err := m.QueryRowCtx(ctx, &resp, fastgameMerchantUsersIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantUsersRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantUsersModel) FindOneByMerchantIdUsername(ctx context.Context, merchantId uint64, username string) (*MerchantUsers, error) {
	fastgameMerchantUsersMerchantIdUsernameKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantUsersMerchantIdUsernamePrefix, merchantId, username)
	var resp MerchantUsers
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameMerchantUsersMerchantIdUsernameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `merchant_id` = ? and `username` = ? limit 1", merchantUsersRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, merchantId, username); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantUsersModel) Insert(ctx context.Context, data *MerchantUsers) (sql.Result, error) {
	fastgameMerchantUsersIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantUsersIdPrefix, data.Id)
	fastgameMerchantUsersMerchantIdUsernameKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantUsersMerchantIdUsernamePrefix, data.MerchantId, data.Username)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantUsersRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MerchantId, data.Username, data.PasswordHash, data.Salt, data.RealName, data.Role, data.TotpSecret, data.Is2FaEnabled, data.LastLoginIp, data.LastLoginTime, data.Status)
	}, fastgameMerchantUsersIdKey, fastgameMerchantUsersMerchantIdUsernameKey)
	return ret, err
}

func (m *defaultMerchantUsersModel) Update(ctx context.Context, newData *MerchantUsers) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameMerchantUsersIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantUsersIdPrefix, data.Id)
	fastgameMerchantUsersMerchantIdUsernameKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantUsersMerchantIdUsernamePrefix, data.MerchantId, data.Username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantUsersRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MerchantId, newData.Username, newData.PasswordHash, newData.Salt, newData.RealName, newData.Role, newData.TotpSecret, newData.Is2FaEnabled, newData.LastLoginIp, newData.LastLoginTime, newData.Status, newData.Id)
	}, fastgameMerchantUsersIdKey, fastgameMerchantUsersMerchantIdUsernameKey)
	return err
}

func (m *defaultMerchantUsersModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameMerchantUsersIdPrefix, primary)
}

func (m *defaultMerchantUsersModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantUsersRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantUsersModel) tableName() string {
	return m.table
}
