// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantAuditLogsFieldNames          = builder.RawFieldNames(&MerchantAuditLogs{})
	merchantAuditLogsRows                = strings.Join(merchantAuditLogsFieldNames, ",")
	merchantAuditLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantAuditLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantAuditLogsRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantAuditLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameMerchantAuditLogsIdPrefix = "biz:fastgame:merchantAuditLogs:id:"
)

type (
	merchantAuditLogsModel interface {
		Insert(ctx context.Context, data *MerchantAuditLogs) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MerchantAuditLogs, error)
		Update(ctx context.Context, data *MerchantAuditLogs) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMerchantAuditLogsModel struct {
		sqlc.CachedConn
		table string
	}

	MerchantAuditLogs struct {
		Id             uint64         `db:"id"`               // 审计自增主键ID
		MerchantId     uint64         `db:"merchant_id"`      // 归属商户ID
		OperatorType   string         `db:"operator_type"`    // 操作人身份类型: PLATFORM_ADMIN (我方平台运维), MERCHANT_USER (商户自主管理人员), SYSTEM_CRON (系统定时任务)
		OperatorId     uint64         `db:"operator_id"`      // 操作人员用户主键ID (0表示系统触发)
		OperatorName   string         `db:"operator_name"`    // 操作人账号快照
		ActionModule   string         `db:"action_module"`    // 变更模块: CREDENTIALS (换密), NETWORK (白名单变更), RISK (风控修改), WALLET (路由调整)
		ActionType     string         `db:"action_type"`      // 操作动作: CREATE, UPDATE, DELETE, ROTATE_KEY, TOGGLE_STATUS
		TargetTable    string         `db:"target_table"`     // 受影响的目标数据物理表名
		TargetRecordId uint64         `db:"target_record_id"` // 受影响的目标记录主键ID
		BeforePayload  sql.NullString `db:"before_payload"`   // 修改前数据原始快照 (JSON 序列化存储)
		AfterPayload   sql.NullString `db:"after_payload"`    // 修改后数据最新快照 (JSON 序列化存储)
		RequestIp      string         `db:"request_ip"`       // 发起操作的客户端真实 IP
		UserAgent      string         `db:"user_agent"`       // 发起操作的客户端浏览器/终端 UA
		Remark         string         `db:"remark"`           // 修改原因或工单编号备注
		CreatedAt      time.Time      `db:"created_at"`       // 审计日志产生时间
	}
)

func newMerchantAuditLogsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantAuditLogsModel {
	return &defaultMerchantAuditLogsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchant_audit_logs`",
	}
}

func (m *defaultMerchantAuditLogsModel) Delete(ctx context.Context, id uint64) error {
	fastgameMerchantAuditLogsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantAuditLogsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameMerchantAuditLogsIdKey)
	return err
}

func (m *defaultMerchantAuditLogsModel) FindOne(ctx context.Context, id uint64) (*MerchantAuditLogs, error) {
	fastgameMerchantAuditLogsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantAuditLogsIdPrefix, id)
	var resp MerchantAuditLogs
	err := m.QueryRowCtx(ctx, &resp, fastgameMerchantAuditLogsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantAuditLogsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantAuditLogsModel) Insert(ctx context.Context, data *MerchantAuditLogs) (sql.Result, error) {
	fastgameMerchantAuditLogsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantAuditLogsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantAuditLogsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MerchantId, data.OperatorType, data.OperatorId, data.OperatorName, data.ActionModule, data.ActionType, data.TargetTable, data.TargetRecordId, data.BeforePayload, data.AfterPayload, data.RequestIp, data.UserAgent, data.Remark)
	}, fastgameMerchantAuditLogsIdKey)
	return ret, err
}

func (m *defaultMerchantAuditLogsModel) Update(ctx context.Context, data *MerchantAuditLogs) error {
	fastgameMerchantAuditLogsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantAuditLogsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantAuditLogsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.MerchantId, data.OperatorType, data.OperatorId, data.OperatorName, data.ActionModule, data.ActionType, data.TargetTable, data.TargetRecordId, data.BeforePayload, data.AfterPayload, data.RequestIp, data.UserAgent, data.Remark, data.Id)
	}, fastgameMerchantAuditLogsIdKey)
	return err
}

func (m *defaultMerchantAuditLogsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameMerchantAuditLogsIdPrefix, primary)
}

func (m *defaultMerchantAuditLogsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantAuditLogsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantAuditLogsModel) tableName() string {
	return m.table
}
