// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantGamesFieldNames          = builder.RawFieldNames(&MerchantGames{})
	merchantGamesRows                = strings.Join(merchantGamesFieldNames, ",")
	merchantGamesRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantGamesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantGamesRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantGamesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameMerchantGamesIdPrefix               = "biz:fastgame:merchantGames:id:"
	bizFastgameMerchantGamesMerchantIdGameIdPrefix = "biz:fastgame:merchantGames:merchantId:gameId:"
)

type (
	merchantGamesModel interface {
		Insert(ctx context.Context, data *MerchantGames) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MerchantGames, error)
		FindOneByMerchantIdGameId(ctx context.Context, merchantId uint64, gameId uint64) (*MerchantGames, error)
		Update(ctx context.Context, data *MerchantGames) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMerchantGamesModel struct {
		sqlc.CachedConn
		table string
	}

	MerchantGames struct {
		Id               uint64    `db:"id"`                 // 主键ID
		MerchantId       uint64    `db:"merchant_id"`        // 关联商户ID (merchant_accounts.id)
		MerchantCode     string    `db:"merchant_code"`      // 商户代号冗余
		GameId           uint64    `db:"game_id"`            // 关联游戏ID (games.id)
		GameCode         string    `db:"game_code"`          // 游戏代号冗余
		ActiveRtp        float64   `db:"active_rtp"`         // 为该商户启用的当前实际 RTP 挡位
		MinBet           int64     `db:"min_bet"`            // 该商户下此游戏的单注底注 (分，10 = $0.10)
		MaxBet           int64     `db:"max_bet"`            // 该商户下此游戏的单注顶注 (分，50000 = $500.00)
		MaxMultiplierCap uint64    `db:"max_multiplier_cap"` // 商户定制的单局最大倍数硬顶上限
		Status           uint64    `db:"status"`             // 授权状态: 0-停用下架, 1-正常开放, 2-商户专属维护
		CreatedAt        time.Time `db:"created_at"`         // 创建时间
		UpdatedAt        time.Time `db:"updated_at"`         // 最后更新时间
	}
)

func newMerchantGamesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantGamesModel {
	return &defaultMerchantGamesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchant_games`",
	}
}

func (m *defaultMerchantGamesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameMerchantGamesIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantGamesIdPrefix, id)
	fastgameMerchantGamesMerchantIdGameIdKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantGamesMerchantIdGameIdPrefix, data.MerchantId, data.GameId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameMerchantGamesIdKey, fastgameMerchantGamesMerchantIdGameIdKey)
	return err
}

func (m *defaultMerchantGamesModel) FindOne(ctx context.Context, id uint64) (*MerchantGames, error) {
	fastgameMerchantGamesIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantGamesIdPrefix, id)
	var resp MerchantGames
	err := m.QueryRowCtx(ctx, &resp, fastgameMerchantGamesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantGamesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantGamesModel) FindOneByMerchantIdGameId(ctx context.Context, merchantId uint64, gameId uint64) (*MerchantGames, error) {
	fastgameMerchantGamesMerchantIdGameIdKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantGamesMerchantIdGameIdPrefix, merchantId, gameId)
	var resp MerchantGames
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameMerchantGamesMerchantIdGameIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `merchant_id` = ? and `game_id` = ? limit 1", merchantGamesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, merchantId, gameId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantGamesModel) Insert(ctx context.Context, data *MerchantGames) (sql.Result, error) {
	fastgameMerchantGamesIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantGamesIdPrefix, data.Id)
	fastgameMerchantGamesMerchantIdGameIdKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantGamesMerchantIdGameIdPrefix, data.MerchantId, data.GameId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantGamesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MerchantId, data.MerchantCode, data.GameId, data.GameCode, data.ActiveRtp, data.MinBet, data.MaxBet, data.MaxMultiplierCap, data.Status)
	}, fastgameMerchantGamesIdKey, fastgameMerchantGamesMerchantIdGameIdKey)
	return ret, err
}

func (m *defaultMerchantGamesModel) Update(ctx context.Context, newData *MerchantGames) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameMerchantGamesIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantGamesIdPrefix, data.Id)
	fastgameMerchantGamesMerchantIdGameIdKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantGamesMerchantIdGameIdPrefix, data.MerchantId, data.GameId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantGamesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MerchantId, newData.MerchantCode, newData.GameId, newData.GameCode, newData.ActiveRtp, newData.MinBet, newData.MaxBet, newData.MaxMultiplierCap, newData.Status, newData.Id)
	}, fastgameMerchantGamesIdKey, fastgameMerchantGamesMerchantIdGameIdKey)
	return err
}

func (m *defaultMerchantGamesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameMerchantGamesIdPrefix, primary)
}

func (m *defaultMerchantGamesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantGamesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantGamesModel) tableName() string {
	return m.table
}
