// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantPromoConfigsFieldNames          = builder.RawFieldNames(&MerchantPromoConfigs{})
	merchantPromoConfigsRows                = strings.Join(merchantPromoConfigsFieldNames, ",")
	merchantPromoConfigsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantPromoConfigsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantPromoConfigsRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantPromoConfigsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameMerchantPromoConfigsIdPrefix         = "biz:fastgame:merchantPromoConfigs:id:"
	bizFastgameMerchantPromoConfigsMerchantIdPrefix = "biz:fastgame:merchantPromoConfigs:merchantId:"
)

type (
	merchantPromoConfigsModel interface {
		Insert(ctx context.Context, data *MerchantPromoConfigs) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MerchantPromoConfigs, error)
		FindOneByMerchantId(ctx context.Context, merchantId uint64) (*MerchantPromoConfigs, error)
		Update(ctx context.Context, data *MerchantPromoConfigs) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMerchantPromoConfigsModel struct {
		sqlc.CachedConn
		table string
	}

	MerchantPromoConfigs struct {
		Id                 uint64    `db:"id"`                   // 主键ID
		MerchantId         uint64    `db:"merchant_id"`          // 关联商户ID (merchant_accounts.id)
		PromoSuiteEnabled  uint64    `db:"promo_suite_enabled"`  // 是否启用技术方促活营销套件: 0-关闭, 1-开启
		AllowTournaments   uint64    `db:"allow_tournaments"`    // 是否允许参与锦标排行榜活动: 0-否, 1-是
		AllowMissions      uint64    `db:"allow_missions"`       // 是否允许局数/打卡任务系统: 0-否, 1-是
		AllowDropRewards   uint64    `db:"allow_drop_rewards"`   // 是否允许深海随机掉宝/彩蛋空投: 0-否, 1-是
		MonthlyBudgetCap   float64   `db:"monthly_budget_cap"`   // 月度营销活动赞助/补贴预算上限 (USD，0表示不设限)
		CurrentMonthSpent  float64   `db:"current_month_spent"`  // 本月系统已实际派发的活动奖励累计总成本 (USD)
		RewardTargetWallet string    `db:"reward_target_wallet"` // 活动奖励派发落入的目标账户: BONUS (下游红利钱包), REAL (下游真实可提现主钱包)
		Status             uint64    `db:"status"`               // 配置状态: 0-停用, 1-启用
		CreatedAt          time.Time `db:"created_at"`           // 创建时间
		UpdatedAt          time.Time `db:"updated_at"`           // 最后更新时间
	}
)

func newMerchantPromoConfigsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantPromoConfigsModel {
	return &defaultMerchantPromoConfigsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchant_promo_configs`",
	}
}

func (m *defaultMerchantPromoConfigsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameMerchantPromoConfigsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantPromoConfigsIdPrefix, id)
	fastgameMerchantPromoConfigsMerchantIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantPromoConfigsMerchantIdPrefix, data.MerchantId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameMerchantPromoConfigsIdKey, fastgameMerchantPromoConfigsMerchantIdKey)
	return err
}

func (m *defaultMerchantPromoConfigsModel) FindOne(ctx context.Context, id uint64) (*MerchantPromoConfigs, error) {
	fastgameMerchantPromoConfigsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantPromoConfigsIdPrefix, id)
	var resp MerchantPromoConfigs
	err := m.QueryRowCtx(ctx, &resp, fastgameMerchantPromoConfigsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantPromoConfigsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantPromoConfigsModel) FindOneByMerchantId(ctx context.Context, merchantId uint64) (*MerchantPromoConfigs, error) {
	fastgameMerchantPromoConfigsMerchantIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantPromoConfigsMerchantIdPrefix, merchantId)
	var resp MerchantPromoConfigs
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameMerchantPromoConfigsMerchantIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `merchant_id` = ? limit 1", merchantPromoConfigsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, merchantId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantPromoConfigsModel) Insert(ctx context.Context, data *MerchantPromoConfigs) (sql.Result, error) {
	fastgameMerchantPromoConfigsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantPromoConfigsIdPrefix, data.Id)
	fastgameMerchantPromoConfigsMerchantIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantPromoConfigsMerchantIdPrefix, data.MerchantId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantPromoConfigsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MerchantId, data.PromoSuiteEnabled, data.AllowTournaments, data.AllowMissions, data.AllowDropRewards, data.MonthlyBudgetCap, data.CurrentMonthSpent, data.RewardTargetWallet, data.Status)
	}, fastgameMerchantPromoConfigsIdKey, fastgameMerchantPromoConfigsMerchantIdKey)
	return ret, err
}

func (m *defaultMerchantPromoConfigsModel) Update(ctx context.Context, newData *MerchantPromoConfigs) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameMerchantPromoConfigsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantPromoConfigsIdPrefix, data.Id)
	fastgameMerchantPromoConfigsMerchantIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantPromoConfigsMerchantIdPrefix, data.MerchantId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantPromoConfigsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MerchantId, newData.PromoSuiteEnabled, newData.AllowTournaments, newData.AllowMissions, newData.AllowDropRewards, newData.MonthlyBudgetCap, newData.CurrentMonthSpent, newData.RewardTargetWallet, newData.Status, newData.Id)
	}, fastgameMerchantPromoConfigsIdKey, fastgameMerchantPromoConfigsMerchantIdKey)
	return err
}

func (m *defaultMerchantPromoConfigsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameMerchantPromoConfigsIdPrefix, primary)
}

func (m *defaultMerchantPromoConfigsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantPromoConfigsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantPromoConfigsModel) tableName() string {
	return m.table
}
