// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantReconciliationDiffsFieldNames          = builder.RawFieldNames(&MerchantReconciliationDiffs{})
	merchantReconciliationDiffsRows                = strings.Join(merchantReconciliationDiffsFieldNames, ",")
	merchantReconciliationDiffsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantReconciliationDiffsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantReconciliationDiffsRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantReconciliationDiffsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameMerchantReconciliationDiffsIdPrefix              = "biz:fastgame:merchantReconciliationDiffs:id:"
	bizFastgameMerchantReconciliationDiffsPeriodIdRoundIdPrefix = "biz:fastgame:merchantReconciliationDiffs:periodId:roundId:"
)

type (
	merchantReconciliationDiffsModel interface {
		Insert(ctx context.Context, data *MerchantReconciliationDiffs) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MerchantReconciliationDiffs, error)
		FindOneByPeriodIdRoundId(ctx context.Context, periodId uint64, roundId string) (*MerchantReconciliationDiffs, error)
		Update(ctx context.Context, data *MerchantReconciliationDiffs) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMerchantReconciliationDiffsModel struct {
		sqlc.CachedConn
		table string
	}

	MerchantReconciliationDiffs struct {
		Id               uint64       `db:"id"`                // 差异主键ID
		PeriodId         uint64       `db:"period_id"`         // 关联周期账单ID (merchant_financial_periods.id)
		MerchantId       uint64       `db:"merchant_id"`       // 关联商户ID
		RoundId          string       `db:"round_id"`          // 引发争议的单局流水号
		DiffType         string       `db:"diff_type"`         // 差异类型: MISSING_IN_UPSTREAM (下游有但我方无), MISSING_IN_DOWNSTREAM (我方有但下游无), AMOUNT_MISMATCH (双方金额不符)
		OurBet           int64        `db:"our_bet"`           // 我方记录的投注额 (分)
		OurWin           int64        `db:"our_win"`           // 我方记录的派彩额 (分)
		TheirBet         int64        `db:"their_bet"`         // 下游上报对账单中的投注额 (分)
		TheirWin         int64        `db:"their_win"`         // 下游上报对账单中的派彩额 (分)
		DiffAmount       int64        `db:"diff_amount"`       // 绝对净差异金额 (分)
		ResolutionStatus string       `db:"resolution_status"` // 解决处理状态: PENDING (待核查), AUTO_RESOLVED (自动对账修补), MANUAL_ADJUSTED (人工确认调整), IGNORED (忽略小额尾差)
		ResolutionRemark string       `db:"resolution_remark"` // 财务/技术人员平账备注说明
		ResolvedAt       sql.NullTime `db:"resolved_at"`       // 平账了结时间戳
		CreatedAt        time.Time    `db:"created_at"`        // 发现差异并入库时间
		UpdatedAt        time.Time    `db:"updated_at"`        // 最后更新时间
	}
)

func newMerchantReconciliationDiffsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantReconciliationDiffsModel {
	return &defaultMerchantReconciliationDiffsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchant_reconciliation_diffs`",
	}
}

func (m *defaultMerchantReconciliationDiffsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameMerchantReconciliationDiffsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantReconciliationDiffsIdPrefix, id)
	fastgameMerchantReconciliationDiffsPeriodIdRoundIdKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantReconciliationDiffsPeriodIdRoundIdPrefix, data.PeriodId, data.RoundId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameMerchantReconciliationDiffsIdKey, fastgameMerchantReconciliationDiffsPeriodIdRoundIdKey)
	return err
}

func (m *defaultMerchantReconciliationDiffsModel) FindOne(ctx context.Context, id uint64) (*MerchantReconciliationDiffs, error) {
	fastgameMerchantReconciliationDiffsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantReconciliationDiffsIdPrefix, id)
	var resp MerchantReconciliationDiffs
	err := m.QueryRowCtx(ctx, &resp, fastgameMerchantReconciliationDiffsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantReconciliationDiffsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantReconciliationDiffsModel) FindOneByPeriodIdRoundId(ctx context.Context, periodId uint64, roundId string) (*MerchantReconciliationDiffs, error) {
	fastgameMerchantReconciliationDiffsPeriodIdRoundIdKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantReconciliationDiffsPeriodIdRoundIdPrefix, periodId, roundId)
	var resp MerchantReconciliationDiffs
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameMerchantReconciliationDiffsPeriodIdRoundIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `period_id` = ? and `round_id` = ? limit 1", merchantReconciliationDiffsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, periodId, roundId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantReconciliationDiffsModel) Insert(ctx context.Context, data *MerchantReconciliationDiffs) (sql.Result, error) {
	fastgameMerchantReconciliationDiffsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantReconciliationDiffsIdPrefix, data.Id)
	fastgameMerchantReconciliationDiffsPeriodIdRoundIdKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantReconciliationDiffsPeriodIdRoundIdPrefix, data.PeriodId, data.RoundId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantReconciliationDiffsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PeriodId, data.MerchantId, data.RoundId, data.DiffType, data.OurBet, data.OurWin, data.TheirBet, data.TheirWin, data.DiffAmount, data.ResolutionStatus, data.ResolutionRemark, data.ResolvedAt)
	}, fastgameMerchantReconciliationDiffsIdKey, fastgameMerchantReconciliationDiffsPeriodIdRoundIdKey)
	return ret, err
}

func (m *defaultMerchantReconciliationDiffsModel) Update(ctx context.Context, newData *MerchantReconciliationDiffs) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameMerchantReconciliationDiffsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantReconciliationDiffsIdPrefix, data.Id)
	fastgameMerchantReconciliationDiffsPeriodIdRoundIdKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantReconciliationDiffsPeriodIdRoundIdPrefix, data.PeriodId, data.RoundId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantReconciliationDiffsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.PeriodId, newData.MerchantId, newData.RoundId, newData.DiffType, newData.OurBet, newData.OurWin, newData.TheirBet, newData.TheirWin, newData.DiffAmount, newData.ResolutionStatus, newData.ResolutionRemark, newData.ResolvedAt, newData.Id)
	}, fastgameMerchantReconciliationDiffsIdKey, fastgameMerchantReconciliationDiffsPeriodIdRoundIdKey)
	return err
}

func (m *defaultMerchantReconciliationDiffsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameMerchantReconciliationDiffsIdPrefix, primary)
}

func (m *defaultMerchantReconciliationDiffsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantReconciliationDiffsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantReconciliationDiffsModel) tableName() string {
	return m.table
}
