// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantNetworkConfigsFieldNames          = builder.RawFieldNames(&MerchantNetworkConfigs{})
	merchantNetworkConfigsRows                = strings.Join(merchantNetworkConfigsFieldNames, ",")
	merchantNetworkConfigsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantNetworkConfigsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantNetworkConfigsRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantNetworkConfigsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameMerchantNetworkConfigsIdPrefix                    = "biz:fastgame:merchantNetworkConfigs:id:"
	bizFastgameMerchantNetworkConfigsMerchantIdEnvironmentPrefix = "biz:fastgame:merchantNetworkConfigs:merchantId:environment:"
)

type (
	merchantNetworkConfigsModel interface {
		Insert(ctx context.Context, data *MerchantNetworkConfigs) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MerchantNetworkConfigs, error)
		FindOneByMerchantIdEnvironment(ctx context.Context, merchantId uint64, environment string) (*MerchantNetworkConfigs, error)
		Update(ctx context.Context, data *MerchantNetworkConfigs) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMerchantNetworkConfigsModel struct {
		sqlc.CachedConn
		table string
	}

	MerchantNetworkConfigs struct {
		Id                  uint64         `db:"id"`                    // 主键ID
		MerchantId          uint64         `db:"merchant_id"`           // 关联商户ID (merchant_accounts.id)
		Environment         string         `db:"environment"`           // 适用环境: PRODUCTION, STAGING, SANDBOX
		IpWhitelist         string         `db:"ip_whitelist"`          // 允许调用我方网关的下游服务器 IPv4/IPv6 或 CIDR 数组
		EgressIps           sql.NullString `db:"egress_ips"`            // 我方出网回调下游时告知商户的固定出网 IP 列表
		GeoBlockEnabled     uint64         `db:"geo_block_enabled"`     // 是否开启地理区域封锁: 0-关闭, 1-开启
		GeoBlockedCountries sql.NullString `db:"geo_blocked_countries"` // 禁止访问该商户游戏的国家/地区二字码数组 (如: ["CN", "US", "SG"])
		RateLimitRps        uint64         `db:"rate_limit_rps"`        // 单商户在我方网关的并发频率上限 (Requests Per Second)
		Status              uint64         `db:"status"`                // 策略生效状态: 0-停用, 1-启用
		CreatedAt           time.Time      `db:"created_at"`            // 创建时间
		UpdatedAt           time.Time      `db:"updated_at"`            // 最后更新时间
	}
)

func newMerchantNetworkConfigsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantNetworkConfigsModel {
	return &defaultMerchantNetworkConfigsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchant_network_configs`",
	}
}

func (m *defaultMerchantNetworkConfigsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameMerchantNetworkConfigsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantNetworkConfigsIdPrefix, id)
	fastgameMerchantNetworkConfigsMerchantIdEnvironmentKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantNetworkConfigsMerchantIdEnvironmentPrefix, data.MerchantId, data.Environment)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameMerchantNetworkConfigsIdKey, fastgameMerchantNetworkConfigsMerchantIdEnvironmentKey)
	return err
}

func (m *defaultMerchantNetworkConfigsModel) FindOne(ctx context.Context, id uint64) (*MerchantNetworkConfigs, error) {
	fastgameMerchantNetworkConfigsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantNetworkConfigsIdPrefix, id)
	var resp MerchantNetworkConfigs
	err := m.QueryRowCtx(ctx, &resp, fastgameMerchantNetworkConfigsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantNetworkConfigsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantNetworkConfigsModel) FindOneByMerchantIdEnvironment(ctx context.Context, merchantId uint64, environment string) (*MerchantNetworkConfigs, error) {
	fastgameMerchantNetworkConfigsMerchantIdEnvironmentKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantNetworkConfigsMerchantIdEnvironmentPrefix, merchantId, environment)
	var resp MerchantNetworkConfigs
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameMerchantNetworkConfigsMerchantIdEnvironmentKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `merchant_id` = ? and `environment` = ? limit 1", merchantNetworkConfigsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, merchantId, environment); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantNetworkConfigsModel) Insert(ctx context.Context, data *MerchantNetworkConfigs) (sql.Result, error) {
	fastgameMerchantNetworkConfigsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantNetworkConfigsIdPrefix, data.Id)
	fastgameMerchantNetworkConfigsMerchantIdEnvironmentKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantNetworkConfigsMerchantIdEnvironmentPrefix, data.MerchantId, data.Environment)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantNetworkConfigsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MerchantId, data.Environment, data.IpWhitelist, data.EgressIps, data.GeoBlockEnabled, data.GeoBlockedCountries, data.RateLimitRps, data.Status)
	}, fastgameMerchantNetworkConfigsIdKey, fastgameMerchantNetworkConfigsMerchantIdEnvironmentKey)
	return ret, err
}

func (m *defaultMerchantNetworkConfigsModel) Update(ctx context.Context, newData *MerchantNetworkConfigs) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameMerchantNetworkConfigsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantNetworkConfigsIdPrefix, data.Id)
	fastgameMerchantNetworkConfigsMerchantIdEnvironmentKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantNetworkConfigsMerchantIdEnvironmentPrefix, data.MerchantId, data.Environment)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantNetworkConfigsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MerchantId, newData.Environment, newData.IpWhitelist, newData.EgressIps, newData.GeoBlockEnabled, newData.GeoBlockedCountries, newData.RateLimitRps, newData.Status, newData.Id)
	}, fastgameMerchantNetworkConfigsIdKey, fastgameMerchantNetworkConfigsMerchantIdEnvironmentKey)
	return err
}

func (m *defaultMerchantNetworkConfigsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameMerchantNetworkConfigsIdPrefix, primary)
}

func (m *defaultMerchantNetworkConfigsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantNetworkConfigsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantNetworkConfigsModel) tableName() string {
	return m.table
}
