// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantAccountsFieldNames          = builder.RawFieldNames(&MerchantAccounts{})
	merchantAccountsRows                = strings.Join(merchantAccountsFieldNames, ",")
	merchantAccountsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantAccountsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantAccountsRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantAccountsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameMerchantAccountsIdPrefix           = "biz:fastgame:merchantAccounts:id:"
	bizFastgameMerchantAccountsMerchantCodePrefix = "biz:fastgame:merchantAccounts:merchantCode:"
)

type (
	merchantAccountsModel interface {
		Insert(ctx context.Context, data *MerchantAccounts) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MerchantAccounts, error)
		FindOneByMerchantCode(ctx context.Context, merchantCode string) (*MerchantAccounts, error)
		Update(ctx context.Context, data *MerchantAccounts) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMerchantAccountsModel struct {
		sqlc.CachedConn
		table string
	}

	MerchantAccounts struct {
		Id               uint64    `db:"id"`                 // 商户主键ID
		MerchantCode     string    `db:"merchant_code"`      // 商户唯一代号 (全局识别码，如: M_WINNER_01)
		Name             string    `db:"name"`               // 商户对外主体全称
		ShortName        string    `db:"short_name"`         // 商户简称 (大厅显示或简短标识)
		CompanyRegNumber string    `db:"company_reg_number"` // 海外法人实体注册编号/商业执照号
		TierLevel        uint64    `db:"tier_level"`         // 商户层级: 1-直客, 2-主聚合商(Master Aggregator), 3-子分销渠道
		ParentId         uint64    `db:"parent_id"`          // 父级商户ID (针对分销与聚合层级，0为顶级主体)
		DefaultCurrency  string    `db:"default_currency"`   // 法定基准对账币种 (ISO-4217 代码，如 USD, BRL, PHP)
		ContactName      string    `db:"contact_name"`       // 主要商务/技术对接人姓名
		ContactEmail     string    `db:"contact_email"`      // 核心对接邮箱
		ContactTelegram  string    `db:"contact_telegram"`   // Telegram 对接账号/群组
		Status           uint64    `db:"status"`             // 商户主体状态: 0-待激活, 1-正常营业, 2-临时封禁/风控, 3-已注销
		CreatedAt        time.Time `db:"created_at"`         // 创建时间
		UpdatedAt        time.Time `db:"updated_at"`         // 最后更新时间
	}
)

func newMerchantAccountsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantAccountsModel {
	return &defaultMerchantAccountsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchant_accounts`",
	}
}

func (m *defaultMerchantAccountsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameMerchantAccountsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantAccountsIdPrefix, id)
	fastgameMerchantAccountsMerchantCodeKey := fmt.Sprintf("%s%v", bizFastgameMerchantAccountsMerchantCodePrefix, data.MerchantCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameMerchantAccountsIdKey, fastgameMerchantAccountsMerchantCodeKey)
	return err
}

func (m *defaultMerchantAccountsModel) FindOne(ctx context.Context, id uint64) (*MerchantAccounts, error) {
	fastgameMerchantAccountsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantAccountsIdPrefix, id)
	var resp MerchantAccounts
	err := m.QueryRowCtx(ctx, &resp, fastgameMerchantAccountsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantAccountsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantAccountsModel) FindOneByMerchantCode(ctx context.Context, merchantCode string) (*MerchantAccounts, error) {
	fastgameMerchantAccountsMerchantCodeKey := fmt.Sprintf("%s%v", bizFastgameMerchantAccountsMerchantCodePrefix, merchantCode)
	var resp MerchantAccounts
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameMerchantAccountsMerchantCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `merchant_code` = ? limit 1", merchantAccountsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, merchantCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantAccountsModel) Insert(ctx context.Context, data *MerchantAccounts) (sql.Result, error) {
	fastgameMerchantAccountsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantAccountsIdPrefix, data.Id)
	fastgameMerchantAccountsMerchantCodeKey := fmt.Sprintf("%s%v", bizFastgameMerchantAccountsMerchantCodePrefix, data.MerchantCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantAccountsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MerchantCode, data.Name, data.ShortName, data.CompanyRegNumber, data.TierLevel, data.ParentId, data.DefaultCurrency, data.ContactName, data.ContactEmail, data.ContactTelegram, data.Status)
	}, fastgameMerchantAccountsIdKey, fastgameMerchantAccountsMerchantCodeKey)
	return ret, err
}

func (m *defaultMerchantAccountsModel) Update(ctx context.Context, newData *MerchantAccounts) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameMerchantAccountsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantAccountsIdPrefix, data.Id)
	fastgameMerchantAccountsMerchantCodeKey := fmt.Sprintf("%s%v", bizFastgameMerchantAccountsMerchantCodePrefix, data.MerchantCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantAccountsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MerchantCode, newData.Name, newData.ShortName, newData.CompanyRegNumber, newData.TierLevel, newData.ParentId, newData.DefaultCurrency, newData.ContactName, newData.ContactEmail, newData.ContactTelegram, newData.Status, newData.Id)
	}, fastgameMerchantAccountsIdKey, fastgameMerchantAccountsMerchantCodeKey)
	return err
}

func (m *defaultMerchantAccountsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameMerchantAccountsIdPrefix, primary)
}

func (m *defaultMerchantAccountsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantAccountsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantAccountsModel) tableName() string {
	return m.table
}
