// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantContractsFieldNames          = builder.RawFieldNames(&MerchantContracts{})
	merchantContractsRows                = strings.Join(merchantContractsFieldNames, ",")
	merchantContractsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantContractsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantContractsRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantContractsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameMerchantContractsIdPrefix         = "biz:fastgame:merchantContracts:id:"
	bizFastgameMerchantContractsContractNoPrefix = "biz:fastgame:merchantContracts:contractNo:"
)

type (
	merchantContractsModel interface {
		Insert(ctx context.Context, data *MerchantContracts) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MerchantContracts, error)
		FindOneByContractNo(ctx context.Context, contractNo string) (*MerchantContracts, error)
		Update(ctx context.Context, data *MerchantContracts) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMerchantContractsModel struct {
		sqlc.CachedConn
		table string
	}

	MerchantContracts struct {
		Id                  uint64         `db:"id"`                    // 合同主键ID
		MerchantId          uint64         `db:"merchant_id"`           // 关联商户ID (merchant_accounts.id)
		ContractNo          string         `db:"contract_no"`           // 商务纸质/电子合同唯一编号
		SettlementModel     string         `db:"settlement_model"`      // 商业结算模式: GGR (总博弈毛利抽成), NGR (扣减红利后抽成), FLAT_FEE (固定月保底)
		SettlementCurrency  string         `db:"settlement_currency"`   // 合同法定义务结算货币
		BaseRate            float64        `db:"base_rate"`             // 基础技术服务分成比率 (如 0.1200 代表 12%)
		TieredRates         sql.NullString `db:"tiered_rates"`          // 阶梯费率配置 (如月流水超$100K降至10%: [{"min_ggr": 0, "max_ggr": 100000, "rate": 0.12}, {"min_ggr": 100001, "max_ggr": -1, "rate": 0.10}])
		MonthlyMinGuarantee float64        `db:"monthly_min_guarantee"` // 月度保底消费要求 (USD，若未达标按此补足)
		EffectiveStart      time.Time      `db:"effective_start"`       // 合同法律生效开始日期
		EffectiveEnd        time.Time      `db:"effective_end"`         // 合同截止到期日期
		Status              uint64         `db:"status"`                // 合同状态: 0-作废, 1-正常生效, 2-已过期
		CreatedAt           time.Time      `db:"created_at"`            // 录入时间
		UpdatedAt           time.Time      `db:"updated_at"`            // 最后更新时间
	}
)

func newMerchantContractsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantContractsModel {
	return &defaultMerchantContractsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchant_contracts`",
	}
}

func (m *defaultMerchantContractsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameMerchantContractsContractNoKey := fmt.Sprintf("%s%v", bizFastgameMerchantContractsContractNoPrefix, data.ContractNo)
	fastgameMerchantContractsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantContractsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameMerchantContractsContractNoKey, fastgameMerchantContractsIdKey)
	return err
}

func (m *defaultMerchantContractsModel) FindOne(ctx context.Context, id uint64) (*MerchantContracts, error) {
	fastgameMerchantContractsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantContractsIdPrefix, id)
	var resp MerchantContracts
	err := m.QueryRowCtx(ctx, &resp, fastgameMerchantContractsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantContractsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantContractsModel) FindOneByContractNo(ctx context.Context, contractNo string) (*MerchantContracts, error) {
	fastgameMerchantContractsContractNoKey := fmt.Sprintf("%s%v", bizFastgameMerchantContractsContractNoPrefix, contractNo)
	var resp MerchantContracts
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameMerchantContractsContractNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `contract_no` = ? limit 1", merchantContractsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, contractNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantContractsModel) Insert(ctx context.Context, data *MerchantContracts) (sql.Result, error) {
	fastgameMerchantContractsContractNoKey := fmt.Sprintf("%s%v", bizFastgameMerchantContractsContractNoPrefix, data.ContractNo)
	fastgameMerchantContractsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantContractsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantContractsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MerchantId, data.ContractNo, data.SettlementModel, data.SettlementCurrency, data.BaseRate, data.TieredRates, data.MonthlyMinGuarantee, data.EffectiveStart, data.EffectiveEnd, data.Status)
	}, fastgameMerchantContractsContractNoKey, fastgameMerchantContractsIdKey)
	return ret, err
}

func (m *defaultMerchantContractsModel) Update(ctx context.Context, newData *MerchantContracts) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameMerchantContractsContractNoKey := fmt.Sprintf("%s%v", bizFastgameMerchantContractsContractNoPrefix, data.ContractNo)
	fastgameMerchantContractsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantContractsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantContractsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MerchantId, newData.ContractNo, newData.SettlementModel, newData.SettlementCurrency, newData.BaseRate, newData.TieredRates, newData.MonthlyMinGuarantee, newData.EffectiveStart, newData.EffectiveEnd, newData.Status, newData.Id)
	}, fastgameMerchantContractsContractNoKey, fastgameMerchantContractsIdKey)
	return err
}

func (m *defaultMerchantContractsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameMerchantContractsIdPrefix, primary)
}

func (m *defaultMerchantContractsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantContractsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantContractsModel) tableName() string {
	return m.table
}
