// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantWalletDlqFieldNames          = builder.RawFieldNames(&MerchantWalletDlq{})
	merchantWalletDlqRows                = strings.Join(merchantWalletDlqFieldNames, ",")
	merchantWalletDlqRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantWalletDlqFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantWalletDlqRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantWalletDlqFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameMerchantWalletDlqIdPrefix                = "biz:fastgame:merchantWalletDlq:id:"
	bizFastgameMerchantWalletDlqRoundIdActionTypePrefix = "biz:fastgame:merchantWalletDlq:roundId:actionType:"
)

type (
	merchantWalletDlqModel interface {
		Insert(ctx context.Context, data *MerchantWalletDlq) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MerchantWalletDlq, error)
		FindOneByRoundIdActionType(ctx context.Context, roundId string, actionType string) (*MerchantWalletDlq, error)
		Update(ctx context.Context, data *MerchantWalletDlq) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMerchantWalletDlqModel struct {
		sqlc.CachedConn
		table string
	}

	MerchantWalletDlq struct {
		Id              uint64         `db:"id"`               // 自增流水主键ID
		MerchantId      uint64         `db:"merchant_id"`      // 关联商户ID
		RoundId         string         `db:"round_id"`         // 关联游戏全局唯一单局业务号 (业务幂等根基)
		ActionType      string         `db:"action_type"`      // 动作类型: BET (扣款), WIN (派彩), ROLLBACK (撤销)
		UserId          string         `db:"user_id"`          // 玩家在下游系统的唯一代号
		Amount          int64          `db:"amount"`           // 涉及资金数额 (按货币最小单位: 分 存储)
		Currency        string         `db:"currency"`         // 货币代号
		RequestPayload  string         `db:"request_payload"`  // 最后一次调用下游钱包时投递的完整 JSON 报文
		ResponsePayload sql.NullString `db:"response_payload"` // 下游返回的错误报文、HTTP状态码或网络异常快照
		HttpStatus      int64          `db:"http_status"`      // 最后一次通信 HTTP 状态码 (如: 504, 502, 0代表网络超时)
		RetryCount      uint64         `db:"retry_count"`      // 已执行的异步重试次数
		MaxRetries      uint64         `db:"max_retries"`      // 允许的最大自动重试次数
		NextRetryTime   time.Time      `db:"next_retry_time"`  // 下次计划调度补偿的时间戳 (指数退避计算)
		Status          string         `db:"status"`           // 补偿状态: PENDING (等待重试), PROCESSING (正在执行), SUCCESS (补偿成功), FAILED_FINAL (超限作废/需人工介入), MANUAL_FIXED (人工平账), SUSPENDED_BY_CIRCUIT (下游通道熔断暂停重试，待健康探测唤醒)
		CreatedAt       time.Time      `db:"created_at"`       // 首次入死信队列时间
		UpdatedAt       time.Time      `db:"updated_at"`       // 最后重试更新时间
	}
)

func newMerchantWalletDlqModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantWalletDlqModel {
	return &defaultMerchantWalletDlqModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchant_wallet_dlq`",
	}
}

func (m *defaultMerchantWalletDlqModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameMerchantWalletDlqIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantWalletDlqIdPrefix, id)
	fastgameMerchantWalletDlqRoundIdActionTypeKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantWalletDlqRoundIdActionTypePrefix, data.RoundId, data.ActionType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameMerchantWalletDlqIdKey, fastgameMerchantWalletDlqRoundIdActionTypeKey)
	return err
}

func (m *defaultMerchantWalletDlqModel) FindOne(ctx context.Context, id uint64) (*MerchantWalletDlq, error) {
	fastgameMerchantWalletDlqIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantWalletDlqIdPrefix, id)
	var resp MerchantWalletDlq
	err := m.QueryRowCtx(ctx, &resp, fastgameMerchantWalletDlqIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantWalletDlqRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantWalletDlqModel) FindOneByRoundIdActionType(ctx context.Context, roundId string, actionType string) (*MerchantWalletDlq, error) {
	fastgameMerchantWalletDlqRoundIdActionTypeKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantWalletDlqRoundIdActionTypePrefix, roundId, actionType)
	var resp MerchantWalletDlq
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameMerchantWalletDlqRoundIdActionTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `round_id` = ? and `action_type` = ? limit 1", merchantWalletDlqRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, roundId, actionType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantWalletDlqModel) Insert(ctx context.Context, data *MerchantWalletDlq) (sql.Result, error) {
	fastgameMerchantWalletDlqIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantWalletDlqIdPrefix, data.Id)
	fastgameMerchantWalletDlqRoundIdActionTypeKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantWalletDlqRoundIdActionTypePrefix, data.RoundId, data.ActionType)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantWalletDlqRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MerchantId, data.RoundId, data.ActionType, data.UserId, data.Amount, data.Currency, data.RequestPayload, data.ResponsePayload, data.HttpStatus, data.RetryCount, data.MaxRetries, data.NextRetryTime, data.Status)
	}, fastgameMerchantWalletDlqIdKey, fastgameMerchantWalletDlqRoundIdActionTypeKey)
	return ret, err
}

func (m *defaultMerchantWalletDlqModel) Update(ctx context.Context, newData *MerchantWalletDlq) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameMerchantWalletDlqIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantWalletDlqIdPrefix, data.Id)
	fastgameMerchantWalletDlqRoundIdActionTypeKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantWalletDlqRoundIdActionTypePrefix, data.RoundId, data.ActionType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantWalletDlqRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MerchantId, newData.RoundId, newData.ActionType, newData.UserId, newData.Amount, newData.Currency, newData.RequestPayload, newData.ResponsePayload, newData.HttpStatus, newData.RetryCount, newData.MaxRetries, newData.NextRetryTime, newData.Status, newData.Id)
	}, fastgameMerchantWalletDlqIdKey, fastgameMerchantWalletDlqRoundIdActionTypeKey)
	return err
}

func (m *defaultMerchantWalletDlqModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameMerchantWalletDlqIdPrefix, primary)
}

func (m *defaultMerchantWalletDlqModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantWalletDlqRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantWalletDlqModel) tableName() string {
	return m.table
}
