// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantWalletEndpointsFieldNames          = builder.RawFieldNames(&MerchantWalletEndpoints{})
	merchantWalletEndpointsRows                = strings.Join(merchantWalletEndpointsFieldNames, ",")
	merchantWalletEndpointsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantWalletEndpointsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantWalletEndpointsRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantWalletEndpointsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameMerchantWalletEndpointsIdPrefix                    = "biz:fastgame:merchantWalletEndpoints:id:"
	bizFastgameMerchantWalletEndpointsMerchantIdEnvironmentPrefix = "biz:fastgame:merchantWalletEndpoints:merchantId:environment:"
)

type (
	merchantWalletEndpointsModel interface {
		Insert(ctx context.Context, data *MerchantWalletEndpoints) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MerchantWalletEndpoints, error)
		FindOneByMerchantIdEnvironment(ctx context.Context, merchantId uint64, environment string) (*MerchantWalletEndpoints, error)
		Update(ctx context.Context, data *MerchantWalletEndpoints) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMerchantWalletEndpointsModel struct {
		sqlc.CachedConn
		table string
	}

	MerchantWalletEndpoints struct {
		Id              uint64    `db:"id"`                // 主键ID
		MerchantId      uint64    `db:"merchant_id"`       // 关联商户ID (merchant_accounts.id)
		Environment     string    `db:"environment"`       // 适用环境: PRODUCTION, STAGING, SANDBOX
		BaseUrl         string    `db:"base_url"`          // 下游 Seamless 钱包基础通信 URL (如 https://api.wallet.com)
		PathGetBalance  string    `db:"path_get_balance"`  // 查询余额接口绝对/相对路径
		PathBet         string    `db:"path_bet"`          // 原子扣款 (Bet) 接口路径
		PathWin         string    `db:"path_win"`          // 原子派彩 (Win) 接口路径
		PathRollback    string    `db:"path_rollback"`     // 撤单回滚 (Rollback) 接口路径
		TimeoutMs       uint64    `db:"timeout_ms"`        // HTTP 请求硬超时时间 (单位: 毫秒)
		RetryLimit      uint64    `db:"retry_limit"`       // 遇网络故障最大重试次数
		CircuitStatus   string    `db:"circuit_status"`    // 断路器当前健康度: HEALTHY (正常), DEGRADED (慢请求降级), TRIPPED (熔断阻断)
		FailCountWindow uint64    `db:"fail_count_window"` // 当前滑动窗口内累计失败通信次数
		CreatedAt       time.Time `db:"created_at"`        // 创建时间
		UpdatedAt       time.Time `db:"updated_at"`        // 最后更新时间
	}
)

func newMerchantWalletEndpointsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantWalletEndpointsModel {
	return &defaultMerchantWalletEndpointsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchant_wallet_endpoints`",
	}
}

func (m *defaultMerchantWalletEndpointsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameMerchantWalletEndpointsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantWalletEndpointsIdPrefix, id)
	fastgameMerchantWalletEndpointsMerchantIdEnvironmentKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantWalletEndpointsMerchantIdEnvironmentPrefix, data.MerchantId, data.Environment)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameMerchantWalletEndpointsIdKey, fastgameMerchantWalletEndpointsMerchantIdEnvironmentKey)
	return err
}

func (m *defaultMerchantWalletEndpointsModel) FindOne(ctx context.Context, id uint64) (*MerchantWalletEndpoints, error) {
	fastgameMerchantWalletEndpointsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantWalletEndpointsIdPrefix, id)
	var resp MerchantWalletEndpoints
	err := m.QueryRowCtx(ctx, &resp, fastgameMerchantWalletEndpointsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantWalletEndpointsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantWalletEndpointsModel) FindOneByMerchantIdEnvironment(ctx context.Context, merchantId uint64, environment string) (*MerchantWalletEndpoints, error) {
	fastgameMerchantWalletEndpointsMerchantIdEnvironmentKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantWalletEndpointsMerchantIdEnvironmentPrefix, merchantId, environment)
	var resp MerchantWalletEndpoints
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameMerchantWalletEndpointsMerchantIdEnvironmentKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `merchant_id` = ? and `environment` = ? limit 1", merchantWalletEndpointsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, merchantId, environment); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantWalletEndpointsModel) Insert(ctx context.Context, data *MerchantWalletEndpoints) (sql.Result, error) {
	fastgameMerchantWalletEndpointsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantWalletEndpointsIdPrefix, data.Id)
	fastgameMerchantWalletEndpointsMerchantIdEnvironmentKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantWalletEndpointsMerchantIdEnvironmentPrefix, data.MerchantId, data.Environment)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantWalletEndpointsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MerchantId, data.Environment, data.BaseUrl, data.PathGetBalance, data.PathBet, data.PathWin, data.PathRollback, data.TimeoutMs, data.RetryLimit, data.CircuitStatus, data.FailCountWindow)
	}, fastgameMerchantWalletEndpointsIdKey, fastgameMerchantWalletEndpointsMerchantIdEnvironmentKey)
	return ret, err
}

func (m *defaultMerchantWalletEndpointsModel) Update(ctx context.Context, newData *MerchantWalletEndpoints) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameMerchantWalletEndpointsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantWalletEndpointsIdPrefix, data.Id)
	fastgameMerchantWalletEndpointsMerchantIdEnvironmentKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantWalletEndpointsMerchantIdEnvironmentPrefix, data.MerchantId, data.Environment)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantWalletEndpointsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MerchantId, newData.Environment, newData.BaseUrl, newData.PathGetBalance, newData.PathBet, newData.PathWin, newData.PathRollback, newData.TimeoutMs, newData.RetryLimit, newData.CircuitStatus, newData.FailCountWindow, newData.Id)
	}, fastgameMerchantWalletEndpointsIdKey, fastgameMerchantWalletEndpointsMerchantIdEnvironmentKey)
	return err
}

func (m *defaultMerchantWalletEndpointsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameMerchantWalletEndpointsIdPrefix, primary)
}

func (m *defaultMerchantWalletEndpointsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantWalletEndpointsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantWalletEndpointsModel) tableName() string {
	return m.table
}
