// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantRiskPoliciesFieldNames          = builder.RawFieldNames(&MerchantRiskPolicies{})
	merchantRiskPoliciesRows                = strings.Join(merchantRiskPoliciesFieldNames, ",")
	merchantRiskPoliciesRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantRiskPoliciesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantRiskPoliciesRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantRiskPoliciesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameMerchantRiskPoliciesIdPrefix         = "biz:fastgame:merchantRiskPolicies:id:"
	bizFastgameMerchantRiskPoliciesMerchantIdPrefix = "biz:fastgame:merchantRiskPolicies:merchantId:"
)

type (
	merchantRiskPoliciesModel interface {
		Insert(ctx context.Context, data *MerchantRiskPolicies) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MerchantRiskPolicies, error)
		FindOneByMerchantId(ctx context.Context, merchantId uint64) (*MerchantRiskPolicies, error)
		Update(ctx context.Context, data *MerchantRiskPolicies) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMerchantRiskPoliciesModel struct {
		sqlc.CachedConn
		table string
	}

	MerchantRiskPolicies struct {
		Id                    uint64    `db:"id"`                       // 主键ID
		MerchantId            uint64    `db:"merchant_id"`              // 关联商户ID (merchant_accounts.id)
		MaxSingleBet          int64     `db:"max_single_bet"`           // 单注投注硬上限 (分，如 50000 = $500.00)
		MinSingleBet          int64     `db:"min_single_bet"`           // 单注投注硬下限 (分，如 10 = $0.10)
		MaxSingleWin          int64     `db:"max_single_win"`           // 单局派彩硬顶上限 (分，如 25000000 = $250,000.00，超额系统自动截断拦截)
		HourlyLossLimit       int64     `db:"hourly_loss_limit"`        // 商户池1小时最大允许累计净亏损熔断额 (分，如 -$10,000 则触发商户级熔断)
		DailyLossLimit        int64     `db:"daily_loss_limit"`         // 商户池24小时最大允许累计净亏损熔断额 (分)
		MaxUserConcurrentBets uint64    `db:"max_user_concurrent_bets"` // 单玩家同时并发抛竿/下注最大允许线程数 (防并发刷单脚本)
		AutoSuspendOnLeak     uint64    `db:"auto_suspend_on_leak"`     // 当算法检测到疑似数学穿池时是否自动挂起该商户: 0-仅告警, 1-毫秒级自动挂起
		Status                uint64    `db:"status"`                   // 策略状态: 0-停用, 1-启用
		CreatedAt             time.Time `db:"created_at"`               // 创建时间
		UpdatedAt             time.Time `db:"updated_at"`               // 最后更新时间
	}
)

func newMerchantRiskPoliciesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantRiskPoliciesModel {
	return &defaultMerchantRiskPoliciesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchant_risk_policies`",
	}
}

func (m *defaultMerchantRiskPoliciesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameMerchantRiskPoliciesIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantRiskPoliciesIdPrefix, id)
	fastgameMerchantRiskPoliciesMerchantIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantRiskPoliciesMerchantIdPrefix, data.MerchantId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameMerchantRiskPoliciesIdKey, fastgameMerchantRiskPoliciesMerchantIdKey)
	return err
}

func (m *defaultMerchantRiskPoliciesModel) FindOne(ctx context.Context, id uint64) (*MerchantRiskPolicies, error) {
	fastgameMerchantRiskPoliciesIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantRiskPoliciesIdPrefix, id)
	var resp MerchantRiskPolicies
	err := m.QueryRowCtx(ctx, &resp, fastgameMerchantRiskPoliciesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantRiskPoliciesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantRiskPoliciesModel) FindOneByMerchantId(ctx context.Context, merchantId uint64) (*MerchantRiskPolicies, error) {
	fastgameMerchantRiskPoliciesMerchantIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantRiskPoliciesMerchantIdPrefix, merchantId)
	var resp MerchantRiskPolicies
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameMerchantRiskPoliciesMerchantIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `merchant_id` = ? limit 1", merchantRiskPoliciesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, merchantId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantRiskPoliciesModel) Insert(ctx context.Context, data *MerchantRiskPolicies) (sql.Result, error) {
	fastgameMerchantRiskPoliciesIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantRiskPoliciesIdPrefix, data.Id)
	fastgameMerchantRiskPoliciesMerchantIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantRiskPoliciesMerchantIdPrefix, data.MerchantId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantRiskPoliciesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MerchantId, data.MaxSingleBet, data.MinSingleBet, data.MaxSingleWin, data.HourlyLossLimit, data.DailyLossLimit, data.MaxUserConcurrentBets, data.AutoSuspendOnLeak, data.Status)
	}, fastgameMerchantRiskPoliciesIdKey, fastgameMerchantRiskPoliciesMerchantIdKey)
	return ret, err
}

func (m *defaultMerchantRiskPoliciesModel) Update(ctx context.Context, newData *MerchantRiskPolicies) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameMerchantRiskPoliciesIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantRiskPoliciesIdPrefix, data.Id)
	fastgameMerchantRiskPoliciesMerchantIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantRiskPoliciesMerchantIdPrefix, data.MerchantId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantRiskPoliciesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MerchantId, newData.MaxSingleBet, newData.MinSingleBet, newData.MaxSingleWin, newData.HourlyLossLimit, newData.DailyLossLimit, newData.MaxUserConcurrentBets, newData.AutoSuspendOnLeak, newData.Status, newData.Id)
	}, fastgameMerchantRiskPoliciesIdKey, fastgameMerchantRiskPoliciesMerchantIdKey)
	return err
}

func (m *defaultMerchantRiskPoliciesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameMerchantRiskPoliciesIdPrefix, primary)
}

func (m *defaultMerchantRiskPoliciesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantRiskPoliciesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantRiskPoliciesModel) tableName() string {
	return m.table
}
