// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantFinancialPeriodsFieldNames          = builder.RawFieldNames(&MerchantFinancialPeriods{})
	merchantFinancialPeriodsRows                = strings.Join(merchantFinancialPeriodsFieldNames, ",")
	merchantFinancialPeriodsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantFinancialPeriodsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	merchantFinancialPeriodsRowsWithPlaceHolder = strings.Join(stringx.Remove(merchantFinancialPeriodsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameMerchantFinancialPeriodsIdPrefix                   = "biz:fastgame:merchantFinancialPeriods:id:"
	bizFastgameMerchantFinancialPeriodsPeriodCodeMerchantIdPrefix = "biz:fastgame:merchantFinancialPeriods:periodCode:merchantId:"
)

type (
	merchantFinancialPeriodsModel interface {
		Insert(ctx context.Context, data *MerchantFinancialPeriods) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MerchantFinancialPeriods, error)
		FindOneByPeriodCodeMerchantId(ctx context.Context, periodCode string, merchantId uint64) (*MerchantFinancialPeriods, error)
		Update(ctx context.Context, data *MerchantFinancialPeriods) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMerchantFinancialPeriodsModel struct {
		sqlc.CachedConn
		table string
	}

	MerchantFinancialPeriods struct {
		Id                   uint64       `db:"id"`                    // 账单主键ID
		PeriodCode           string       `db:"period_code"`           // 账期结算代号 (按日如: D_20260914_M01, 按月如: M_202609_M01)
		MerchantId           uint64       `db:"merchant_id"`           // 关联商户ID
		MerchantCode         string       `db:"merchant_code"`         // 商户代号冗余
		PeriodType           string       `db:"period_type"`           // 账期类型: DAILY (日结), MONTHLY (月结账单)
		StartDate            time.Time    `db:"start_date"`            // 统计区间开始日期 (UTC)
		EndDate              time.Time    `db:"end_date"`              // 统计区间结束日期 (UTC)
		TotalRounds          uint64       `db:"total_rounds"`          // 区间内总投注局数
		TotalBet             int64        `db:"total_bet"`             // 总有效投注金额 (分)
		TotalWin             int64        `db:"total_win"`             // 总有效派彩金额 (分)
		Ggr                  int64        `db:"ggr"`                   // 博弈毛利总额 (分): total_bet - total_win
		PromoCost            int64        `db:"promo_cost"`            // 商户本期消耗的活动补贴成本 (分)
		ShareRateApplied     float64      `db:"share_rate_applied"`    // 本账期最终核算的有效分成比率
		FeeReceivable        float64      `db:"fee_receivable"`        // 我方技术服务费应收总额 (结算币种法币金额)
		SettlementCurrency   string       `db:"settlement_currency"`   // 账单计价货币
		ReconciliationStatus string       `db:"reconciliation_status"` // 对账审核状态: UNCONFIRMED (未确认), BALANCED (平账无误), DISCREPANCY (存在差异争议), SETTLED (已打款结清)
		ConfirmedAt          sql.NullTime `db:"confirmed_at"`          // 双方确认平账时间
		CreatedAt            time.Time    `db:"created_at"`            // 快照生成时间
		UpdatedAt            time.Time    `db:"updated_at"`            // 最后更新时间
	}
)

func newMerchantFinancialPeriodsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMerchantFinancialPeriodsModel {
	return &defaultMerchantFinancialPeriodsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`merchant_financial_periods`",
	}
}

func (m *defaultMerchantFinancialPeriodsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameMerchantFinancialPeriodsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantFinancialPeriodsIdPrefix, id)
	fastgameMerchantFinancialPeriodsPeriodCodeMerchantIdKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantFinancialPeriodsPeriodCodeMerchantIdPrefix, data.PeriodCode, data.MerchantId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameMerchantFinancialPeriodsIdKey, fastgameMerchantFinancialPeriodsPeriodCodeMerchantIdKey)
	return err
}

func (m *defaultMerchantFinancialPeriodsModel) FindOne(ctx context.Context, id uint64) (*MerchantFinancialPeriods, error) {
	fastgameMerchantFinancialPeriodsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantFinancialPeriodsIdPrefix, id)
	var resp MerchantFinancialPeriods
	err := m.QueryRowCtx(ctx, &resp, fastgameMerchantFinancialPeriodsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantFinancialPeriodsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantFinancialPeriodsModel) FindOneByPeriodCodeMerchantId(ctx context.Context, periodCode string, merchantId uint64) (*MerchantFinancialPeriods, error) {
	fastgameMerchantFinancialPeriodsPeriodCodeMerchantIdKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantFinancialPeriodsPeriodCodeMerchantIdPrefix, periodCode, merchantId)
	var resp MerchantFinancialPeriods
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameMerchantFinancialPeriodsPeriodCodeMerchantIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `period_code` = ? and `merchant_id` = ? limit 1", merchantFinancialPeriodsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, periodCode, merchantId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantFinancialPeriodsModel) Insert(ctx context.Context, data *MerchantFinancialPeriods) (sql.Result, error) {
	fastgameMerchantFinancialPeriodsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantFinancialPeriodsIdPrefix, data.Id)
	fastgameMerchantFinancialPeriodsPeriodCodeMerchantIdKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantFinancialPeriodsPeriodCodeMerchantIdPrefix, data.PeriodCode, data.MerchantId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, merchantFinancialPeriodsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PeriodCode, data.MerchantId, data.MerchantCode, data.PeriodType, data.StartDate, data.EndDate, data.TotalRounds, data.TotalBet, data.TotalWin, data.Ggr, data.PromoCost, data.ShareRateApplied, data.FeeReceivable, data.SettlementCurrency, data.ReconciliationStatus, data.ConfirmedAt)
	}, fastgameMerchantFinancialPeriodsIdKey, fastgameMerchantFinancialPeriodsPeriodCodeMerchantIdKey)
	return ret, err
}

func (m *defaultMerchantFinancialPeriodsModel) Update(ctx context.Context, newData *MerchantFinancialPeriods) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameMerchantFinancialPeriodsIdKey := fmt.Sprintf("%s%v", bizFastgameMerchantFinancialPeriodsIdPrefix, data.Id)
	fastgameMerchantFinancialPeriodsPeriodCodeMerchantIdKey := fmt.Sprintf("%s%v:%v", bizFastgameMerchantFinancialPeriodsPeriodCodeMerchantIdPrefix, data.PeriodCode, data.MerchantId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, merchantFinancialPeriodsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.PeriodCode, newData.MerchantId, newData.MerchantCode, newData.PeriodType, newData.StartDate, newData.EndDate, newData.TotalRounds, newData.TotalBet, newData.TotalWin, newData.Ggr, newData.PromoCost, newData.ShareRateApplied, newData.FeeReceivable, newData.SettlementCurrency, newData.ReconciliationStatus, newData.ConfirmedAt, newData.Id)
	}, fastgameMerchantFinancialPeriodsIdKey, fastgameMerchantFinancialPeriodsPeriodCodeMerchantIdKey)
	return err
}

func (m *defaultMerchantFinancialPeriodsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameMerchantFinancialPeriodsIdPrefix, primary)
}

func (m *defaultMerchantFinancialPeriodsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", merchantFinancialPeriodsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMerchantFinancialPeriodsModel) tableName() string {
	return m.table
}
