// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	playerGameSessionsFieldNames          = builder.RawFieldNames(&PlayerGameSessions{})
	playerGameSessionsRows                = strings.Join(playerGameSessionsFieldNames, ",")
	playerGameSessionsRowsExpectAutoSet   = strings.Join(stringx.Remove(playerGameSessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	playerGameSessionsRowsWithPlaceHolder = strings.Join(stringx.Remove(playerGameSessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgamePlayerGameSessionsIdPrefix           = "biz:fastgame:playerGameSessions:id:"
	bizFastgamePlayerGameSessionsSessionTokenPrefix = "biz:fastgame:playerGameSessions:sessionToken:"
)

type (
	playerGameSessionsModel interface {
		Insert(ctx context.Context, data *PlayerGameSessions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*PlayerGameSessions, error)
		FindOneBySessionToken(ctx context.Context, sessionToken string) (*PlayerGameSessions, error)
		Update(ctx context.Context, data *PlayerGameSessions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPlayerGameSessionsModel struct {
		sqlc.CachedConn
		table string
	}

	PlayerGameSessions struct {
		Id           uint64    `db:"id"`            // è‡ªå¢žä¸»é”®ID
		SessionToken string    `db:"session_token"` // å‰å°æ¸¸æˆè¿è¡Œæ—¶æ¡æ‰‹ Token (UUID/å®‰å…¨éšæœºä¸²)
		MerchantId   uint64    `db:"merchant_id"`   // æ‰€å±žå•†æˆ·ID
		MerchantCode string    `db:"merchant_code"` // å•†æˆ·ä»£å·
		UserId       string    `db:"user_id"`       // ä¸‹æ¸¸çŽ©å®¶å”¯ä¸€ID
		UserName     string    `db:"user_name"`     // çŽ©å®¶æ˜¾ç¤ºæ˜µç§° (è„±æ•)
		GameId       uint64    `db:"game_id"`       // è¿›å…¥çš„ç›®æ ‡æ¸¸æˆID
		GameCode     string    `db:"game_code"`     // ç›®æ ‡æ¸¸æˆä»£å·
		Currency     string    `db:"currency"`      // çŽ©å®¶å½“å‰è¿›å…¥æºå¸¦çš„è´§å¸ä»£ç 
		IsDemo       uint64    `db:"is_demo"`       // æ˜¯å¦è¯•çŽ©ä¼šè¯: 0-çœŸé‡‘, 1-è¯•çŽ©
		Lang         string    `db:"lang"`          // çŽ©å®¶æŒ‡å®šçš„åˆå§‹è¯­ç§ä»£ç 
		ClientIp     string    `db:"client_ip"`     // å•†æˆ·è¯·æ±‚æ¢å–Tokenæ—¶çš„çŽ©å®¶IP
		DeviceType   string    `db:"device_type"`   // ç»ˆç«¯ç±»åž‹: MOBILE, DESKTOP, TABLET
		Status       uint64    `db:"status"`        // ä¼šè¯çŠ¶æ€: 1-æœ‰æ•ˆæ¿€æ´», 2-å·²è¢«é¡¶å·è¸¢å‡º, 3-å·²è‡ªç„¶è¿‡æœŸ
		ExpireAt     time.Time `db:"expire_at"`     // Token ç¡¬æ€§è¿‡æœŸæ—¶é—´æˆ³ (é€šå¸¸ä¸ºç”ŸæˆåŽ 24 å°æ—¶)
		CreatedAt    time.Time `db:"created_at"`    // æ¢å–å¯åŠ¨ç¥¨æ®æ—¶é—´
		UpdatedAt    time.Time `db:"updated_at"`    // æ›´æ–°æ—¶é—´
	}
)

func newPlayerGameSessionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPlayerGameSessionsModel {
	return &defaultPlayerGameSessionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`player_game_sessions`",
	}
}

func (m *defaultPlayerGameSessionsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgamePlayerGameSessionsIdKey := fmt.Sprintf("%s%v", bizFastgamePlayerGameSessionsIdPrefix, id)
	fastgamePlayerGameSessionsSessionTokenKey := fmt.Sprintf("%s%v", bizFastgamePlayerGameSessionsSessionTokenPrefix, data.SessionToken)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgamePlayerGameSessionsIdKey, fastgamePlayerGameSessionsSessionTokenKey)
	return err
}

func (m *defaultPlayerGameSessionsModel) FindOne(ctx context.Context, id uint64) (*PlayerGameSessions, error) {
	fastgamePlayerGameSessionsIdKey := fmt.Sprintf("%s%v", bizFastgamePlayerGameSessionsIdPrefix, id)
	var resp PlayerGameSessions
	err := m.QueryRowCtx(ctx, &resp, fastgamePlayerGameSessionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", playerGameSessionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlayerGameSessionsModel) FindOneBySessionToken(ctx context.Context, sessionToken string) (*PlayerGameSessions, error) {
	fastgamePlayerGameSessionsSessionTokenKey := fmt.Sprintf("%s%v", bizFastgamePlayerGameSessionsSessionTokenPrefix, sessionToken)
	var resp PlayerGameSessions
	err := m.QueryRowIndexCtx(ctx, &resp, fastgamePlayerGameSessionsSessionTokenKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `session_token` = ? limit 1", playerGameSessionsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, sessionToken); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlayerGameSessionsModel) Insert(ctx context.Context, data *PlayerGameSessions) (sql.Result, error) {
	fastgamePlayerGameSessionsIdKey := fmt.Sprintf("%s%v", bizFastgamePlayerGameSessionsIdPrefix, data.Id)
	fastgamePlayerGameSessionsSessionTokenKey := fmt.Sprintf("%s%v", bizFastgamePlayerGameSessionsSessionTokenPrefix, data.SessionToken)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, playerGameSessionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SessionToken, data.MerchantId, data.MerchantCode, data.UserId, data.UserName, data.GameId, data.GameCode, data.Currency, data.IsDemo, data.Lang, data.ClientIp, data.DeviceType, data.Status, data.ExpireAt)
	}, fastgamePlayerGameSessionsIdKey, fastgamePlayerGameSessionsSessionTokenKey)
	return ret, err
}

func (m *defaultPlayerGameSessionsModel) Update(ctx context.Context, newData *PlayerGameSessions) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgamePlayerGameSessionsIdKey := fmt.Sprintf("%s%v", bizFastgamePlayerGameSessionsIdPrefix, data.Id)
	fastgamePlayerGameSessionsSessionTokenKey := fmt.Sprintf("%s%v", bizFastgamePlayerGameSessionsSessionTokenPrefix, data.SessionToken)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, playerGameSessionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.SessionToken, newData.MerchantId, newData.MerchantCode, newData.UserId, newData.UserName, newData.GameId, newData.GameCode, newData.Currency, newData.IsDemo, newData.Lang, newData.ClientIp, newData.DeviceType, newData.Status, newData.ExpireAt, newData.Id)
	}, fastgamePlayerGameSessionsIdKey, fastgamePlayerGameSessionsSessionTokenKey)
	return err
}

func (m *defaultPlayerGameSessionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgamePlayerGameSessionsIdPrefix, primary)
}

func (m *defaultPlayerGameSessionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", playerGameSessionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPlayerGameSessionsModel) tableName() string {
	return m.table
}
