// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	promoRewardGrantsFieldNames          = builder.RawFieldNames(&PromoRewardGrants{})
	promoRewardGrantsRows                = strings.Join(promoRewardGrantsFieldNames, ",")
	promoRewardGrantsRowsExpectAutoSet   = strings.Join(stringx.Remove(promoRewardGrantsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	promoRewardGrantsRowsWithPlaceHolder = strings.Join(stringx.Remove(promoRewardGrantsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgamePromoRewardGrantsIdPrefix      = "biz:fastgame:promoRewardGrants:id:"
	bizFastgamePromoRewardGrantsGrantIdPrefix = "biz:fastgame:promoRewardGrants:grantId:"
)

type (
	promoRewardGrantsModel interface {
		Insert(ctx context.Context, data *PromoRewardGrants) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*PromoRewardGrants, error)
		FindOneByGrantId(ctx context.Context, grantId string) (*PromoRewardGrants, error)
		Update(ctx context.Context, data *PromoRewardGrants) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPromoRewardGrantsModel struct {
		sqlc.CachedConn
		table string
	}

	PromoRewardGrants struct {
		Id                     uint64    `db:"id"`                       // 派发流水主键ID
		GrantId                string    `db:"grant_id"`                 // 奖励发放全局唯一业务号 (UUID / 雪花ID)
		CampaignId             uint64    `db:"campaign_id"`              // 来源活动ID
		CampaignCode           string    `db:"campaign_code"`            // 来源活动代号
		MerchantId             uint64    `db:"merchant_id"`              // 商户ID
		MerchantCode           string    `db:"merchant_code"`            // 商户代号
		UserId                 string    `db:"user_id"`                  // 获赠玩家ID
		Currency               string    `db:"currency"`                 // 奖励币种
		RewardType             string    `db:"reward_type"`              // 奖励类型: BONUS_MONEY (红利金), REAL_CASH (真金可提现), FREE_ROUNDS (免费游戏局)
		Amount                 int64     `db:"amount"`                   // 派发金额 (分) 或 免费局数
		WageringMultiplier     float64   `db:"wagering_multiplier"`      // 流水打码量要求倍数 (如 10.00 代表需达到 10 倍下注方可转为真金提现)
		WageringRequiredAmount int64     `db:"wagering_required_amount"` // 实际需要达到的绝对下注打码金额 (分): amount * wagering_multiplier
		WageringCurrentAmount  int64     `db:"wagering_current_amount"`  // 玩家当前已完成的累计打码金额 (分)
		TargetWallet           string    `db:"target_wallet"`            // 打入目标账户: BONUS (商户红利钱包), REAL (主资金钱包), TECHNICAL_MOCK (仅本地虚拟金)
		Status                 string    `db:"status"`                   // 奖励状态: ISSUED (已发放到账), IN_WAGERING (打码中), COMPLETED (流水达标结清), EXPIRED (超时未完成没收)
		ValidUntil             time.Time `db:"valid_until"`              // 奖励有效期截止时间 (超时自动销毁)
		CreatedAt              time.Time `db:"created_at"`               // 派发时间
		UpdatedAt              time.Time `db:"updated_at"`               // 更新时间
	}
)

func newPromoRewardGrantsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPromoRewardGrantsModel {
	return &defaultPromoRewardGrantsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`promo_reward_grants`",
	}
}

func (m *defaultPromoRewardGrantsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgamePromoRewardGrantsGrantIdKey := fmt.Sprintf("%s%v", bizFastgamePromoRewardGrantsGrantIdPrefix, data.GrantId)
	fastgamePromoRewardGrantsIdKey := fmt.Sprintf("%s%v", bizFastgamePromoRewardGrantsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgamePromoRewardGrantsGrantIdKey, fastgamePromoRewardGrantsIdKey)
	return err
}

func (m *defaultPromoRewardGrantsModel) FindOne(ctx context.Context, id uint64) (*PromoRewardGrants, error) {
	fastgamePromoRewardGrantsIdKey := fmt.Sprintf("%s%v", bizFastgamePromoRewardGrantsIdPrefix, id)
	var resp PromoRewardGrants
	err := m.QueryRowCtx(ctx, &resp, fastgamePromoRewardGrantsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", promoRewardGrantsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPromoRewardGrantsModel) FindOneByGrantId(ctx context.Context, grantId string) (*PromoRewardGrants, error) {
	fastgamePromoRewardGrantsGrantIdKey := fmt.Sprintf("%s%v", bizFastgamePromoRewardGrantsGrantIdPrefix, grantId)
	var resp PromoRewardGrants
	err := m.QueryRowIndexCtx(ctx, &resp, fastgamePromoRewardGrantsGrantIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `grant_id` = ? limit 1", promoRewardGrantsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, grantId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPromoRewardGrantsModel) Insert(ctx context.Context, data *PromoRewardGrants) (sql.Result, error) {
	fastgamePromoRewardGrantsGrantIdKey := fmt.Sprintf("%s%v", bizFastgamePromoRewardGrantsGrantIdPrefix, data.GrantId)
	fastgamePromoRewardGrantsIdKey := fmt.Sprintf("%s%v", bizFastgamePromoRewardGrantsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, promoRewardGrantsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GrantId, data.CampaignId, data.CampaignCode, data.MerchantId, data.MerchantCode, data.UserId, data.Currency, data.RewardType, data.Amount, data.WageringMultiplier, data.WageringRequiredAmount, data.WageringCurrentAmount, data.TargetWallet, data.Status, data.ValidUntil)
	}, fastgamePromoRewardGrantsGrantIdKey, fastgamePromoRewardGrantsIdKey)
	return ret, err
}

func (m *defaultPromoRewardGrantsModel) Update(ctx context.Context, newData *PromoRewardGrants) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgamePromoRewardGrantsGrantIdKey := fmt.Sprintf("%s%v", bizFastgamePromoRewardGrantsGrantIdPrefix, data.GrantId)
	fastgamePromoRewardGrantsIdKey := fmt.Sprintf("%s%v", bizFastgamePromoRewardGrantsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, promoRewardGrantsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.GrantId, newData.CampaignId, newData.CampaignCode, newData.MerchantId, newData.MerchantCode, newData.UserId, newData.Currency, newData.RewardType, newData.Amount, newData.WageringMultiplier, newData.WageringRequiredAmount, newData.WageringCurrentAmount, newData.TargetWallet, newData.Status, newData.ValidUntil, newData.Id)
	}, fastgamePromoRewardGrantsGrantIdKey, fastgamePromoRewardGrantsIdKey)
	return err
}

func (m *defaultPromoRewardGrantsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgamePromoRewardGrantsIdPrefix, primary)
}

func (m *defaultPromoRewardGrantsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", promoRewardGrantsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPromoRewardGrantsModel) tableName() string {
	return m.table
}
