// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	promoCampaignsFieldNames          = builder.RawFieldNames(&PromoCampaigns{})
	promoCampaignsRows                = strings.Join(promoCampaignsFieldNames, ",")
	promoCampaignsRowsExpectAutoSet   = strings.Join(stringx.Remove(promoCampaignsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	promoCampaignsRowsWithPlaceHolder = strings.Join(stringx.Remove(promoCampaignsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgamePromoCampaignsIdPrefix           = "biz:fastgame:promoCampaigns:id:"
	bizFastgamePromoCampaignsCampaignCodePrefix = "biz:fastgame:promoCampaigns:campaignCode:"
)

type (
	promoCampaignsModel interface {
		Insert(ctx context.Context, data *PromoCampaigns) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*PromoCampaigns, error)
		FindOneByCampaignCode(ctx context.Context, campaignCode string) (*PromoCampaigns, error)
		Update(ctx context.Context, data *PromoCampaigns) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPromoCampaignsModel struct {
		sqlc.CachedConn
		table string
	}

	PromoCampaigns struct {
		Id               uint64         `db:"id"`                 // 活动自增主键ID
		CampaignCode     string         `db:"campaign_code"`      // 活动唯一业务代号 (如: TOURN_DEEPSEA_2026_Q3)
		CampaignType     string         `db:"campaign_type"`      // 活动类型: TOURNAMENT (锦标赛), MISSION (局数挑战), MYSTERY_DROP (随机空投), FREE_ROUND (免费转/局)
		Title            string         `db:"title"`              // 多语言活动主标题: {"en": "Deep Sea Hunter Tourney", "zh": "深海猎手锦标赛"}
		Description      string         `db:"description"`        // 多语言活动规则与副标题富文本说明
		ThemeSkinId      string         `db:"theme_skin_id"`      // Cocos 客户端挂载的活动主题/换肤包ID
		ScopeType        string         `db:"scope_type"`         // 适用商户范围: ALL (全平台商户通用), INCLUDED (指定白名单商户), EXCLUDED (排除特定商户)
		MerchantScopeIds sql.NullString `db:"merchant_scope_ids"` // 商户ID数组白名单/黑名单 (如: [1, 5, 12])
		GameScopeCodes   string         `db:"game_scope_codes"`   // 参与该活动的游戏代号数组 (如: ["fishing_deep_sea", "gold_miner"])
		StartTime        time.Time      `db:"start_time"`         // 活动开始时间戳 (UTC)
		EndTime          time.Time      `db:"end_time"`           // 活动结束时间戳 (UTC)
		DisplayTimezone  string         `db:"display_timezone"`   // 前端面板展示默认转换的参考时区 (如: America/Sao_Paulo)
		BudgetCap        int64          `db:"budget_cap"`         // 活动总资金预算硬顶上限 (分，0表示不设限)
		TotalSpent       int64          `db:"total_spent"`        // 当前系统已实际派发的奖励总成本 (分)
		RewardCurrency   string         `db:"reward_currency"`    // 奖励计价基准货币
		Status           string         `db:"status"`             // 活动状态: DRAFT (草稿), SCHEDULED (已排期), RUNNING (进行中), PAUSED (已暂停), FINISHED (已结算完毕), CANCELLED (已废弃)
		CreatedAt        time.Time      `db:"created_at"`         // 创建时间
		UpdatedAt        time.Time      `db:"updated_at"`         // 更新时间
	}
)

func newPromoCampaignsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPromoCampaignsModel {
	return &defaultPromoCampaignsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`promo_campaigns`",
	}
}

func (m *defaultPromoCampaignsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgamePromoCampaignsCampaignCodeKey := fmt.Sprintf("%s%v", bizFastgamePromoCampaignsCampaignCodePrefix, data.CampaignCode)
	fastgamePromoCampaignsIdKey := fmt.Sprintf("%s%v", bizFastgamePromoCampaignsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgamePromoCampaignsCampaignCodeKey, fastgamePromoCampaignsIdKey)
	return err
}

func (m *defaultPromoCampaignsModel) FindOne(ctx context.Context, id uint64) (*PromoCampaigns, error) {
	fastgamePromoCampaignsIdKey := fmt.Sprintf("%s%v", bizFastgamePromoCampaignsIdPrefix, id)
	var resp PromoCampaigns
	err := m.QueryRowCtx(ctx, &resp, fastgamePromoCampaignsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", promoCampaignsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPromoCampaignsModel) FindOneByCampaignCode(ctx context.Context, campaignCode string) (*PromoCampaigns, error) {
	fastgamePromoCampaignsCampaignCodeKey := fmt.Sprintf("%s%v", bizFastgamePromoCampaignsCampaignCodePrefix, campaignCode)
	var resp PromoCampaigns
	err := m.QueryRowIndexCtx(ctx, &resp, fastgamePromoCampaignsCampaignCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `campaign_code` = ? limit 1", promoCampaignsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, campaignCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPromoCampaignsModel) Insert(ctx context.Context, data *PromoCampaigns) (sql.Result, error) {
	fastgamePromoCampaignsCampaignCodeKey := fmt.Sprintf("%s%v", bizFastgamePromoCampaignsCampaignCodePrefix, data.CampaignCode)
	fastgamePromoCampaignsIdKey := fmt.Sprintf("%s%v", bizFastgamePromoCampaignsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, promoCampaignsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CampaignCode, data.CampaignType, data.Title, data.Description, data.ThemeSkinId, data.ScopeType, data.MerchantScopeIds, data.GameScopeCodes, data.StartTime, data.EndTime, data.DisplayTimezone, data.BudgetCap, data.TotalSpent, data.RewardCurrency, data.Status)
	}, fastgamePromoCampaignsCampaignCodeKey, fastgamePromoCampaignsIdKey)
	return ret, err
}

func (m *defaultPromoCampaignsModel) Update(ctx context.Context, newData *PromoCampaigns) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgamePromoCampaignsCampaignCodeKey := fmt.Sprintf("%s%v", bizFastgamePromoCampaignsCampaignCodePrefix, data.CampaignCode)
	fastgamePromoCampaignsIdKey := fmt.Sprintf("%s%v", bizFastgamePromoCampaignsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, promoCampaignsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CampaignCode, newData.CampaignType, newData.Title, newData.Description, newData.ThemeSkinId, newData.ScopeType, newData.MerchantScopeIds, newData.GameScopeCodes, newData.StartTime, newData.EndTime, newData.DisplayTimezone, newData.BudgetCap, newData.TotalSpent, newData.RewardCurrency, newData.Status, newData.Id)
	}, fastgamePromoCampaignsCampaignCodeKey, fastgamePromoCampaignsIdKey)
	return err
}

func (m *defaultPromoCampaignsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgamePromoCampaignsIdPrefix, primary)
}

func (m *defaultPromoCampaignsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", promoCampaignsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPromoCampaignsModel) tableName() string {
	return m.table
}
