// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	promoUserProgressFieldNames          = builder.RawFieldNames(&PromoUserProgress{})
	promoUserProgressRows                = strings.Join(promoUserProgressFieldNames, ",")
	promoUserProgressRowsExpectAutoSet   = strings.Join(stringx.Remove(promoUserProgressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	promoUserProgressRowsWithPlaceHolder = strings.Join(stringx.Remove(promoUserProgressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgamePromoUserProgressIdPrefix                                  = "biz:fastgame:promoUserProgress:id:"
	bizFastgamePromoUserProgressCampaignIdMissionIdMerchantIdUserIdPrefix = "biz:fastgame:promoUserProgress:campaignId:missionId:merchantId:userId:"
)

type (
	promoUserProgressModel interface {
		Insert(ctx context.Context, data *PromoUserProgress) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*PromoUserProgress, error)
		FindOneByCampaignIdMissionIdMerchantIdUserId(ctx context.Context, campaignId uint64, missionId uint64, merchantId uint64, userId string) (*PromoUserProgress, error)
		Update(ctx context.Context, data *PromoUserProgress) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPromoUserProgressModel struct {
		sqlc.CachedConn
		table string
	}

	PromoUserProgress struct {
		Id               uint64    `db:"id"`                // 自增主键ID
		CampaignId       uint64    `db:"campaign_id"`       // 关联活动ID
		MissionId        uint64    `db:"mission_id"`        // 关联具体任务ID (0 表示锦标赛等无具体子任务)
		MerchantId       uint64    `db:"merchant_id"`       // 所属商户ID
		MerchantCode     string    `db:"merchant_code"`     // 商户代号
		UserId           string    `db:"user_id"`           // 下游玩家唯一代号
		CurrentScore     float64   `db:"current_score"`     // 当前锦标赛积分 / 最高倍率快照
		AccumulatedValue int64     `db:"accumulated_value"` // 当前任务已累加进度数值 (如已完成 32 局)
		TargetValue      int64     `db:"target_value"`      // 目标数值快照
		IsCompleted      uint64    `db:"is_completed"`      // 是否已达成目标: 0-未完成, 1-已达成
		IsRewardClaimed  uint64    `db:"is_reward_claimed"` // 奖励是否已被领取核销: 0-未领, 1-已领取
		LastActionTime   time.Time `db:"last_action_time"`  // 最后一次进度推进时间
		CreatedAt        time.Time `db:"created_at"`        // 首次参与记录时间
		UpdatedAt        time.Time `db:"updated_at"`        // 更新时间
	}
)

func newPromoUserProgressModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPromoUserProgressModel {
	return &defaultPromoUserProgressModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`promo_user_progress`",
	}
}

func (m *defaultPromoUserProgressModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgamePromoUserProgressCampaignIdMissionIdMerchantIdUserIdKey := fmt.Sprintf("%s%v:%v:%v:%v", bizFastgamePromoUserProgressCampaignIdMissionIdMerchantIdUserIdPrefix, data.CampaignId, data.MissionId, data.MerchantId, data.UserId)
	fastgamePromoUserProgressIdKey := fmt.Sprintf("%s%v", bizFastgamePromoUserProgressIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgamePromoUserProgressCampaignIdMissionIdMerchantIdUserIdKey, fastgamePromoUserProgressIdKey)
	return err
}

func (m *defaultPromoUserProgressModel) FindOne(ctx context.Context, id uint64) (*PromoUserProgress, error) {
	fastgamePromoUserProgressIdKey := fmt.Sprintf("%s%v", bizFastgamePromoUserProgressIdPrefix, id)
	var resp PromoUserProgress
	err := m.QueryRowCtx(ctx, &resp, fastgamePromoUserProgressIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", promoUserProgressRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPromoUserProgressModel) FindOneByCampaignIdMissionIdMerchantIdUserId(ctx context.Context, campaignId uint64, missionId uint64, merchantId uint64, userId string) (*PromoUserProgress, error) {
	fastgamePromoUserProgressCampaignIdMissionIdMerchantIdUserIdKey := fmt.Sprintf("%s%v:%v:%v:%v", bizFastgamePromoUserProgressCampaignIdMissionIdMerchantIdUserIdPrefix, campaignId, missionId, merchantId, userId)
	var resp PromoUserProgress
	err := m.QueryRowIndexCtx(ctx, &resp, fastgamePromoUserProgressCampaignIdMissionIdMerchantIdUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `campaign_id` = ? and `mission_id` = ? and `merchant_id` = ? and `user_id` = ? limit 1", promoUserProgressRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, campaignId, missionId, merchantId, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPromoUserProgressModel) Insert(ctx context.Context, data *PromoUserProgress) (sql.Result, error) {
	fastgamePromoUserProgressCampaignIdMissionIdMerchantIdUserIdKey := fmt.Sprintf("%s%v:%v:%v:%v", bizFastgamePromoUserProgressCampaignIdMissionIdMerchantIdUserIdPrefix, data.CampaignId, data.MissionId, data.MerchantId, data.UserId)
	fastgamePromoUserProgressIdKey := fmt.Sprintf("%s%v", bizFastgamePromoUserProgressIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, promoUserProgressRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CampaignId, data.MissionId, data.MerchantId, data.MerchantCode, data.UserId, data.CurrentScore, data.AccumulatedValue, data.TargetValue, data.IsCompleted, data.IsRewardClaimed, data.LastActionTime)
	}, fastgamePromoUserProgressCampaignIdMissionIdMerchantIdUserIdKey, fastgamePromoUserProgressIdKey)
	return ret, err
}

func (m *defaultPromoUserProgressModel) Update(ctx context.Context, newData *PromoUserProgress) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgamePromoUserProgressCampaignIdMissionIdMerchantIdUserIdKey := fmt.Sprintf("%s%v:%v:%v:%v", bizFastgamePromoUserProgressCampaignIdMissionIdMerchantIdUserIdPrefix, data.CampaignId, data.MissionId, data.MerchantId, data.UserId)
	fastgamePromoUserProgressIdKey := fmt.Sprintf("%s%v", bizFastgamePromoUserProgressIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, promoUserProgressRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CampaignId, newData.MissionId, newData.MerchantId, newData.MerchantCode, newData.UserId, newData.CurrentScore, newData.AccumulatedValue, newData.TargetValue, newData.IsCompleted, newData.IsRewardClaimed, newData.LastActionTime, newData.Id)
	}, fastgamePromoUserProgressCampaignIdMissionIdMerchantIdUserIdKey, fastgamePromoUserProgressIdKey)
	return err
}

func (m *defaultPromoUserProgressModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgamePromoUserProgressIdPrefix, primary)
}

func (m *defaultPromoUserProgressModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", promoUserProgressRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPromoUserProgressModel) tableName() string {
	return m.table
}
