// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	promoMissionDefinitionsFieldNames          = builder.RawFieldNames(&PromoMissionDefinitions{})
	promoMissionDefinitionsRows                = strings.Join(promoMissionDefinitionsFieldNames, ",")
	promoMissionDefinitionsRowsExpectAutoSet   = strings.Join(stringx.Remove(promoMissionDefinitionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	promoMissionDefinitionsRowsWithPlaceHolder = strings.Join(stringx.Remove(promoMissionDefinitionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgamePromoMissionDefinitionsIdPrefix          = "biz:fastgame:promoMissionDefinitions:id:"
	bizFastgamePromoMissionDefinitionsMissionCodePrefix = "biz:fastgame:promoMissionDefinitions:missionCode:"
)

type (
	promoMissionDefinitionsModel interface {
		Insert(ctx context.Context, data *PromoMissionDefinitions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*PromoMissionDefinitions, error)
		FindOneByMissionCode(ctx context.Context, missionCode string) (*PromoMissionDefinitions, error)
		Update(ctx context.Context, data *PromoMissionDefinitions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPromoMissionDefinitionsModel struct {
		sqlc.CachedConn
		table string
	}

	PromoMissionDefinitions struct {
		Id             uint64         `db:"id"`               // 任务主键ID
		CampaignId     uint64         `db:"campaign_id"`      // 关联主活动ID (promo_campaigns.id)
		MissionCode    string         `db:"mission_code"`     // 任务唯一代号 (如: MISSION_SPIN_50_ROUNDS)
		MissionType    string         `db:"mission_type"`     // 任务类型: ROUND_COUNT (累计局数), TOTAL_BET (累计投注), HIT_SPECIFIC_FISH (钓起指定特定鱼种)
		TargetGameCode string         `db:"target_game_code"` // 目标机台代号 (ALL为全游戏通用)
		ThresholdValue int64          `db:"threshold_value"`  // 达成任务所需的目标数值 (如局数需达到 50，或投注额需达到 $100)
		MinSingleBet   int64          `db:"min_single_bet"`   // 单次下注有效计数的最低金额限制 (分)
		RewardType     string         `db:"reward_type"`      // 达成后发放奖励类型: BONUS_MONEY (红利金), FREE_SPINS (免费抛竿券), TICKET (锦标赛门票)
		RewardAmount   int64          `db:"reward_amount"`    // 奖励金额 (分) 或 赠送免费局数量
		RewardMeta     sql.NullString `db:"reward_meta"`      // 奖励附加元数据 (如免费局对应的固定单注面额: {"free_bet_value": 20})
		SortOrder      int64          `db:"sort_order"`       // 任务展示排序
		CreatedAt      time.Time      `db:"created_at"`       // 创建时间
		UpdatedAt      time.Time      `db:"updated_at"`       // 更新时间
	}
)

func newPromoMissionDefinitionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPromoMissionDefinitionsModel {
	return &defaultPromoMissionDefinitionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`promo_mission_definitions`",
	}
}

func (m *defaultPromoMissionDefinitionsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgamePromoMissionDefinitionsIdKey := fmt.Sprintf("%s%v", bizFastgamePromoMissionDefinitionsIdPrefix, id)
	fastgamePromoMissionDefinitionsMissionCodeKey := fmt.Sprintf("%s%v", bizFastgamePromoMissionDefinitionsMissionCodePrefix, data.MissionCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgamePromoMissionDefinitionsIdKey, fastgamePromoMissionDefinitionsMissionCodeKey)
	return err
}

func (m *defaultPromoMissionDefinitionsModel) FindOne(ctx context.Context, id uint64) (*PromoMissionDefinitions, error) {
	fastgamePromoMissionDefinitionsIdKey := fmt.Sprintf("%s%v", bizFastgamePromoMissionDefinitionsIdPrefix, id)
	var resp PromoMissionDefinitions
	err := m.QueryRowCtx(ctx, &resp, fastgamePromoMissionDefinitionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", promoMissionDefinitionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPromoMissionDefinitionsModel) FindOneByMissionCode(ctx context.Context, missionCode string) (*PromoMissionDefinitions, error) {
	fastgamePromoMissionDefinitionsMissionCodeKey := fmt.Sprintf("%s%v", bizFastgamePromoMissionDefinitionsMissionCodePrefix, missionCode)
	var resp PromoMissionDefinitions
	err := m.QueryRowIndexCtx(ctx, &resp, fastgamePromoMissionDefinitionsMissionCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `mission_code` = ? limit 1", promoMissionDefinitionsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, missionCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPromoMissionDefinitionsModel) Insert(ctx context.Context, data *PromoMissionDefinitions) (sql.Result, error) {
	fastgamePromoMissionDefinitionsIdKey := fmt.Sprintf("%s%v", bizFastgamePromoMissionDefinitionsIdPrefix, data.Id)
	fastgamePromoMissionDefinitionsMissionCodeKey := fmt.Sprintf("%s%v", bizFastgamePromoMissionDefinitionsMissionCodePrefix, data.MissionCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, promoMissionDefinitionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CampaignId, data.MissionCode, data.MissionType, data.TargetGameCode, data.ThresholdValue, data.MinSingleBet, data.RewardType, data.RewardAmount, data.RewardMeta, data.SortOrder)
	}, fastgamePromoMissionDefinitionsIdKey, fastgamePromoMissionDefinitionsMissionCodeKey)
	return ret, err
}

func (m *defaultPromoMissionDefinitionsModel) Update(ctx context.Context, newData *PromoMissionDefinitions) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgamePromoMissionDefinitionsIdKey := fmt.Sprintf("%s%v", bizFastgamePromoMissionDefinitionsIdPrefix, data.Id)
	fastgamePromoMissionDefinitionsMissionCodeKey := fmt.Sprintf("%s%v", bizFastgamePromoMissionDefinitionsMissionCodePrefix, data.MissionCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, promoMissionDefinitionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CampaignId, newData.MissionCode, newData.MissionType, newData.TargetGameCode, newData.ThresholdValue, newData.MinSingleBet, newData.RewardType, newData.RewardAmount, newData.RewardMeta, newData.SortOrder, newData.Id)
	}, fastgamePromoMissionDefinitionsIdKey, fastgamePromoMissionDefinitionsMissionCodeKey)
	return err
}

func (m *defaultPromoMissionDefinitionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgamePromoMissionDefinitionsIdPrefix, primary)
}

func (m *defaultPromoMissionDefinitionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", promoMissionDefinitionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPromoMissionDefinitionsModel) tableName() string {
	return m.table
}
