// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	promoTournamentRulesFieldNames          = builder.RawFieldNames(&PromoTournamentRules{})
	promoTournamentRulesRows                = strings.Join(promoTournamentRulesFieldNames, ",")
	promoTournamentRulesRowsExpectAutoSet   = strings.Join(stringx.Remove(promoTournamentRulesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	promoTournamentRulesRowsWithPlaceHolder = strings.Join(stringx.Remove(promoTournamentRulesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgamePromoTournamentRulesIdPrefix         = "biz:fastgame:promoTournamentRules:id:"
	bizFastgamePromoTournamentRulesCampaignIdPrefix = "biz:fastgame:promoTournamentRules:campaignId:"
)

type (
	promoTournamentRulesModel interface {
		Insert(ctx context.Context, data *PromoTournamentRules) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*PromoTournamentRules, error)
		FindOneByCampaignId(ctx context.Context, campaignId uint64) (*PromoTournamentRules, error)
		Update(ctx context.Context, data *PromoTournamentRules) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPromoTournamentRulesModel struct {
		sqlc.CachedConn
		table string
	}

	PromoTournamentRules struct {
		Id                   uint64       `db:"id"`                     // 主键ID
		CampaignId           uint64       `db:"campaign_id"`            // 关联活动ID (promo_campaigns.id)
		ScoreCalculationType string       `db:"score_calculation_type"` // 积分计分模型: HIGHEST_MULTIPLIER (单局最高倍数), TURNOVER_ACCUMULATED (累计投注总额), WIN_STREAK (连续命中次数), TOTAL_NET_WIN (总净赢额)
		MinQualifyingBet     int64        `db:"min_qualifying_bet"`     // 参与该锦标赛的单注最低门槛 (分，如 50 = $0.50，低于此额不计入积分)
		LeaderboardSize      uint64       `db:"leaderboard_size"`       // 前台展示的上榜总人数 (如 Top 100)
		PrizePoolType        string       `db:"prize_pool_type"`        // 奖池类型: FIXED (固定保底奖金), PROGRESSIVE (流水动态抽水注水奖池)
		TotalPrizePool       int64        `db:"total_prize_pool"`       // 总奖池固定金额 (分)
		PrizeDistribution    string       `db:"prize_distribution"`     // 排名奖励分配阶梯 JSON: [{"rank_from": 1, "rank_to": 1, "reward_type": "CASH", "amount": 100000}, {"rank_from": 2, "rank_to": 5, "reward_type": "CASH", "amount": 20000}]
		IsSettled            uint64       `db:"is_settled"`             // 活动到期是否已完成奖金自动计算派发: 0-未结算, 1-已完成派发
		SettledAt            sql.NullTime `db:"settled_at"`             // 终榜实际结算时间戳
		CreatedAt            time.Time    `db:"created_at"`             // 创建时间
		UpdatedAt            time.Time    `db:"updated_at"`             // 更新时间
	}
)

func newPromoTournamentRulesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPromoTournamentRulesModel {
	return &defaultPromoTournamentRulesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`promo_tournament_rules`",
	}
}

func (m *defaultPromoTournamentRulesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgamePromoTournamentRulesCampaignIdKey := fmt.Sprintf("%s%v", bizFastgamePromoTournamentRulesCampaignIdPrefix, data.CampaignId)
	fastgamePromoTournamentRulesIdKey := fmt.Sprintf("%s%v", bizFastgamePromoTournamentRulesIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgamePromoTournamentRulesCampaignIdKey, fastgamePromoTournamentRulesIdKey)
	return err
}

func (m *defaultPromoTournamentRulesModel) FindOne(ctx context.Context, id uint64) (*PromoTournamentRules, error) {
	fastgamePromoTournamentRulesIdKey := fmt.Sprintf("%s%v", bizFastgamePromoTournamentRulesIdPrefix, id)
	var resp PromoTournamentRules
	err := m.QueryRowCtx(ctx, &resp, fastgamePromoTournamentRulesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", promoTournamentRulesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPromoTournamentRulesModel) FindOneByCampaignId(ctx context.Context, campaignId uint64) (*PromoTournamentRules, error) {
	fastgamePromoTournamentRulesCampaignIdKey := fmt.Sprintf("%s%v", bizFastgamePromoTournamentRulesCampaignIdPrefix, campaignId)
	var resp PromoTournamentRules
	err := m.QueryRowIndexCtx(ctx, &resp, fastgamePromoTournamentRulesCampaignIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `campaign_id` = ? limit 1", promoTournamentRulesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, campaignId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPromoTournamentRulesModel) Insert(ctx context.Context, data *PromoTournamentRules) (sql.Result, error) {
	fastgamePromoTournamentRulesCampaignIdKey := fmt.Sprintf("%s%v", bizFastgamePromoTournamentRulesCampaignIdPrefix, data.CampaignId)
	fastgamePromoTournamentRulesIdKey := fmt.Sprintf("%s%v", bizFastgamePromoTournamentRulesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, promoTournamentRulesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CampaignId, data.ScoreCalculationType, data.MinQualifyingBet, data.LeaderboardSize, data.PrizePoolType, data.TotalPrizePool, data.PrizeDistribution, data.IsSettled, data.SettledAt)
	}, fastgamePromoTournamentRulesCampaignIdKey, fastgamePromoTournamentRulesIdKey)
	return ret, err
}

func (m *defaultPromoTournamentRulesModel) Update(ctx context.Context, newData *PromoTournamentRules) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgamePromoTournamentRulesCampaignIdKey := fmt.Sprintf("%s%v", bizFastgamePromoTournamentRulesCampaignIdPrefix, data.CampaignId)
	fastgamePromoTournamentRulesIdKey := fmt.Sprintf("%s%v", bizFastgamePromoTournamentRulesIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, promoTournamentRulesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CampaignId, newData.ScoreCalculationType, newData.MinQualifyingBet, newData.LeaderboardSize, newData.PrizePoolType, newData.TotalPrizePool, newData.PrizeDistribution, newData.IsSettled, newData.SettledAt, newData.Id)
	}, fastgamePromoTournamentRulesCampaignIdKey, fastgamePromoTournamentRulesIdKey)
	return err
}

func (m *defaultPromoTournamentRulesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgamePromoTournamentRulesIdPrefix, primary)
}

func (m *defaultPromoTournamentRulesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", promoTournamentRulesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPromoTournamentRulesModel) tableName() string {
	return m.table
}
