// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	rptExportTasksFieldNames          = builder.RawFieldNames(&RptExportTasks{})
	rptExportTasksRows                = strings.Join(rptExportTasksFieldNames, ",")
	rptExportTasksRowsExpectAutoSet   = strings.Join(stringx.Remove(rptExportTasksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	rptExportTasksRowsWithPlaceHolder = strings.Join(stringx.Remove(rptExportTasksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameRptExportTasksIdPrefix     = "biz:fastgame:rptExportTasks:id:"
	bizFastgameRptExportTasksTaskIdPrefix = "biz:fastgame:rptExportTasks:taskId:"
)

type (
	rptExportTasksModel interface {
		Insert(ctx context.Context, data *RptExportTasks) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*RptExportTasks, error)
		FindOneByTaskId(ctx context.Context, taskId string) (*RptExportTasks, error)
		Update(ctx context.Context, data *RptExportTasks) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultRptExportTasksModel struct {
		sqlc.CachedConn
		table string
	}

	RptExportTasks struct {
		Id            uint64    `db:"id"`              // 任务自增主键ID
		TaskId        string    `db:"task_id"`         // 任务对外唯一代号 (UUID)
		MerchantId    uint64    `db:"merchant_id"`     // 关联商户ID
		MerchantCode  string    `db:"merchant_code"`   // 商户代号
		OperatorId    uint64    `db:"operator_id"`     // 发起导出的商户操作人员用户ID
		ReportType    string    `db:"report_type"`     // 导出的报表类型: ROUNDS_DETAIL (原始注单), DAILY_SUMMARY (日总账), PLAYER_RANK (玩家排行)
		FilterParams  string    `db:"filter_params"`   // 导出时的查询筛选条件快照 (日期范围、币种、游戏等)
		FileFormat    string    `db:"file_format"`     // 导出格式: CSV, XLSX
		FileSizeBytes uint64    `db:"file_size_bytes"` // 生成的文件大小 (字节)
		DownloadUrl   string    `db:"download_url"`    // 生成的临时安全下载地址 (S3/OSS 预签名 URL)
		TaskStatus    string    `db:"task_status"`     // 任务状态: PENDING (排队中), PROCESSING (生成中), SUCCESS (已就绪), FAILED (生成失败)
		ErrorMsg      string    `db:"error_msg"`       // 失败原因说明
		ExpireAt      time.Time `db:"expire_at"`       // 文件下载链接失效时间 (通常保留 72 小时自动清理)
		CreatedAt     time.Time `db:"created_at"`      // 提交时间
		UpdatedAt     time.Time `db:"updated_at"`      // 更新时间
	}
)

func newRptExportTasksModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRptExportTasksModel {
	return &defaultRptExportTasksModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`rpt_export_tasks`",
	}
}

func (m *defaultRptExportTasksModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameRptExportTasksIdKey := fmt.Sprintf("%s%v", bizFastgameRptExportTasksIdPrefix, id)
	fastgameRptExportTasksTaskIdKey := fmt.Sprintf("%s%v", bizFastgameRptExportTasksTaskIdPrefix, data.TaskId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameRptExportTasksIdKey, fastgameRptExportTasksTaskIdKey)
	return err
}

func (m *defaultRptExportTasksModel) FindOne(ctx context.Context, id uint64) (*RptExportTasks, error) {
	fastgameRptExportTasksIdKey := fmt.Sprintf("%s%v", bizFastgameRptExportTasksIdPrefix, id)
	var resp RptExportTasks
	err := m.QueryRowCtx(ctx, &resp, fastgameRptExportTasksIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rptExportTasksRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRptExportTasksModel) FindOneByTaskId(ctx context.Context, taskId string) (*RptExportTasks, error) {
	fastgameRptExportTasksTaskIdKey := fmt.Sprintf("%s%v", bizFastgameRptExportTasksTaskIdPrefix, taskId)
	var resp RptExportTasks
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameRptExportTasksTaskIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `task_id` = ? limit 1", rptExportTasksRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, taskId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRptExportTasksModel) Insert(ctx context.Context, data *RptExportTasks) (sql.Result, error) {
	fastgameRptExportTasksIdKey := fmt.Sprintf("%s%v", bizFastgameRptExportTasksIdPrefix, data.Id)
	fastgameRptExportTasksTaskIdKey := fmt.Sprintf("%s%v", bizFastgameRptExportTasksTaskIdPrefix, data.TaskId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, rptExportTasksRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TaskId, data.MerchantId, data.MerchantCode, data.OperatorId, data.ReportType, data.FilterParams, data.FileFormat, data.FileSizeBytes, data.DownloadUrl, data.TaskStatus, data.ErrorMsg, data.ExpireAt)
	}, fastgameRptExportTasksIdKey, fastgameRptExportTasksTaskIdKey)
	return ret, err
}

func (m *defaultRptExportTasksModel) Update(ctx context.Context, newData *RptExportTasks) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameRptExportTasksIdKey := fmt.Sprintf("%s%v", bizFastgameRptExportTasksIdPrefix, data.Id)
	fastgameRptExportTasksTaskIdKey := fmt.Sprintf("%s%v", bizFastgameRptExportTasksTaskIdPrefix, data.TaskId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, rptExportTasksRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TaskId, newData.MerchantId, newData.MerchantCode, newData.OperatorId, newData.ReportType, newData.FilterParams, newData.FileFormat, newData.FileSizeBytes, newData.DownloadUrl, newData.TaskStatus, newData.ErrorMsg, newData.ExpireAt, newData.Id)
	}, fastgameRptExportTasksIdKey, fastgameRptExportTasksTaskIdKey)
	return err
}

func (m *defaultRptExportTasksModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameRptExportTasksIdPrefix, primary)
}

func (m *defaultRptExportTasksModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rptExportTasksRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRptExportTasksModel) tableName() string {
	return m.table
}
