// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package biz

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	systemExchangeRatesFieldNames          = builder.RawFieldNames(&SystemExchangeRates{})
	systemExchangeRatesRows                = strings.Join(systemExchangeRatesFieldNames, ",")
	systemExchangeRatesRowsExpectAutoSet   = strings.Join(stringx.Remove(systemExchangeRatesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	systemExchangeRatesRowsWithPlaceHolder = strings.Join(stringx.Remove(systemExchangeRatesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	bizFastgameSystemExchangeRatesIdPrefix                                      = "biz:fastgame:systemExchangeRates:id:"
	bizFastgameSystemExchangeRatesBaseCurrencyTargetCurrencyEffectiveDatePrefix = "biz:fastgame:systemExchangeRates:baseCurrency:targetCurrency:effectiveDate:"
)

type (
	systemExchangeRatesModel interface {
		Insert(ctx context.Context, data *SystemExchangeRates) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SystemExchangeRates, error)
		FindOneByBaseCurrencyTargetCurrencyEffectiveDate(ctx context.Context, baseCurrency string, targetCurrency string, effectiveDate time.Time) (*SystemExchangeRates, error)
		Update(ctx context.Context, data *SystemExchangeRates) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultSystemExchangeRatesModel struct {
		sqlc.CachedConn
		table string
	}

	SystemExchangeRates struct {
		Id             uint64    `db:"id"`              // è‡ªå¢žä¸»é”®ID
		BaseCurrency   string    `db:"base_currency"`   // åŸºå‡†é”šå®šè´§å¸ (é€šå¸¸ä¸º USD)
		TargetCurrency string    `db:"target_currency"` // ç›®æ ‡è´§å¸ä»£ç  (å¦‚: BRL, PHP, EUR, USDT)
		Rate           float64   `db:"rate"`            // å½“å‰å®žæ—¶ä¹°å…¥åŸºå‡†æ±‡çŽ‡ (1 USD = ? Target)
		InverseRate    float64   `db:"inverse_rate"`    // å€’æ•°æ±‡çŽ‡ (1 Target = ? USD)
		Source         string    `db:"source"`          // æ±‡çŽ‡æ•°æ®æº
		EffectiveDate  time.Time `db:"effective_date"`  // ç”Ÿæ•ˆåŸºå‡†æ—¥æœŸ (UTC)
		CreatedAt      time.Time `db:"created_at"`      // åŒæ­¥å…¥åº“æ—¶é—´
		UpdatedAt      time.Time `db:"updated_at"`      // æ›´æ–°æ—¶é—´
	}
)

func newSystemExchangeRatesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSystemExchangeRatesModel {
	return &defaultSystemExchangeRatesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`system_exchange_rates`",
	}
}

func (m *defaultSystemExchangeRatesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	fastgameSystemExchangeRatesBaseCurrencyTargetCurrencyEffectiveDateKey := fmt.Sprintf("%s%v:%v:%v", bizFastgameSystemExchangeRatesBaseCurrencyTargetCurrencyEffectiveDatePrefix, data.BaseCurrency, data.TargetCurrency, data.EffectiveDate)
	fastgameSystemExchangeRatesIdKey := fmt.Sprintf("%s%v", bizFastgameSystemExchangeRatesIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, fastgameSystemExchangeRatesBaseCurrencyTargetCurrencyEffectiveDateKey, fastgameSystemExchangeRatesIdKey)
	return err
}

func (m *defaultSystemExchangeRatesModel) FindOne(ctx context.Context, id uint64) (*SystemExchangeRates, error) {
	fastgameSystemExchangeRatesIdKey := fmt.Sprintf("%s%v", bizFastgameSystemExchangeRatesIdPrefix, id)
	var resp SystemExchangeRates
	err := m.QueryRowCtx(ctx, &resp, fastgameSystemExchangeRatesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", systemExchangeRatesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemExchangeRatesModel) FindOneByBaseCurrencyTargetCurrencyEffectiveDate(ctx context.Context, baseCurrency string, targetCurrency string, effectiveDate time.Time) (*SystemExchangeRates, error) {
	fastgameSystemExchangeRatesBaseCurrencyTargetCurrencyEffectiveDateKey := fmt.Sprintf("%s%v:%v:%v", bizFastgameSystemExchangeRatesBaseCurrencyTargetCurrencyEffectiveDatePrefix, baseCurrency, targetCurrency, effectiveDate)
	var resp SystemExchangeRates
	err := m.QueryRowIndexCtx(ctx, &resp, fastgameSystemExchangeRatesBaseCurrencyTargetCurrencyEffectiveDateKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `base_currency` = ? and `target_currency` = ? and `effective_date` = ? limit 1", systemExchangeRatesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, baseCurrency, targetCurrency, effectiveDate); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemExchangeRatesModel) Insert(ctx context.Context, data *SystemExchangeRates) (sql.Result, error) {
	fastgameSystemExchangeRatesBaseCurrencyTargetCurrencyEffectiveDateKey := fmt.Sprintf("%s%v:%v:%v", bizFastgameSystemExchangeRatesBaseCurrencyTargetCurrencyEffectiveDatePrefix, data.BaseCurrency, data.TargetCurrency, data.EffectiveDate)
	fastgameSystemExchangeRatesIdKey := fmt.Sprintf("%s%v", bizFastgameSystemExchangeRatesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, systemExchangeRatesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.BaseCurrency, data.TargetCurrency, data.Rate, data.InverseRate, data.Source, data.EffectiveDate)
	}, fastgameSystemExchangeRatesBaseCurrencyTargetCurrencyEffectiveDateKey, fastgameSystemExchangeRatesIdKey)
	return ret, err
}

func (m *defaultSystemExchangeRatesModel) Update(ctx context.Context, newData *SystemExchangeRates) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	fastgameSystemExchangeRatesBaseCurrencyTargetCurrencyEffectiveDateKey := fmt.Sprintf("%s%v:%v:%v", bizFastgameSystemExchangeRatesBaseCurrencyTargetCurrencyEffectiveDatePrefix, data.BaseCurrency, data.TargetCurrency, data.EffectiveDate)
	fastgameSystemExchangeRatesIdKey := fmt.Sprintf("%s%v", bizFastgameSystemExchangeRatesIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, systemExchangeRatesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.BaseCurrency, newData.TargetCurrency, newData.Rate, newData.InverseRate, newData.Source, newData.EffectiveDate, newData.Id)
	}, fastgameSystemExchangeRatesBaseCurrencyTargetCurrencyEffectiveDateKey, fastgameSystemExchangeRatesIdKey)
	return err
}

func (m *defaultSystemExchangeRatesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", bizFastgameSystemExchangeRatesIdPrefix, primary)
}

func (m *defaultSystemExchangeRatesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", systemExchangeRatesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSystemExchangeRatesModel) tableName() string {
	return m.table
}
