// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateMerchantReq struct {
	MerchantCode string `json:"merchantCode" validate:"required"`
	Name         string `json:"name" validate:"required"`
	Status       int64  `json:"status,default=1"`
}

type GameConfigItem struct {
	Id          uint64 `json:"id"`
	MerchantId  uint64 `json:"merchantId"`
	GameCode    string `json:"gameCode"`
	ConfigKey   string `json:"configKey"`
	ConfigValue string `json:"configValue"`
	RtpTier     string `json:"rtpTier"`
	Status      int64  `json:"status"`
}

type GameConfigListReq struct {
	MerchantId uint64 `form:"merchantId" validate:"required"`
	GameCode   string `form:"gameCode,optional"`
}

type GameConfigListResp struct {
	List []GameConfigItem `json:"list"`
}

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	AccessToken string `json:"accessToken"`
	ExpireAt    int64  `json:"expireAt"`
}

type MerchantItem struct {
	Id           uint64 `json:"id"`
	MerchantCode string `json:"merchantCode"`
	Name         string `json:"name"`
	Status       int64  `json:"status"`
}

type MerchantListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"pageSize,default=20"`
}

type MerchantListResp struct {
	Total int64          `json:"total"`
	List  []MerchantItem `json:"list"`
}

type RtpReportItem struct {
	MerchantId  uint64  `json:"merchantId"`
	GameCode    string  `json:"gameCode"`
	Hour        string  `json:"hour"`
	TotalBet    float64 `json:"totalBet"`
	TotalWin    float64 `json:"totalWin"`
	TotalRounds uint64  `json:"totalRounds"`
	ActualRtp   float64 `json:"actualRtp"`
}

type RtpReportReq struct {
	MerchantId uint64 `form:"merchantId,optional"`
	GameCode   string `form:"gameCode,optional"`
	Hours      int    `form:"hours,default=24"`
}

type RtpReportResp struct {
	List []RtpReportItem `json:"list"`
}

type UpdateMerchantReq struct {
	Id     uint64 `path:"id"`
	Name   string `json:"name,optional"`
	Status int64  `json:"status,optional"`
}

type UpsertGameConfigReq struct {
	MerchantId  uint64 `json:"merchantId" validate:"required"`
	GameCode    string `json:"gameCode" validate:"required"`
	ConfigKey   string `json:"configKey" validate:"required"`
	ConfigValue string `json:"configValue" validate:"required"`
	RtpTier     string `json:"rtpTier,optional"`
	Status      int64  `json:"status,default=1"`
}

type RotateMerchantKeyReq struct {
	Id               uint64 `path:"id"`
	GracePeriodHours int64  `json:"gracePeriodHours,optional"`
}

type RotateMerchantKeyResp struct {
	MerchantId       uint64 `json:"merchantId"`
	MerchantCode     string `json:"merchantCode"`
	NewPrivateKey    string `json:"newPrivateKey"`
	GracePeriodHours int64  `json:"gracePeriodHours"`
	RotatedAt        int64  `json:"rotatedAt"`
}

type BlacklistItem struct {
	Id        uint64 `json:"id"`
	ListType  string `json:"listType"`
	ListValue string `json:"listValue"`
	Reason    string `json:"reason"`
	Status    int64  `json:"status"`
	ExpiresAt string `json:"expiresAt,omitempty"`
	CreatedAt int64  `json:"createdAt"`
}

type BlacklistListReq struct {
	ListType string `form:"listType,optional"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
}

type BlacklistListResp struct {
	Total int64           `json:"total"`
	List  []BlacklistItem `json:"list"`
}

type CreateBlacklistReq struct {
	ListType  string `json:"listType" validate:"required"`
	ListValue string `json:"listValue" validate:"required"`
	Reason    string `json:"reason,optional"`
	ExpiresAt string `json:"expiresAt,optional"`
}

type DeleteBlacklistReq struct {
	Id uint64 `path:"id"`
}

type MerchantAllowedIPsReq struct {
	Id uint64 `path:"id"`
}

type MerchantAllowedIPsResp struct {
	MerchantId   uint64   `json:"merchantId"`
	MerchantCode string   `json:"merchantCode"`
	AllowedIps   []string `json:"allowedIps"`
}

type UpdateMerchantAllowedIPsReq struct {
	Id         uint64   `path:"id"`
	AllowedIps []string `json:"allowedIps"`
}

type TraceLookupReq struct {
	TraceId string `path:"traceId"`
}

type TraceSpanItem struct {
	SpanId     string `json:"spanId"`
	Service    string `json:"service"`
	Operation  string `json:"operation"`
	RoundId    string `json:"roundId"`
	Status     string `json:"status"`
	Detail     string `json:"detail"`
	DurationMs uint32 `json:"durationMs"`
	OccurredAt int64  `json:"occurredAt"`
}

type PendingTxItem struct {
	RoundId        string  `json:"roundId"`
	Phase          string  `json:"phase"`
	Status         string  `json:"status"`
	BetAmount      int64   `json:"betAmount"`
	WinAmount      int64   `json:"winAmount"`
	ExpectedAction string  `json:"expectedAction"`
	RetryCount     int64   `json:"retryCount"`
	LastError      string  `json:"lastError,omitempty"`
	CreatedAt      int64   `json:"createdAt"`
}

type TraceLookupResp struct {
	TraceId             string          `json:"traceId"`
	Spans               []TraceSpanItem `json:"spans"`
	PendingTransactions []PendingTxItem `json:"pendingTransactions"`
}
