// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AckRiskAlertReq struct {
	Id uint64 `path:"id"`
}

type AdminUserItem struct {
	Id       uint64 `json:"id"`
	Username string `json:"username"`
	RoleId   uint64 `json:"roleId"`
	RoleName string `json:"roleName"`
	Status   int64  `json:"status"`
}

type AdminUserListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"pageSize,default=20"`
}

type AdminUserListResp struct {
	Total int64           `json:"total"`
	List  []AdminUserItem `json:"list"`
}

type AuditLogItem struct {
	Id           uint64 `json:"id"`
	AdminUserId  uint64 `json:"adminUserId,omitempty"`
	Username     string `json:"username"`
	RoleName     string `json:"roleName"`
	Action       string `json:"action"`
	ResourceType string `json:"resourceType"`
	ResourceId   string `json:"resourceId"`
	HttpMethod   string `json:"httpMethod,omitempty"`
	RequestPath  string `json:"requestPath,omitempty"`
	Detail       string `json:"detail,omitempty"`
	ClientIp     string `json:"clientIp,omitempty"`
	StatusCode   int    `json:"statusCode,omitempty"`
	CreatedAt    int64  `json:"createdAt"`
}

type AuditLogListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
	Action   string `form:"action,optional"`
	Username string `form:"username,optional"`
}

type AuditLogListResp struct {
	Total int64          `json:"total"`
	List  []AuditLogItem `json:"list"`
}

type BlacklistItem struct {
	Id        uint64 `json:"id"`
	ListType  string `json:"listType"`
	ListValue string `json:"listValue"`
	Reason    string `json:"reason"`
	Status    int64  `json:"status"`
	ExpiresAt string `json:"expiresAt,omitempty"`
	CreatedAt int64  `json:"createdAt"`
}

type BlacklistListReq struct {
	ListType string `form:"listType,optional"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
}

type BlacklistListResp struct {
	Total int64           `json:"total"`
	List  []BlacklistItem `json:"list"`
}

type ConfirmDailySettlementReq struct {
	Id uint64 `path:"id"`
}

type CreateAdminUserReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
	RoleId   uint64 `json:"roleId" validate:"required"`
	Status   int64  `json:"status,default=1"`
}

type CreateBlacklistReq struct {
	ListType  string `json:"listType" validate:"required"`
	ListValue string `json:"listValue" validate:"required"`
	Reason    string `json:"reason,optional"`
	ExpiresAt string `json:"expiresAt,optional"`
}

type CreateMerchantGameReq struct {
	MerchantId  uint64 `json:"merchantId" validate:"required"`
	GameId      uint64 `json:"gameId" validate:"required"`
	RtpTierCode string `json:"rtpTierCode,optional"`
	MinBetMinor int64  `json:"minBetMinor,optional"`
	MaxBetMinor int64  `json:"maxBetMinor,optional"`
	SortOrder   int64  `json:"sortOrder,optional"`
}

type CreateMerchantReq struct {
	MerchantCode string `json:"merchantCode" validate:"required"`
	Name         string `json:"name" validate:"required"`
	Status       int64  `json:"status,default=1"`
}

type CreateMerchantResp struct {
	Id           uint64 `json:"id"`
	MerchantCode string `json:"merchantCode"`
	Name         string `json:"name"`
	Status       int64  `json:"status"`
	PrivateKey   string `json:"privateKey"`
}

type CreatePlatformGameReq struct {
	GameCode      string `json:"gameCode" validate:"required"`
	Name          string `json:"name" validate:"required"`
	CategoryId    uint64 `json:"categoryId,optional"`
	GameType      string `json:"gameType" validate:"required"`
	DefaultRtpPpm int64  `json:"defaultRtpPpm,optional"`
	Volatility    string `json:"volatility,optional"`
	MinBetMinor   int64  `json:"minBetMinor,optional"`
	MaxBetMinor   int64  `json:"maxBetMinor,optional"`
	ClientVersion string `json:"clientVersion,optional"`
	ThumbnailUrl  string `json:"thumbnailUrl,optional"`
	Status        int64  `json:"status,default=1"`
}

type DailySettlementItem struct {
	Id           uint64  `json:"id"`
	MerchantId   uint64  `json:"merchantId"`
	MerchantCode string  `json:"merchantCode"`
	SettleDate   string  `json:"settleDate"`
	TotalBet     float64 `json:"totalBet"`
	TotalWin     float64 `json:"totalWin"`
	TotalRounds  uint64  `json:"totalRounds"`
	ActualRtp    float64 `json:"actualRtp"`
	Status       int64   `json:"status"`
}

type DailySettlementListReq struct {
	MerchantId uint64 `form:"merchantId,optional"`
	Page       int    `form:"page,default=1"`
	PageSize   int    `form:"pageSize,default=20"`
}

type DailySettlementListResp struct {
	Total int64                 `json:"total"`
	List  []DailySettlementItem `json:"list"`
}

type DeleteBlacklistReq struct {
	Id uint64 `path:"id"`
}

type DeleteGameConfigReq struct {
	Id uint64 `path:"id"`
}

type DeleteMerchantGameReq struct {
	Id uint64 `path:"id"`
}

type FileUploadResp struct {
	URL      string `json:"url"`
	Filename string `json:"filename"`
	Size     int64  `json:"size"`
}

type GameCategoryItem struct {
	Id   uint64 `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type GameCategoryListResp struct {
	List []GameCategoryItem `json:"list"`
}

type GameConfigItem struct {
	Id          uint64 `json:"id"`
	MerchantId  uint64 `json:"merchantId"`
	GameCode    string `json:"gameCode"`
	ConfigKey   string `json:"configKey"`
	ConfigValue string `json:"configValue"`
	RtpTier     string `json:"rtpTier"`
	Status      int64  `json:"status"`
}

type GameConfigListReq struct {
	MerchantId uint64 `form:"merchantId" validate:"required"`
	GameCode   string `form:"gameCode,optional"`
}

type GameConfigListResp struct {
	List []GameConfigItem `json:"list"`
}

type GameRtpTierItem struct {
	Id           uint64 `json:"id"`
	GameId       uint64 `json:"gameId"`
	TierCode     string `json:"tierCode"`
	TargetRtpPpm int64  `json:"targetRtpPpm"`
	ParSheetRef  string `json:"parSheetRef,omitempty"`
	Weight       int64  `json:"weight"`
}

type GameRtpTierListReq struct {
	Id uint64 `path:"id"`
}

type GameRtpTierListResp struct {
	List []GameRtpTierItem `json:"list"`
}

type I18nDictionaryReq struct {
	Bundle string `form:"bundle" validate:"required"`
	Locale string `form:"locale,optional"`
}

type I18nDictionaryResp struct {
	Bundle   string            `json:"bundle"`
	Locale   string            `json:"locale"`
	Messages map[string]string `json:"messages"`
}

// LedgerAdjustmentReq 人工调账请求。
//
// 为什么必填 externalTxId 与 remark：玩家余额的权威在商户钱包侧，本地台账
// 只是镜像。人工调账**不是**在本地凭空改余额，而是登记一笔"已经在钱包侧
// 做过的人工调整"，所以钱包凭证号与调整原因是审计的最低要求——缺了任何
// 一条，事后都无法回答"这笔钱凭什么动"。
type LedgerAdjustmentReq struct {
	MerchantId  uint64 `json:"merchantId" validate:"required"`
	UserId      string `json:"userId" validate:"required"`
	TypeCode    string `json:"typeCode" validate:"required"`
	AmountMinor int64  `json:"amountMinor" validate:"required"`
	// ExternalTxId 商户钱包侧的人工调整凭证号。
	ExternalTxId string `json:"externalTxId" validate:"required"`
	// Remark 调整原因（写入流水的 remark，便于只查流水就能还原上下文）。
	Remark   string `json:"remark" validate:"required"`
	Currency string `json:"currency,optional"`
	// OperatorIp 客户端 IP，由 handler 用 pkg/httputil.ClientIP 取出后填入；
	// logic 拿不到 http.Request，所以在这里传进来写入 extra_data 供审计追溯。
	OperatorIp string `json:"-"`
}

// LedgerAdjustmentResp 人工调账返回体。金额一律 minor units（scale=10000）。
type LedgerAdjustmentResp struct {
	TransactionId      string `json:"transactionId"`
	TxType             string `json:"txType"`
	Direction          string `json:"direction"`
	AmountMinor        int64  `json:"amountMinor"`
	BalanceBeforeMinor int64  `json:"balanceBeforeMinor"`
	BalanceAfterMinor  int64  `json:"balanceAfterMinor"`
	Status             string `json:"status"`
	// DriftMinor 不可解释差额（钱包余额 - 本地按类型推算）。人工调账不传
	// 钱包余额（本地推算镜像自洽），因此恒为 0；字段保留是为了与其它账变
	// 响应结构统一，客户端不必区分接口。
	DriftMinor int64 `json:"driftMinor"`
	// Duplicated=true 表示命中幂等键，本次没有再动余额镜像。
	Duplicated bool `json:"duplicated"`
}

// LedgerTransactionListReq 账变流水查询条件，全部可选。
type LedgerTransactionListReq struct {
	MerchantId uint64 `form:"merchantId,optional"`
	UserId     string `form:"userId,optional"`
	TxType     string `form:"txType,optional"`
	RoundId    string `form:"roundId,optional"`
	Status     string `form:"status,optional"`
	// DriftOnly=true 只看存在不可解释差额的流水（本地镜像与钱包对不上的那些）。
	DriftOnly bool `form:"driftOnly,optional"`
	// StartTime/EndTime 支持 "2006-01-02 15:04:05"、"2006-01-02" 与 RFC3339；
	// 不带时区的一律按 UTC 解释（账变时间以 UTC 入库）。
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=20"`
}

// LedgerTransactionItem 账变流水列表项。金额一律 minor units（scale=10000）。
type LedgerTransactionItem struct {
	Id            uint64 `json:"id"`
	TransactionId string `json:"transactionId"`
	ExternalTxId  string `json:"externalTxId"`
	TxType        string `json:"txType"`
	Direction     string `json:"direction"`
	MerchantId    uint64 `json:"merchantId"`
	MerchantCode  string `json:"merchantCode"`
	UserId        string `json:"userId"`
	GameCode      string `json:"gameCode"`
	RoundId       string `json:"roundId"`
	Currency      string `json:"currency"`
	Amount        int64  `json:"amount"`
	BalanceBefore int64  `json:"balanceBefore"`
	BalanceAfter  int64  `json:"balanceAfter"`
	// DriftMinor 不可解释差额：钱包返回余额 - 本地按类型推算余额。
	DriftMinor int64  `json:"driftMinor"`
	Status     string `json:"status"`
	Remark     string `json:"remark"`
	// TypeName 账变类型中文名（来自 transaction_types，一次性查表映射，避免 N+1）。
	TypeName  string `json:"typeName"`
	CreatedAt int64  `json:"createdAt"`
}

type LedgerTransactionListResp struct {
	List     []LedgerTransactionItem `json:"list"`
	Total    int64                   `json:"total"`
	Page     int                     `json:"page"`
	PageSize int                     `json:"pageSize"`
}

type LocaleItem struct {
	Code       string `json:"code"`
	Name       string `json:"name"`
	NativeName string `json:"nativeName"`
	IsDefault  bool   `json:"isDefault"`
}

type LocaleListResp struct {
	List []LocaleItem `json:"list"`
}

type LoginReq struct {
	Username     string `json:"username" validate:"required"`
	Password     string `json:"password" validate:"required"`
	TotpCode     string `json:"totpCode,optional"`
	RecoveryCode string `json:"recoveryCode,optional"`
}

type LoginResp struct {
	AccessToken       string `json:"accessToken"`
	ExpireAt          int64  `json:"expireAt"`
	RoleName          string `json:"roleName"`
	RequiresTotpSetup bool   `json:"requiresTotpSetup,omitempty"`
}

type MerchantAllowedIPsReq struct {
	Id uint64 `path:"id"`
}

type MerchantAllowedIPsResp struct {
	MerchantId   uint64   `json:"merchantId"`
	MerchantCode string   `json:"merchantCode"`
	AllowedIps   []string `json:"allowedIps"`
}

type MerchantGameItem struct {
	Id            uint64 `json:"id"`
	MerchantId    uint64 `json:"merchantId"`
	MerchantCode  string `json:"merchantCode"`
	GameId        uint64 `json:"gameId"`
	GameCode      string `json:"gameCode"`
	GameName      string `json:"gameName"`
	GameType      string `json:"gameType"`
	GameStatus    int64  `json:"gameStatus"`
	RtpTierCode   string `json:"rtpTierCode"`
	MinBetMinor   int64  `json:"minBetMinor,omitempty"`
	MaxBetMinor   int64  `json:"maxBetMinor,omitempty"`
	SortOrder     int64  `json:"sortOrder"`
	Status        int64  `json:"status"`
	DefaultRtpPpm int64  `json:"defaultRtpPpm"`
}

type MerchantGameListReq struct {
	MerchantId uint64 `form:"merchantId" validate:"required"`
	Page       int    `form:"page,default=1"`
	PageSize   int    `form:"pageSize,default=50"`
}

type MerchantGameListResp struct {
	Total int64              `json:"total"`
	List  []MerchantGameItem `json:"list"`
}

type MerchantItem struct {
	Id           uint64 `json:"id"`
	MerchantCode string `json:"merchantCode"`
	Name         string `json:"name"`
	Status       int64  `json:"status"`
}

type MerchantListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"pageSize,default=20"`
}

type MerchantListResp struct {
	Total int64          `json:"total"`
	List  []MerchantItem `json:"list"`
}

type PendingTxItem struct {
	RoundId        string `json:"roundId"`
	Phase          string `json:"phase"`
	Status         string `json:"status"`
	BetAmount      int64  `json:"betAmount"`
	WinAmount      int64  `json:"winAmount"`
	ExpectedAction string `json:"expectedAction"`
	RetryCount     int64  `json:"retryCount"`
	LastError      string `json:"lastError,omitempty"`
	CreatedAt      int64  `json:"createdAt"`
}

type PlatformGameItem struct {
	Id            uint64 `json:"id"`
	GameCode      string `json:"gameCode"`
	Name          string `json:"name"`
	CategoryId    uint64 `json:"categoryId,omitempty"`
	CategoryCode  string `json:"categoryCode"`
	CategoryName  string `json:"categoryName"`
	GameType      string `json:"gameType"`
	DefaultRtpPpm int64  `json:"defaultRtpPpm"`
	Volatility    string `json:"volatility,omitempty"`
	MinBetMinor   int64  `json:"minBetMinor"`
	MaxBetMinor   int64  `json:"maxBetMinor"`
	ClientVersion string `json:"clientVersion,omitempty"`
	ThumbnailUrl  string `json:"thumbnailUrl,omitempty"`
	Status        int64  `json:"status"`
}

type PlatformGameListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
	GameType string `form:"gameType,optional"`
}

type PlatformGameListResp struct {
	Total int64              `json:"total"`
	List  []PlatformGameItem `json:"list"`
}

type ResetWalletBreakerReq struct {
	MerchantCode string `json:"merchantCode" validate:"required"`
}

type RiskAlertItem struct {
	Id           uint64 `json:"id"`
	AlertType    string `json:"alertType"`
	ScopeType    string `json:"scopeType"`
	ScopeValue   string `json:"scopeValue"`
	MerchantCode string `json:"merchantCode"`
	GameCode     string `json:"gameCode"`
	RtpPPM       int64  `json:"rtpPpm"`
	TotalBet     int64  `json:"totalBet"`
	TotalWin     int64  `json:"totalWin"`
	SampleSize   int64  `json:"sampleSize"`
	ActionTaken  string `json:"actionTaken"`
	Status       string `json:"status"`
	CreatedAt    int64  `json:"createdAt"`
}

type RiskAlertsReq struct {
	Limit int `form:"limit,default=50"`
}

type RiskAlertsResp struct {
	List []RiskAlertItem `json:"list"`
}

type RoleItem struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type RoleListResp struct {
	List []RoleItem `json:"list"`
}

type RollupSettlementPeriodReq struct {
	Id uint64 `path:"id"`
}

type RollupSettlementPeriodResp struct {
	RolledUp int `json:"rolledUp"`
}

type RotateMerchantKeyReq struct {
	Id               uint64 `path:"id"`
	GracePeriodHours int64  `json:"gracePeriodHours,optional"`
}

type RotateMerchantKeyResp struct {
	MerchantId       uint64 `json:"merchantId"`
	MerchantCode     string `json:"merchantCode"`
	NewPrivateKey    string `json:"newPrivateKey"`
	GracePeriodHours int64  `json:"gracePeriodHours"`
	RotatedAt        int64  `json:"rotatedAt"`
}

type RtpReportItem struct {
	MerchantId  uint64  `json:"merchantId"`
	GameCode    string  `json:"gameCode"`
	Hour        string  `json:"hour"`
	TotalBet    float64 `json:"totalBet"`
	TotalWin    float64 `json:"totalWin"`
	TotalRounds uint64  `json:"totalRounds"`
	ActualRtp   float64 `json:"actualRtp"`
}

type RtpReportReq struct {
	MerchantId uint64 `form:"merchantId,optional"`
	GameCode   string `form:"gameCode,optional"`
	Hours      int    `form:"hours,default=24"`
}

type RtpReportResp struct {
	List []RtpReportItem `json:"list"`
}

type SettlementPeriodItem struct {
	Id           uint64  `json:"id"`
	MerchantId   uint64  `json:"merchantId"`
	MerchantCode string  `json:"merchantCode"`
	PeriodType   string  `json:"periodType"`
	PeriodStart  string  `json:"periodStart"`
	PeriodEnd    string  `json:"periodEnd"`
	CurrencyCode string  `json:"currencyCode"`
	TotalBet     float64 `json:"totalBet"`
	TotalWin     float64 `json:"totalWin"`
	Ggr          float64 `json:"ggr"`
	Commission   float64 `json:"commission"`
	NetPayable   float64 `json:"netPayable"`
	TotalRounds  uint64  `json:"totalRounds"`
	Status       string  `json:"status"`
	ConfirmedBy  uint64  `json:"confirmedBy,omitempty"`
	ConfirmedAt  string  `json:"confirmedAt,omitempty"`
	Notes        string  `json:"notes,omitempty"`
}

type SettlementPeriodListReq struct {
	MerchantId uint64 `form:"merchantId,optional"`
	PeriodType string `form:"periodType,optional"`
	Page       int    `form:"page,default=1"`
	PageSize   int    `form:"pageSize,default=20"`
}

type SettlementPeriodListResp struct {
	Total int64                  `json:"total"`
	List  []SettlementPeriodItem `json:"list"`
}

type SyncDailySettlementReq struct {
	MerchantId uint64 `json:"merchantId,optional"`
	Days       int    `json:"days,default=7"`
}

type SyncDailySettlementResp struct {
	Synced int `json:"synced"`
}

type TotpConfirmReq struct {
	TotpCode string `json:"totpCode" validate:"required"`
}

type TotpConfirmResp struct {
	AccessToken   string   `json:"accessToken"`
	ExpireAt      int64    `json:"expireAt"`
	RoleName      string   `json:"roleName"`
	RecoveryCodes []string `json:"recoveryCodes"`
}

type TotpSetupResp struct {
	ProvisioningUri string `json:"provisioningUri"`
	Secret          string `json:"secret"`
}

type TraceByRoundReq struct {
	RoundId string `path:"roundId"`
	// MerchantId 可选；round_id 只在商户内唯一（唯一键 uk_merchant_round），
	// 带上可保证查到的是该商户那一局。不传则按 round_id 取最近一条。
	MerchantId uint64 `form:"merchantId,optional"`
}

type TraceLookupReq struct {
	TraceId string `path:"traceId"`
}

type TraceLookupResp struct {
	TraceId             string          `json:"traceId"`
	RoundId             string          `json:"roundId,omitempty"`
	Spans               []TraceSpanItem `json:"spans"`
	PendingTransactions []PendingTxItem `json:"pendingTransactions"`
}

type TraceSpanItem struct {
	SpanId     string `json:"spanId"`
	Service    string `json:"service"`
	Operation  string `json:"operation"`
	RoundId    string `json:"roundId"`
	Status     string `json:"status"`
	Detail     string `json:"detail"`
	DurationMs uint32 `json:"durationMs"`
	OccurredAt int64  `json:"occurredAt"`
}

type UpdateAdminUserReq struct {
	Id       uint64 `path:"id"`
	RoleId   uint64 `json:"roleId,optional"`
	Status   int64  `json:"status,optional"`
	Password string `json:"password,optional"`
}

type UpdateMerchantAllowedIPsReq struct {
	Id         uint64   `path:"id"`
	AllowedIps []string `json:"allowedIps"`
}

type UpdateMerchantGameReq struct {
	Id          uint64 `path:"id"`
	RtpTierCode string `json:"rtpTierCode,optional"`
	MinBetMinor int64  `json:"minBetMinor,optional"`
	MaxBetMinor int64  `json:"maxBetMinor,optional"`
	SortOrder   int64  `json:"sortOrder,optional"`
	Status      int64  `json:"status,optional"`
}

type UpdateMerchantReq struct {
	Id     uint64 `path:"id"`
	Name   string `json:"name,optional"`
	Status int64  `json:"status,optional"`
}

type UpdatePlatformGameReq struct {
	Id            uint64 `path:"id"`
	Name          string `json:"name,optional"`
	CategoryId    uint64 `json:"categoryId,optional"`
	DefaultRtpPpm int64  `json:"defaultRtpPpm,optional"`
	Volatility    string `json:"volatility,optional"`
	MinBetMinor   int64  `json:"minBetMinor,optional"`
	MaxBetMinor   int64  `json:"maxBetMinor,optional"`
	ClientVersion string `json:"clientVersion,optional"`
	ThumbnailUrl  string `json:"thumbnailUrl,optional"`
	Status        int64  `json:"status,optional"`
}

type UpsertGameConfigReq struct {
	MerchantId  uint64 `json:"merchantId" validate:"required"`
	GameCode    string `json:"gameCode" validate:"required"`
	ConfigKey   string `json:"configKey" validate:"required"`
	ConfigValue string `json:"configValue" validate:"required"`
	RtpTier     string `json:"rtpTier,optional"`
	Status      int64  `json:"status,default=1"`
}

type WalletBreakerItem struct {
	MerchantCode string `json:"merchantCode"`
	Open         bool   `json:"open"`
	OpenedAt     int64  `json:"openedAt,omitempty"`
	Overridden   bool   `json:"overridden"`
}

type WalletBreakersResp struct {
	List []WalletBreakerItem `json:"list"`
}
