// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BalanceReq struct {
	MerchantId   string `form:"merchantId" validate:"required"`
	UserId       uint64 `form:"userId" validate:"required"`
	SessionToken string `form:"sessionToken,optional"`
}

type BalanceResp struct {
	Balance int64 `json:"balance"`
}

type SessionReq struct {
	MerchantId string `json:"merchantId" validate:"required"`
	UserId     uint64 `json:"userId" validate:"required"`
	GameCode   string `json:"gameCode" validate:"required"`
	ClientSeed string `json:"clientSeed,optional"`
}

type SessionResp struct {
	SessionToken      string `json:"sessionToken"`
	ServerSeedHash    string `json:"serverSeedHash"`
	ClientSeed        string `json:"clientSeed"`
	DynamicSessionKey string `json:"dynamicSessionKey"`
	NextSequenceId    uint64 `json:"nextSequenceId"`
	ExpiresAt         int64  `json:"expiresAt"`
}

type BetReq struct {
	MerchantId       string `json:"merchantId" validate:"required"`
	UserId           uint64 `json:"userId" validate:"required"`
	SessionToken     string `json:"sessionToken" validate:"required"`
	GameCode         string `json:"gameCode" validate:"required"`
	Action           string `json:"action" validate:"required"` // 仅允许 cast
	BetAmount        int64  `json:"betAmount" validate:"required,gt=0"`
	RoundId          string `json:"roundId" validate:"required"`
	SequenceId       uint64 `json:"sequenceId" validate:"required"`
	IdempotencyToken string `json:"idempotencyToken,optional"`
	ClientSeed       string `json:"clientSeed,optional"`
}

type ProvablyFairProof struct {
	ServerSeedHash string  `json:"serverSeedHash"`
	ServerSeed     string  `json:"serverSeed"`
	ClientSeed     string  `json:"clientSeed"`
	Nonce          string  `json:"nonce"`
	Roll           float64 `json:"roll"`
}

type ReplayInputs struct {
	ServerSeed string `json:"serverSeed"`
	ClientSeed string `json:"clientSeed"`
	Nonce      string `json:"nonce"`
	BetAmount  int64  `json:"betAmount"`
}

type ReplayPoint struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type ReplayScene struct {
	Weather        string        `json:"weather"`
	FishSpecies    string        `json:"fishSpecies"`
	FishPath       []ReplayPoint `json:"fishPath"`
	BiteProp       string        `json:"biteProp"`
	CastDurationMs int           `json:"castDurationMs"`
	FishSpeed      float64       `json:"fishSpeed"`
}

type ReplayPayload struct {
	Inputs ReplayInputs `json:"inputs"`
	Scene  ReplayScene  `json:"scene"`
}

type BetResp struct {
	RoundId          string            `json:"roundId"`
	WinAmount        int64             `json:"winAmount"`
	Multiplier       int64             `json:"multiplier"`
	Balance          int64             `json:"balance"`
	RtpTier          string            `json:"rtpTier"`
	FishState        string            `json:"fishState"`
	AnimationKey     string            `json:"animationKey"`
	SequenceId       uint64            `json:"sequenceId"`
	SettlementStatus string            `json:"settlementStatus"` // settled / pending
	ProvablyFair     ProvablyFairProof `json:"provablyFair"`
	Replay           ReplayPayload     `json:"replay"`
}

type ReplayReq struct {
	RoundId string `path:"roundId"`
}

type ReplayComputeReq struct {
	ServerSeed string `json:"serverSeed" validate:"required"`
	ClientSeed string `json:"clientSeed" validate:"required"`
	Nonce      string `json:"nonce" validate:"required"`
	BetAmount  int64  `json:"betAmount" validate:"required,gt=0"`
	RtpTier    string `json:"rtpTier,optional"`
}

type ReplayResp struct {
	RoundId      string            `json:"roundId,omitempty"`
	SequenceId   uint64            `json:"sequenceId,omitempty"`
	Replay       ReplayPayload     `json:"replay"`
	ProvablyFair ProvablyFairProof `json:"provablyFair"`
	WinAmount    int64             `json:"winAmount"`
	Multiplier   int64             `json:"multiplier"`
	FishState    string            `json:"fishState"`
	AnimationKey string            `json:"animationKey"`
}
