// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BalanceReq struct {
	MerchantId string `form:"merchantId" validate:"required"`
	UserId     uint64 `form:"userId" validate:"required"`
}

type BalanceResp struct {
	Balance float64 `json:"balance"`
}

type BetReq struct {
	MerchantId       string  `json:"merchantId" validate:"required"`
	UserId           uint64  `json:"userId" validate:"required"`
	RoundId          string  `json:"roundId" validate:"required"` // 幂等键
	GameCode         string  `json:"gameCode" validate:"required"`
	BetAmount        float64 `json:"betAmount" validate:"required,gt=0"`
	IdempotencyToken string  `json:"idempotencyToken" validate:"required"`
}

type BetResp struct {
	RoundId      string  `json:"roundId"`
	WinAmount    float64 `json:"winAmount"`
	Multiplier   float64 `json:"multiplier"`
	Balance      float64 `json:"balance"`
	RtpTier      string  `json:"rtpTier"`
	FishState    string  `json:"fishState"` // 咬钩状态: miss / bite / big_win
	AnimationKey string  `json:"animationKey"`
}
